### ISSUE TITLE
Delete (instead of deactivate) completed timers

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#109]
I don’t think there is any reason to keep timers around after that have completed and been used for an entry. Instead they should just be removed. I’m interested to hear if any users have a use case that involves keeping them around.

This relates to #108, which is planned for a 1.x release.

**Comment by LostSoulfly** [comment]
I kept yelling at my wife for leaving so many unused timers around because I assumed they would disappear automatically! No complaints here.

**Comment by cdubz** [comment]
Re-opening to correct automated release notes dealy.

**Comment by bluesmokeresearch** [comment]
A little late to the party here, but I am using the android app by Paul and it relies on re-using the same timers over and over to make them quickly available. Reading the latest release notes, I believe the timers autodelete change (Timers no longer have an "end" and cannot be stopped -- only deleted or used to create a new entry with times) means they will have to be recreated every time either in the webpage outside the app or with a 'recreate default timers' command in the app and it will essentially break the workflow.

I see how for many people the autodelete would be the _preferred_ and probably _default_ setting though. One option is that the app could be updated to adopt a new model or timer management, but depending on how deep the change was to the code in 2.0.0,  perhaps the timer end vs delete could be an settings toggle in babybuddy?

**Comment by MrApplejuice** [comment]
@bluesmokeresearch

Hey there! Yeah, @cbudz made me (and others) aware of the pending breaking change over here: https://github.com/babybuddy/babybuddy/issues/515#issuecomment-1540051632

I am trying to do a sort-of "mad dash" to push an update in time for the 2.0 release of babybuddy that will make the app compatible with either 1.x or 2.x before BabyBuddy 2.0 goes live. You can follow the progress over here: https://github.com/MrApplejuice/BabyBuddyAndroid/tree/fix-v2.0-breakage

Unfortunately, the code-quality of the app's timer-implementation was a bit "meh" so this took me a little while to fix things. I hope that I will have something in working order by next week, which then needs to go through a short test-phase and then can be published. So ETA ~27th of May, I hope!

**Comment by bluesmokeresearch** [comment]
@MrApplejuice Ah that is exciting news! We are very thankful for the app and look forward to it pushing out :)

**Comment by bluesmokeresearch** [comment]
@MrApplejuice I receive the OTA update from the play store on all our devices by yesterday morning so I will update the main server soon and report back. Thanks again.

**Comment by MrApplejuice** [comment]
I hope that everything will work sufficiently well! :-)
