### ISSUE TITLE
[Feature Request] API Endpoints to end timers and associate that timer with a task

### ISSUE THREAD

**Issue by PTST** [babybuddy/babybuddy#131]
## Basic functionality needed:
API endpoint for ending running timers, possibly via a PUT/PATCH request to the existing timer endpoint (#126).
Then either as a separate endpoint you should be able to associate a timer with a task like it's possible via the web interface. Either as a new endpoint, or by extending the existing POST endpoint to accept a timer id instead of a start & end parameter

## Possible use cases
I would very much like to integrate this app with my [Home Assistant](https://www.home-assistant.io/) instance. This would make it easy for me to set up physical buttons around the bed and the changing table that would post data to Baby Buddy.

I am well versed enough in Python and the Home Assistant code base, that creating a baby buddy component for Home Assistant would be trivial. But with the current API limitations it is severely limited in its use case because of the lack of timer management via the Baby Buddy API

## Why am i not just creating a pull request for this.
To be honest, i am not at all familiar with either Django as a whole or Django Rest Framework specifically. And while i did attempt to add basic PUT/PATCH functionality to the timer endpoint, the code quickly became ugly and unwieldy due to my unfamiliarity with the Django structure.

So now i am hoping that in due time somebody with the proper knowledge will be able to add these features.

**Comment by cdubz** [comment]
> by extending the existing POST endpoint to accept a timer id instead of a start & end parameter.

I think this would be the ideal. Right now Baby Buddy's DRF integration is pretty much the default. I'm not sure how difficult it will be to customize in this way, but I suspect it's doable. I'll try to take some time to look at this soon.

I would love to see any Home Assistant integration you put together open sourced (and potentially under the Baby Buddy org repos).

**Comment by PTST** [comment]
Thanks for the quick and positive response :slightly_smiling_face: 

I will of course open source everything under the MIT license, just like my other components. 

Whether this should be published to the baby buddy org or my private github repo, I will let you decide completely.

**Comment by cdubz** [comment]
#132 has been merged in to `master` so `PATCH` and `DELETE` API operations are now supported. The timers will take a little longer so not totally sure when I'll be able to get to it, but definitely doable.

**Comment by PTST** [comment]
Wow, I am very impressed with the progress you are making on this already!

**Comment by cdubz** [comment]
Well you made an annoyingly good suggestion (:

This is on `master` now. I don't think there will be a release any time soon so you'd need to work from that. Let me know if you have any feedback once you get a chance to try things out!

**Comment by PTST** [comment]
@cdubz 
Thanks for the very quick implementation.

I do have one thing i wondering about regarding the API.
When creating new timers via the post request. The only required parameter is the "user".
Is there any reason that this is not just inferred from the token used to authenticate?

**Comment by cdubz** [comment]
@PTST note this is implemented now (#134)
