### ISSUE TITLE
Feature request: Allow hiding the "Last Feeding Method" card

### ISSUE THREAD

**Issue by phardy** [babybuddy/babybuddy#139]
For children who are exclusively formula-fed, the last feeding method card could be considered redundant, and it takes up a lot of space. Would a per-child setting to hide this card be worthwhile?

It does also occur to me that this could be related to the way cards are hidden in #137 . But that's less useful for children who transition to exclusively formula (I have a couple of weeks of breast-fed data I'd like to retain, for example). And if #138 is merged then it won't work anyway.

**Comment by cdubz** [comment]
What I'm most interested in wrt cards is #34. #137 could end up being an OK stop gap, sort of, but ultimately I'd like the give the user greater control over the cards.

**Comment by phardy** [comment]
Oh, I really should have looked at the previous issues first. This is basically a subset of #34. Sorry about that.
