### ISSUE TITLE
server error 500 after initial login

### ISSUE THREAD

**Issue by Ylawy** [babybuddy/babybuddy#140]
Hi,

following this comment https://github.com/babybuddy/babybuddy/issues/129#issuecomment-597588947 I was able to set up baby buddy using docker.
However, when I do the initial login with admin/admin I get a server error 500.

The logs don't indicate any problem:

`[2020-04-01 13:22:29 +0000] [1] [INFO] Starting gunicorn 20.0.4,
[2020-04-01 13:22:29 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1),
[2020-04-01 13:22:29 +0000] [1] [INFO] Using worker: sync,
[2020-04-01 13:22:29 +0000] [1] [INFO] Server is ready. Spawning workers,
[2020-04-01 13:22:29 +0000] [7] [INFO] Booting worker with pid: 7,
[2020-04-01 13:22:29 +0000] [7] [INFO] Worker spawned (pid: 7),
192.168.178.38 - - [01/Apr/2020:15:22:49 +0200] "GET / HTTP/1.1" 302 0 "http://192.168.178.63:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
192.168.178.38 - - [01/Apr/2020:15:22:49 +0200] "GET /login/?next=/ HTTP/1.1" 200 3467 "http://192.168.178.63:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
192.168.178.38 - - [01/Apr/2020:15:22:57 +0200] "POST /login/ HTTP/1.1" 500 145 "http://192.168.178.63:8001/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
192.168.178.38 - - [01/Apr/2020:15:22:58 +0200] "GET /login/?next=/ HTTP/1.1" 200 3467 "http://192.168.178.63:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
192.168.178.38 - - [01/Apr/2020:15:23:15 +0200] "POST /login/ HTTP/1.1" 500 145 "http://192.168.178.63:8001/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
192.168.178.38 - - [01/Apr/2020:15:23:16 +0200] "GET /login/?next=/ HTTP/1.1" 200 3467 "http://192.168.178.63:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
192.168.178.38 - - [01/Apr/2020:15:23:18 +0200] "GET /password_reset/ HTTP/1.1" 200 2918 "http://192.168.178.63:8001/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
192.168.178.38 - - [01/Apr/2020:15:23:22 +0200] "GET /login/?next=/ HTTP/1.1" 200 3467 "http://192.168.178.63:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
192.168.178.38 - - [01/Apr/2020:15:24:23 +0200] "POST /login/ HTTP/1.1" 500 145 "http://192.168.178.63:8001/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",`
Any idea what's wrong?

Thanks!

**Comment by cdubz** [comment]
Hm, in the `app.environment` section, try adding `DEBUG=True`. That should give you some more useful information about the 500 error when it hits.

**Comment by Ylawy** [comment]
Thanks, that helped. Apparently I didn't provide a password :) I tried copy-paste as well as typing it out.

"Request Method: | POST
-- | --
http://192.168.x.x:8001/login/
3.0.3
OperationalError
fe_sendauth: no password supplied
/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py in connect, line 126
/usr/local/bin/python
3.8.2
['/app',  '/usr/local/bin',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages',  '/usr/local/lib/python3.8/site-packages/odf',  '/usr/local/lib/python3.8/site-packages/odf',  '/usr/local/lib/python3.8/site-packages/odf',  '/usr/local/lib/python3.8/site-packages/odf',  '/usr/local/lib/python3.8/site-packages/odf',  '/usr/local/lib/python3.8/site-packages/odf',  '/usr/local/lib/python3.8/site-packages/odf']"

**Comment by cdubz** [comment]
I haven’t seen that message before, but I think it’s actually say that it can’t access the _database_ and no password is provided.

**Comment by Ylawy** [comment]
Possible, but the documentation doesn't mention that a password for the postgres container is required.

This is my docker compose file:
  `db:
    image: postgres
    container_name: BBdb
    environment:
      - PGDATA=/db-data
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=Europe/Berlin
    volumes:
      - ./BBdb:/db-data:rw
   app:
    image: babybuddy/babybuddy
    container_name: babybuddy
    # See README.md#configuration for other environment configuration options.
    environment:
      - ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.docker
      - SECRET_KEY=key
      - TIME_ZONE=Europe/Berlin
      - DEBUG=true
    volumes:
      - ./BBapp/media:/app/media:rw
    command: gunicorn -c /app/gunicorn.py babybuddy.wsgi
    ports:
      - 8001:8000
    depends_on:
      - db

volumes:
  db: {}
  media: {}`

I also defined

**Comment by cdubz** [comment]
Yeah I don’t really get the auth stuff myself, but I have seen it discussed elsewhere. Docker support for BB is a more of community effort, I don’t use it myself. You may want to try chiming in to one of those existing issues or asking in Gitter.

**Comment by 5280Pipedream** [comment]
AFK right now so to access to my files but putting in the 'POSTGRES_PASSWORD = password' under the environment of the dB container should resolve the issue.

Verify that the dB container starts properly when doing 'docker-compose up' . 

Do not use the -d flag so that you can see the errors as the container starts. 

If you don't get any errors then make sure you run the database migrations as outlined in the documentation. Then try to login.

**Comment by Ylawy** [comment]
> 
> 
> AFK right now so to access to my files but putting in the `POSTGRES_HOST_AUTH_METHOD=trust` under the environment of the dB container should resolve the issue.
> 
>     1. Verify that your `docker-compose.yaml` file is valid yaml.
> 
>     2. Try changing the volumes section from `- ./BBdb:/db-data:rw` to `db:/db-data`
> 
>     3. Verify that the dB container starts properly when doing `docker-compose up` .
> 
> 
> Do not use the -d flag so that you can see the errors as the container starts.
> 
> If you don't get any errors then make sure you run the database migrations as outlined in the documentation. Then try to login with the default admin user/password.

thanks for your repy.
1. I verified it is a valid docker-compose file.
2. changed the volume - didnt make a difference.
3. both container run just fine.

The solution here is your last point.
I had to run the following commands in the babybuddy docker file:
```python manage.py migrate´´´ and ```python manage.py createcachetable´´´ to migrate the database.
