### ISSUE TITLE
docker-compose example needs rework

### ISSUE THREAD

**Issue by MaximilianKindshofer** [babybuddy/babybuddy#141]
newer postgres versions need a password
also the docker settings file does not provide a password
there is no database password config mentioned in the readme

I may be doing this wrong so help is appreciated

**Comment by cdubz** [comment]
See #140 and related issues in those comments. If this is related to a recent updates, that explains why it’s happening for lots of people all of a sudden.

I’m not a Docker use myself, so appreciate any help in updating the example file and documentation.

**Comment by MaximilianKindshofer** [comment]
Ok I will prepare a pull request - that's when I can make some time for it. Having a little one doesn't always leave much space for coding ;)
