### ISSUE TITLE
Using 24H format for time

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#148]
Hi! I’m having the reverse problem: I would like to not use AM/PM but 24H format. I’m using the app in English.

My first thought was `DATETIME_INPUT_FORMATS`, but that is about the input format, not display format. I then thought of setting [DATE_FORMAT](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-DATE_FORMAT) but it seems that it will get overridden anyhow because `USE_L10N` is enabled? (that, and I would presumably need to set `DATETIME_FORMAT`, `TIME_FORMAT` and `SHORT_DATE_FORMAT`)?

Digging further, it appears that `USE_L10N` is conditioned by `LANGUAGE_CODE` ; however that is hardcoded to 'en' (presumably aliased somewhere by Django to `en-us`?) in `babybuddy/babybuddy/settings/base.py`  so I guess it would not be taken into account either?).

Am I missing something?

_Originally posted by @JeanFred in https://github.com/babybuddy/babybuddy/issues/93#issuecomment-654884934_

**Comment by cdubz** [comment]
Will test this when I get a chance. There is also [`babybuddy.formats`](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/formats/en/formats.py) for _input_ formats, which seems like it may also be relevant. In theory this should definitely be something Baby Buddy supports, but right now the setup may be totally reliant on L10n formatting. And with the frontend date picker stuff, this may need to be a feature rather than something that can be just customized in settings.

**Comment by JeanFred** [comment]
Thanks for splitting this into its own issue and having looked into it!

**Comment by cdubz** [comment]
I also prefer 24 hour time formats, so I am interested in supporting this (: It's a bit more complicated that Django settings can handle because of the locale support, but doable as a global app setting (per-user setting didn't have a clear path because of the way Django's locale-based time formats work).

I got this as far along as I had time for in #150. In some basic tests it appears to be functional, but documentation and _actual_ tests are still needed.
