### ISSUE TITLE
Allow to set/change the date/time of notes

### ISSUE THREAD

**Issue by JeanFred** [babybuddy/babybuddy#151]
The (start/end) time of all activities (Feeding, Sleep, Tummy Time, Diaper change, Weight, Temperature) can be set at creation and updated later. This is not the case of notes.

I often find myself backfilling notes − this is because 1/ for noteworthy events, filing them in the babybuddy is not always the priority and 2/ I run babybuddy on a rP on my local network, and is not accessible outside (where noteworthy events may happen).

I would suggest to allow to set the date/time of notes either at creation time or at update time (or both).

**Comment by cdubz** [comment]
Fair enough. There is a `DateTimeField` on the Note model, so adding this should be straightforward.
