### ISSUE TITLE
Unable to run `gulp migrate` locally as database path does not exist

### ISSUE THREAD

**Issue by phardy** [babybuddy/babybuddy#156]
#145 moved the default sqlite DB file to `data/db.sqlite3`, but the `data` directory does not exist in the repository. This means that attempting any sort of local development that requires the database (such as `gulp migrate`) fails trying to open the database file.

Steps to replicate: Clone a fresh copy of the repository, and follow the steps in `CONTRIBUTING.md`. :)

The traceback from a `gulp migrate` wasn't helpful, it just says "unable to open database file", and there's no mention in the docs about the database location. I had to do a little spelunking in the configuration classes to find that the location had changed.

I guess I'm expecting one of: a different location for `babybuddy.settings.development`, an empty data dir to be added to the repository, or some logic in `setup.py` to create it if it doesn't exist. But I don't know what the preferred option is, which is why I haven't just opened a PR, sorry.

**Comment by cdubz** [comment]
Oops -- nice catch. Thought I had set that folder up to be committed. Will fix shortly.
