### ISSUE TITLE
Start page showing "Welcome to nginx!"

### ISSUE THREAD

**Issue by dettmering** [babybuddy/babybuddy#157]
I need help with the manual installation. I'm no nginx expert. After following all the steps in the README, I'm not greeted with babybuddy, but with the nginx standard page. 

Here's the current configuration of nginx:

```
 upstream babybuddy {
     server unix:///var/run/uwsgi/app/babybuddy/socket;
 }

 server {
     listen 80;
     server_name babybuddy.example.com;

     location / {
         uwsgi_pass babybuddy;
         include uwsgi_params;
     }

     location /media {
         alias /var/www/babybuddy/data/media;
     }
 }
```

Can you please point me towards a solution? Thank you!

**Comment by cdubz** [comment]
Did you replace the `server_name babybuddy.example.com` directive with an actual reachable address? E.g. the server IP address (if you don't have an associated domain setup)?

**Comment by dettmering** [comment]
That worked, thanks a lot! What an easy fix!
