### ISSUE TITLE
Feature Request: track milk pumping

### ISSUE THREAD

**Issue by amandadebler** [babybuddy/babybuddy#159]
Being able to track milk pumping (time started/stopped, which breast(s), quantity, milk vs colostrum) using an interface similar to the Feeding activity would be great.

**Comment by rplankenhorn** [comment]
Love this idea!  I actually noticed my wife keeping track of her pumping stats in the iOS Notes app yesterday and thought it would be a cool feature in the Baby Buddy app as well.  Glad to see I am not alone.

> On second thought, maybe I should fork it into a second project, because the pumping times are going to collide with the existing activities.

Is this an issue?  I assumed that time overlaps only mattered within the same activity.  If we made this a completely separate activity, I think it would be work.  Or am I missing something?

**Comment by cdubz** [comment]
@rplankenhorn @amandadebler Yeah, that shouldn't be an issue. The time overlap stuff is only checked for Feeding entries. And for a "Pumping" model we wouldn't use the same validation scheme.

**Comment by amandadebler** [comment]
Temporary solution: create another Child, name it "Pumping Tracker", and use Feedings, since that tracks most of data I and probably other moms want: initiation time/date, duration, side, volume, and allows use of the Timer. I was using the Notes feature and had fallen into a standard format: side, start time, stop time, volume, pumping technology (pump name, flange type)

**Comment by cdubz** [comment]
Haha, Little Pumping Tracker saves the day.

**Comment by cdubz** [comment]
Closed by #409.
