### ISSUE TITLE
Integration with HA

### ISSUE THREAD

**Issue by Cpainy** [babybuddy/babybuddy#163]
Is it somehow possible to integrate this with Home assistant (home automation software)?
It would be very convenient to add the timers to (wireless) physiscal buttons next to the baby bed for example. Also voice integration would be possible and much much more.

I'm new to github and open source, so sorry if this a rediculous request :)

**Comment by BenjaminHae** [comment]
This is easily possible by using the API.
The OpenAPI schema is available at `/api/schema` of your instance.

The API is shown in your user profile.

I'm using a physical button for tracking diapers :)

**Comment by BenjaminHae** [comment]
I'm using the API in mir HA (iobroker) like that:
```
const http_baby = require('http');
function sendBabyBuddy(data: string){
    const key = "XXXX";
    const options = {
        hostname: 'localhost',
        port: 8000,
        path: `/api/changes/`,
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(data),
            'Authorization': `Token ${key}`
        },
    }
    var req = http_baby.request(options, (res) => {
        res.setEncoding('utf8');
        res.on('data', (chunk) => {
            console.log(chunk);
            return;
        });
        res.on('end', () => {
            return;
        });
    });
    req.write(data);
    req.end();
}
var trackDiaperChange = function(dp) {
    let color = "";
    if (dp.state.val === true) {
        color = "yellow";
    }
    let data = `{ "child": 1, "time": "${new Date().toISOString()}", "wet": true, "solid": ${dp.state.val}, "amount":1111, "color": "${color}"}`;
    sendBabyBuddy(data);
};
```
It's a bit more complex if you want to create timer, as you have to store the id of the timer when you create it.

**Comment by Cpainy** [comment]
Alright, great to hear!
Am I right to assume that that's code for iobroker. And HA has a plugin for iobroker?
Like I said, it's all pretty new to me and I have no programming experience. This might be to much out of my depth.
Is this feasable form me to learn? Can you point me in the right direction somewhere?
Thanks for your input

**Comment by BenjaminHae** [comment]
No I'm using a generic scripting component in iobroker to directly query the web api of babybuddy.
The code should also easily work with Node-RED.

**Comment by phardy** [comment]
I finally wrote up how I'm sending commands to baby buddy from HA. I've been using this setup a while, and it pre-dates easy access to timers through the BB API. That means times are tracked in Home Assistant only (if you start an activity via HA, it can only be ended/logged via HA). But it's been very reliable for me, and is hopefully a good example of home assistant configuration for baby buddy.

https://hardy.dropbear.id.au/projects/home-assistant/#interacting-with-baby-buddy

**Comment by Cpainy** [comment]
Thanks man!
