### ISSUE TITLE
Adding via Portainer

### ISSUE THREAD

**Issue by Cpainy** [babybuddy/babybuddy#165]
Is it possible to add babybuddy via portainer? I use this to manage all my containers.
I'm getting errors trying to deploy babybuddy with portainer. 
I can't change the docker-compose.example.yml with portainer I think?

Regards

**Comment by cdubz** [comment]
I’ve never heard of or used Portainer, but I can take a look at some point. Can you throw up some links for relevant documentation?

**Comment by Cpainy** [comment]
It's one of many docker container management systems. Lets you install containers via a GUI. The setup process is pretty similar between different system.
Much easier for noobs like me. This is the first container I had trouble setting up because I couldn't get it to run via Portainer.

Eventually I did manage to install Babybuddy via docker using te CLI for my ubuntu server but I can't figure out how to set up an IP and change the ports so babybuddy is accessible to other PC's on the network. 
After that Portainer detected the baby buddy app and database and in the logs I can see the the local 0.0.0.0:8000 ip but I can access it from another PC.

Documentation here: [https://www.portainer.io/documentation/](https://www.portainer.io/documentation/)

**Comment by ssilverr** [comment]
I tried deploying it as a stack using version: "2" as that's the docker-compose version that Portainer supports. Basically just copy the , but I get an error:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Do note, I'm noob, I just started my journey to selfhosted-dom.

**Comment by cdubz** [comment]
@ssilverr I'm not sure what it is exactly, but I believe something in the Docker Compose file is version 3+ only.

**Comment by ssilverr** [comment]
@cdubz bummer. I'm not sure how to get it up runnig with Portainer and Pi. @Cpainy did you manage to do it?

**Comment by Cpainy** [comment]
I did get it to work in Portainer, but only after installing it first via command line interface and docker compose as instructed in the documentation of babybuddy.
Portainer just picked it up automatically after that and I can use it to change settings now.

**Comment by phidauex** [comment]
For future users, below is an example of a Compose file that works in Portainer 2.0. It is just a slight modification from the SQLite compose file.

Volumes may need editing, and you would need to add a network if you want it to join a particular subnet.

Note the change to port 7000 - Portainer uses 8000 for its own web UI.

`version: 2
services:
  app:
    image: babybuddy/babybuddy
    container_name: "babybuddy"
    # See README.md#configuration for other environment configuration options.
    environment:
      - ALLOWED_HOSTS=localhost
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.base
      - SECRET_KEY=
      - TIME_ZONE=America/Denver
      - DEBUG=False # Turn to False in production
    volumes:
      - babybuddy/data:/app/data:rw
      - babybuddy/media:/app/media:rw
    command: bash -c 'python manage.py migrate --noinput && python manage.py createcachetable && gunicorn babybuddy.wsgi -b :8000 --log-level=info'
    ports:
      - "7000:8000"`

**Comment by cdubz** [comment]
Thanks, @phidauex. Do you think that the only _required_ change is the port? Or are the `container_name` and `volumes` changes also necessary (even if not the same changes for all use cases)? Just trying to figure out if there is a concise way to add this information to the README.

**Comment by phidauex** [comment]
Hmm, I believe the only required change would be to specify `Version: 2` and port 7000 (or anything other than 8000). Portainer's internal compose only supports v2 at the moment (though I find that most v3 compose scripts actually work fine if you change the version number since most people aren't using v3-specific features).

The addition of 'container_name' is a convenience and prevents the container from getting named a random string on deployment. It might be nice in both versions of the compose script, or could just be left out since it isn't necessary.

**Comment by cdubz** [comment]
Cool, thanks for sorting this out and following up. It looks like version 2+ support is coming to Portainer is the nearish term (portainer/portainer#3750) so I think just a note in the Docker section of the README and adding the `container_name` stuff to all example compose files would be good. Happy to accept a PR for this, otherwise I'll make the changes someday (:

**Comment by cdubz** [comment]
That said, looking back the history on the composer example file... it doesn't seem there is any feature from 2+ that is used. So maybe a downgrade there would also make sense...
