### ISSUE TITLE
SSL/TLS setup instructions

### ISSUE THREAD

**Issue by amandadebler** [babybuddy/babybuddy#166]
There should be instructions for setting this up using an SSL/TLS certificate, preferably using Let's Encrypt Certbot.

**Comment by cdubz** [comment]
I'm inclined to say that sort of thing would be out of scope for the regular project documentation. Instructions would vary based on deployment method pretty considerably. That said, I'm happy to consider any PRs that could provide -- perhaps just references off to general information about setting up certs for the various deployment methods?
