### ISSUE TITLE
Store birthday as timestamp with time zone

### ISSUE THREAD

**Issue by repomaa** [babybuddy/babybuddy#167]
The children index page shows the age of the children in days and hours so why not store the actual timestamp of the birth? Alternatively remove the hour part of the age.

**Comment by cdubz** [comment]
Ah yeah, I see what you are saying. We don’t actually record _time_ of birth but we show hours for ages below one week. Seems like it would be nice to add time granularity to the birth date info.

**Comment by cdubz** [comment]
I liked the idea of birth dates with time but it struck me that would be pretty API breaking. So I went the route of lowering the age precision to days. Thanks for the suggestion!
