### ISSUE TITLE
POEditor translations not reflected in codebase

### ISSUE THREAD

**Issue by daveliepmann** [babybuddy/babybuddy#168]
I deployed the app today, and have been using it in English and German. I noticed several incorrect translations and one missing translation. I fixed each in POEditor, but I'm concerned that some of the translation errors I see in the deployed app, such as "Letze Mahlzeit" (last feeding) instead of "Letzte Mahlzeit", are already fixed in POEditor, but *not* in GitHub. 

What is the expected process for getting translations from POEditor to `master`?

**Comment by cdubz** [comment]
Unfortunately updating those is a manual process. I _think_ is it possible for contributors to export translations from POEditor (appreciate if you could check/confirm that for me). If so, someone could then follow [CONTRIBUTING.md#translation](https://github.com/babybuddy/babybuddy/blob/master/CONTRIBUTING.md#translation) and make a PR.

That said, I'll get the latest translations in to `master` tonight or this weekend. Thanks for the poke!

**Comment by daveliepmann** [comment]
There's export functionality, but the diff between it and *django.po* was much greater than expected, so I made this issue rather than a PR. Thanks for the quick response! I'm definitely up for updating the docs as soon as I smooth out that process.

**Comment by cdubz** [comment]
I took a quick look at a diff from the POEditor export just now and I think the German translations in the app are just way behind. That may be why you see lots of changes. POEditor has an API, I wonder if this could be automated with GitHub Actions now...

**Comment by cdubz** [comment]
@daveliepmann everything should be even with POEditor now!
