### ISSUE TITLE
Use of datetime.date.fromisoformat breaks Python 3.6 compatability

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#170]
This is only used in [babybuddy/tests/tests_formats.py#L51](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/tests/tests_formats.py#L51) so refactoring it away hopefully won't be too difficult.

This was discovered when #158 was resolved.

**Comment by killua1zoldyck** [comment]
Hey, I can take this up.
