### ISSUE TITLE
Issue with times around daylight savings

### ISSUE THREAD

**Issue by JoeSc** [babybuddy/babybuddy#174]
I was just up feeding my child and got an error saying.
```
2020-11-01 01:06:00 couldn’t be interpreted in time zone America/Chicago; it may be ambiguous or it may not exist
```
The above error was generated from the '+' -> 'Diaper Change' page.

I assume this has to do with daylight savings. Since even I don't know if right now is the first or second time it's 1:06 am...

**Comment by cdubz** [comment]
Oaf. Sorry to hear that. I’ll see if I can reproduce and figure out what’s happening there. Damn DST...

**Comment by JoeSc** [comment]
Interestingly the "Time fill in popup" has two "01s" in it
![image](https://user-images.githubusercontent.com/367827/97805715-6e97bf00-1c1d-11eb-8690-5691b9386c18.png)
So it looks like "time fill in popup" understands the proper time,  might just be how you are interpreting the data that is submitted.

**Comment by cdubz** [comment]
The error occurred for you when you got to the form, correct? I.e. not when you _submitted_ the form? I’m guessing this has something to do with logic relating to prefilling the date field values when the form is loaded.

**Comment by BenjaminHae** [comment]
For me it came after submitting a timer started during the second hour between one and two.

**Comment by cdubz** [comment]
Thanks @BenjaminHae. I’ll check that out as well. Looks like this is reproducible even now by selecting a time between 1 and 2a —

<img width="375" alt="PNG image" src="https://user-images.githubusercontent.com/10456740/97806835-7a31b880-1c12-11eb-9ae7-476b673f1e47.png">

**Comment by Luzr** [comment]
Same issue for Chicago Timezone.
![2020-11-01_09-41-27](https://user-images.githubusercontent.com/9487415/97807460-8fb0dd80-1c26-11eb-8744-674d94f4dfa6.png)

**Comment by amandadebler** [comment]
I saw the same thing during Europe's time change a few weeks ago

**Comment by axilleas** [comment]
👋 any workarounds on this? Seems we cannot use a time between 2am-2:59am when time changes.

btw I'm getting this when submitting the form.

**Comment by cdubz** [comment]
No workarounds I can think of. I can’t believe this bug report is a year old. I hate to say “soon” but I will try to address this… soon 😬

**Comment by axilleas** [comment]
Yeah, I know :smile: No worries, the current workaround is to not file any reports during this hour :)

**Comment by kdrobnyh** [comment]
@cdubz, just an idea: why not to store everything as UTC in the database and convert from/to for every data that it stored/retrieved?

**Comment by cdubz** [comment]
@kdrobnyh date and time data in the database _is_ stored in UTC but we handle the timezone server side based on application or user settings. I think ideally we could move that handling to the _frontend_ but thats no small task.

**Comment by jcgoette** [comment]
Wife reported this issue this morning. I'm thinking this probably isn't an issue when DST begins, only even it ends?

**Comment by cdubz** [comment]
Oh maybe... I thought it was both but, again, I haven't taken the time to dig in to this one 😬

**Comment by cdubz** [comment]
Hoping this is no longer an issue in v2 now that a library is no longer being used for datetime entry :crossed_fingers:

**Comment by jschollenberger** [comment]
We encountered this issue this morning on v2.1.2.

From 1 until 2AM we couldn't log feeds:

`2023-11-05 01:21:53 couldn’t be interpreted in time zone America/New_York; it may be ambiguous or it may not exist`

**Comment by thib3113** [comment]
This bug is always here 
![image](https://github.com/user-attachments/assets/12cf8c2f-bd6e-41e2-9cd0-ae93e4d0ef8d)

**Comment by pVer297** [comment]
Happy new DST! I have to confirm, the issue is still present in 2.7.1

Eastern European Summer Time (UTC+3) -> Eastern European Time (UTC+2)

**Comment by programmerHaaks** [comment]
Merry DST! Confirming it here too. Going from CEST (UTC+2) to CET (UTC+1) on v2.7.1.
