### ISSUE TITLE
Track other baby care tasks (bathing, nail trimming...)

### ISSUE THREAD

**Issue by amandadebler** [babybuddy/babybuddy#176]
"When did we last give him a bath?"

"How soon after we fed him did we give him a bath when he spat up a bunch in the bath?"

**Comment by cdubz** [comment]
We have personally used the Notes feature for this sort of thing. There have been a couple of requests for additional tracking activities but I’m hesitant to clutter things up by adding many features that most users won’t use.

I’m thinking a potential approach would be to come up with some generic way for users to add and track any activity they want. Covering at least activity type, start (and optional end) time, and notes. But making that in a useful and configurable way would be a pretty complex task.

**Comment by cdubz** [comment]
Closing in favor of #217.
