### ISSUE TITLE
S3 Endpoint

### ISSUE THREAD

**Issue by Hyurt** [babybuddy/babybuddy#183]
We should be able to add some more settings, as S3_ENDPOINT to be able to use S3 like/compatible  as Minio for upload files elsewhere. 

I've been following this thread and I think I'll have a look this week or next week to have a look 
https://github.com/babybuddy/babybuddy/issues/180

**Comment by cdubz** [comment]
Do the existing [`AWS_S3` configuration options](https://github.com/babybuddy/babybuddy#aws_access_key_id) not give enough configuration here? Is there a specific configuration setting or group of settings from the [underlying library](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html) that you need for your use case?

**Comment by Hyurt** [comment]
My bad, didn't know Django Storage was already allowing embedding thoses variables. In that case, it seems that AWS_S3_ENDPOINT_URL should be fine.
Maybe I could make a PR to the doc and explicit it if you don't mind.

**Comment by cdubz** [comment]
Yeah I think that would make sense. Could you confirm that you can set that environment variable and have it work? If so it might also make sense to just remove the setting of those variables in [`settings.py:L207-211`](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/base.py#L207) and modify [`settings.py:L213`](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/base.py#L213) slightly to check for that environment variables directly. Then we could update the documentation to just reference the documentation of the underlying library.

**Comment by Hyurt** [comment]
Mmmh I think I need to dig a little bit more
AWS_S3_ENDPOINT_URL is set up, but got an error saying that AWS Access ID doesn't exists in records. 
Looks like it doesn't take my S3 endpoint, I don't see any trace of it in the traceback error

**Comment by cdubz** [comment]
Hm. The fact that it returns an error at all seems to suggest the endpoint setting works, right? Have you tried setting to something not at all right (e.g. “google.com” or something)? Does it give the same error or fail entirely?

**Comment by Hyurt** [comment]
Well, yes and no. This error show that I got S3 that answers, but not Minio as expected. Double checked keys, changed host to Google.com and got same error. Seems like it's ignoring the AWS_S3_ENDPOINT_URL variable

**Comment by cdubz** [comment]
Hmmmm. Ok. I wonder if it also needs to pass through the settings file. Seems odd. Did you try setting up the handling in the same way other S3 config is currently (ie in the settings file via the env variable)?

**Comment by Hyurt** [comment]
Tried through environment variable. I'll give a deeper shoot this afternoon

**Comment by Hyurt** [comment]
Okay, works with value harcoded in `babybuddy/settings/base.py` 
```
AWS_S3_ENDPOINT_URL =  "https://<minio-endpoint>"
```
Removing https://github.com/babybuddy/babybuddy/blob/35c825f223f061806c631c1147c50de9b822230f/babybuddy/settings/base.py#L209 and https://github.com/babybuddy/babybuddy/blob/35c825f223f061806c631c1147c50de9b822230f/babybuddy/settings/base.py#L211 does not affect my ability to see/upload medias as long `AWS_S3_ENDPOINT_URL` is in `base.py` 

```
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL') or None
```

Could be a fix, but I don't know why I need to explicit this variable and not the AWS access/secrets

**Comment by cdubz** [comment]
Perhaps because `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are somewhat standard environment variables used by AWS tools, while `AWS_S3_ENDPOINT_URL` is a specific setting of the django-storages package?

Anyway, I'm not sure if there is a need for any change to the base settings here. What do you think? The django-storages package has a _lot_ of AWS settings variables and I'm not really inclined to pack them all in there.

**Comment by Hyurt** [comment]
It is, huge misunderstanding from my side with `django-storages`.  I thought those variables were automatically checked with environment variables, but it's not and they mention that it must be within `settings.py`. Packages uses boto3  which checks AWS credentials (~/.aws/config, environment variables or IAM) and load them automatically.

I don't know if this should be changed in repo. 
Using docker image would be great to be able to overload it instead of mounting settings.py from host to container. Other values from django-storages could be too specific to require implementation. 
But the Minio usage could also be too specific, I could write quick guide for it or provide a new `DJANGO_SETTINGS_MODULE` ?

**Comment by cdubz** [comment]
Yeah, I think this is all pretty specific and doesn't need any changes to the repo. I welcome you to document it further here in case anyone comes searching for the information (and if you think it's necessary), but I'm going to go ahead and close this issue now.

Glad you were able to get it all sorted!
