### ISSUE TITLE
iFrame Support

### ISSUE THREAD

**Issue by mprajescu** [babybuddy/babybuddy#184]
Is there a way to enable the baby buddy docker image to allow it to be embedded with iframe on another site from it's own domain?

**Comment by cdubz** [comment]
Hmmm. Have you tried to do so? What doesn't work?

Potentially related -- some months ago I created a [Baby Buddy Sandstorm package](https://github.com/babybuddy/babybuddy-sandstorm) that I *think* has some related changes because Sandstorm uses iframes as well. Unfortunately I didn't document the changes there very well so I don't recall exactly what was needed.

**Comment by mprajescu** [comment]
The error that I have is "Refused to display 'https://DOMAIN_HIDDEN/login/?next=/' in a frame because it set 'X-Frame-Options' to 'deny'." How would I change the X-Frame-Options in the docker image?

**Comment by BenjaminHae** [comment]
You need to remove line 69 of `babybuddy/settings/base.py`:
```
'django.middleware.clickjacking.XFrameOptionsMiddleware',
```

**Comment by mprajescu** [comment]
I can confirm commenting out the line 69 fixed the issue and I am able to iframe the app. 
I did had to map /app to an external volume in order to edit the file, but it's all good now. 

@BenjaminHae , thank you.

**Comment by cdubz** [comment]
@mprajescu just one additional note -- the base settings file is committed so you may lose this change if you update the application. If you are using a non-committed settings file anywhere else along the way, you could alternatively add `MIDDLEWARE.remove('django.middleware.clickjacking.XFrameOptionsMiddleware')` to it and not have to worry about it again.

**Comment by thib5** [comment]
Hi, in the latest release the line 69 seams already commented. but the iframe still doesn't work. how can I make it work ( don't know if it change something but my app is host on Heroku
