### ISSUE TITLE
Unraid Docker Template

### ISSUE THREAD

**Issue by roweyourboat90** [babybuddy/babybuddy#185]
Please create or write guidance on docker install on the Unraid platform.  Others have tried and not been successful so far.

Link to Unraid forum:
https://forums.unraid.net/topic/92715-seeking-help-manually-installing-docker-babybuddy/
https://forums.unraid.net/topic/78227-make-unraid-compatible-docker-image/

**Comment by cdubz** [comment]
Those forum posts are be a bit dated w.r.t multistep build process, which BB does not use anymore.

See also this forum post for generalities about Docker Compose (which is the primary Docker install method supported by BB): https://forums.unraid.net/topic/91436-is-docker-compose-available-on-unraid/

The recommendation there seems to be to setup unraid specific templates of some sort. As I know nothing about them, I'd be happy to help someone using unraid as much as I can and get any relevant PRs merged.

**Comment by roweyourboat90** [comment]
I think it's mostly the ability to edit the config files. Those are
typically mapped to an "appdata" directory that can be managed outside of
the docker environment.

What is the directory location of the config file where the variables for
secret_key and such are set? Seems like at least two of those are required
to even start the container. I tried mapping /config to my appdata, but
didn't seem to help either.

Here is some of the template help I've seen in the past, but am a total
newb and use the UI functions unless absolutely necessary.
https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

It's easy to just use a docker hub without a specific unraid template made,
but finding the right variables or things to map is all it really takes as
far as I've seen.

**Comment by cdubz** [comment]
Settings files live in [`babybuddy/settings`](https://github.com/babybuddy/babybuddy/tree/master/babybuddy/settings), which in Docker may translate to `/app/babybuddy/settings`, I think?

Normally, the `DJANGO_SETTINGS_MODULE` environment variable is used to specify which settings file to use and all the provided files extend from [`base.py`](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/base.py) so if `DJANGO_SETTINGS_MODULE` is not defined you'd need to work with `base.py` directly to set those required values. Normally these settings are controlled through the environment variables documented in the [Configuration section of the README](https://github.com/babybuddy/babybuddy#configuration).

Is there no way to pass environment variables to your Docker instance within unraid? I did a search on the unraid forums and saw a couple of posts saying that you should apparently be able to pass environment variables in, but I couldn't find any clear documentation on it.

**Comment by roweyourboat90** [comment]
I tried the variables directly as well, but same result.  I wonder if its something to do with multiple containers since the unraid docker doesn't allow that.  Does the example docker-compose end up generating 2 containers?

**Comment by cdubz** [comment]
Yes, it does -- one for the app and one for the db. BB used to have a multi-stage _build_ process that was problematic for some services, but the multiple containers have never been an issue.

That said, it's my understanding that unraid doesn't use Docker Compose anyway? The Dockerfile itself is just the app and should work with sqlite as a database backend, I think? But maybe that is not the case... I have only ever used Docker Compose and I'm not really familiar with Docker generally.

What happens right now when you try to get it going in unraid? Do you get any sort of error output or other result tha you can share?

**Comment by ministryofsillywalks** [comment]
Also tried settings this up in Unraid and it doesn't even start up.
I don't even get any logs from docker so something is very wrong.
I added the variables directly in the Unraid UI. 
![image](https://user-images.githubusercontent.com/10544895/106241696-c0dd8180-6206-11eb-8071-3bd22e85bea7.png)

**Comment by theiam79** [comment]
@ministryofsillywalks fwiw, I was able to get this to boot in unraid with the following settings.

![babybuddy template](https://user-images.githubusercontent.com/40555254/110896906-21f67b80-82c2-11eb-8219-423f29b8ceba.png)

I used an existing template for postgreSQL 11.  Other than matching the existing docker compose file, I had to add the DB_HOST variable to override the default setting. I might look into creating a template this weekend, time permitting (baby and all that, hence the app lol)

**Comment by ministryofsillywalks** [comment]
@theiam79 tried using your settings and still couldn't get it working.
Guess I'll be patient and wait for the template ;)

**Comment by theiam79** [comment]
@ministryofsillywalks  Finally looking into the process of getting a template published now. In the meantime, do you know where its failing (ie is the docker run command failing, or is something happening with baby buddy that you might be able to see in the logs)?

**Comment by theiam79** [comment]
Oh, realize there's a setting you can't see in my screenshot. If you turn on the advanced mode, you should see an option for `Post Arguments`. You need to set that to `bash -c 'sleep 5 && python manage.py migrate --noinput && python manage.py createcachetable && gunicorn babybuddy.wsgi -b :8000 --log-level=info'`

**Comment by roweyourboat90** [comment]
I got it working!  There is a template in the Community Apps that I started with, and attached are how I configured it.  A couple things I had to wrap my mind around (I'm not a software person, so it's likely obvious to others):
- DB_PASSWORD variable needs to be your Postgres container admin password.  I assumed it was the db user password I created, but eventually realized that didn't make sense since I didn't set a db username.  That might work as well, but I didn't go that far.
- ALLOWED_HOSTS needs to include the babybuddy container IP otherwise Django goes bananas.  If you reverse proxy (I am using [Nginx Proxy Manager](https://github.com/jc21/nginx-proxy-manager)) you also need to add your domain.
- I don't know if the "data" and "media" directories need to be mapped because they remain empty as far as I can tell.

![babybuddy_docker](https://user-images.githubusercontent.com/60307722/112343854-84bc1f80-8c91-11eb-8ca2-f13776c3d51d.png)

![bb_postgres_docker](https://user-images.githubusercontent.com/60307722/112343874-8be32d80-8c91-11eb-9c74-12c51420113a.png)

[Unraid XML template here](https://pastebin.com/aWXAtmEW)

**Comment by cdubz** [comment]
Just FYI the `data` directory only exists as a place for sqlite to initialize itself so indeed is not relevant here. The `media` directory is where a child photo would be stored if uploaded.

**Comment by ministryofsillywalks** [comment]
> 
> [Unraid XML template here](https://pastebin.com/aWXAtmEW)

Thanks! I used that template and modified it a bit adding "DB_USER" and "DB_NAME" as my postgres instance has more than one database.
Worked just fine!

**Comment by cdubz** [comment]
It's cool that y'all were able to work this out. Could someone work on some concise instructions on how to get this working that we could add to the README? I see that the Unraid site also has an "Apps" section but it's unclear to me how to add apps there. Is it just a manual request?

**Comment by theiam79** [comment]
> It's cool that y'all were able to work this out. Could someone work on some concise instructions on how to get this working that we could add to the README? I see that the Unraid site also has an "Apps" section but it's unclear to me how to add apps there. Is it just a manual request?

It's a multi step process that I had started but ultimately didn't continue down. I'll try to send you the process tonight, as well as the xml template it uses.

**Comment by theiam79** [comment]
@cdubz 

Here is the link to submit a template for community apps in Unraid

https://forums.unraid.net/topic/57181-docker-faq/#comment-566084


[babybuddy_template.txt](https://github.com/babybuddy/babybuddy/files/6253974/babybuddy_template.txt)

 Heres the generated XML. Even if you don't have unraid I imagine you'll undeddrstand this and be able to make any tweaks if needed.
