### ISSUE TITLE
Feature Request:  Track baby height

### ISSUE THREAD

**Issue by Floyz** [babybuddy/babybuddy#191]
Hello again !
I haven't seen a place to track baby height, 
This would be a good feature If this could be added :)
Regards

**Comment by cdubz** [comment]
This feature has been requested in the past (see #105) -- see my response there (happy to consider this, but not something I am looking to implement):

> Weight tracking is supported because it relates pretty directly to baby's health in the early days and weeks, but I'm not sure that height has a similarly strong correlation to health. That said, I am happy to be corrected on that and/or hear from other users who may be interested in this feature.

**Comment by Floyz** [comment]
I think you're right about that weight is a more obvious baby's health data than height.
But i'm pretty sure it's as important as Tummy time for example.
All doctors visit tracks weight and lenghts on charts to track growth.

During the first year of life, an infant's weight and length are charted at each doctor's visit to make sure that growth is proceeding at a steady rate. Percentiles are a way of comparing infants of the same age. For an infant at the 10th percentile for weight, 10% of infants weigh less and 90% weigh more. For an infant at the 90th percentile, 90% of infants weigh less and 10% weigh more. For an infant at the 50th percentile, 50% of infants weigh less and 50% weigh more. Of more significance than the actual percentile is any significant change in percentile between doctor's visits. (Adapted from WHO Child Growth Standards

**Comment by cdubz** [comment]
Fair enough. I'll leave this issue open for a bit in case anyone wants to put together a PR.

**Comment by harrisonhjones** [comment]
I casually follow this project (I just think it's neat) and saw this request today. As someone who knows how to code but is not familiar with this project at all how much time do you think implementing this feature would take? Could one do it in an afternoon? I poked around the demo site and it looks like a height tracker would be implemented similar to how the weight feature works. So it would need an interface to add a height entry, like http://demo.baby-buddy.net/weight/add/, a graph to show height over time, like http://demo.baby-buddy.net/children/sean-brooks/reports/weight/weight/, and the underlying API addition. Anything else?

**Comment by cdubz** [comment]
👋 @harrisonhjones, thanks for your interest. I actually built Baby Buddy while learning Python. The only previous experience I had was [LPTHW](https://learncodethehardway.org/python/) (back when it was free) and the [Writing your first Django app series](https://docs.djangoproject.com/en/3.1/intro/tutorial01/). You pretty much have the gist of it, but I would recommend at least the Django series first to get familiar with the tools and general structure of a Django app. After that and some general exploring of BB's structure an afternoon would be a fair estimate. I'll also be happy to provide guidance once you get a PR moving.

Tangent, I recently learn about the [ARCHITECTURE.md concept](https://news.ycombinator.com/item?id=26048784) and want to do it for BB someday... it would help me remember things too, hah.

**Comment by mvanrompuy** [comment]
I agree that height tracking would be a valuable health tracking feature. The WHO hosts a number of [growth standards](https://www.who.int/tools/child-growth-standards/standards), which they see as valuable metrics. Height is indeed one of them. 

In my country they track the following metrics throughout the childs development (using a combination of the WHO standards and country specific ones):
- weight
- height
- BMI
- head circumference growth

All of these are regularly checked during the first 2,5 years and logged in a paper booklet for the parents. It would be nice if I could also enter this data into babybuddy to track all health parameters in the same location.

I would be willing to spend some time on adding such a feature, should nobody else take this up.
