### ISSUE TITLE
Translations are inconsistent on Docker Deployment of v 1.5

### ISSUE THREAD

**Issue by cephos** [babybuddy/babybuddy#197]
When the language is changed in the profile, only the submit-Button and "None" in the dashboard are translated. All menus and labels remain in English. This happens no matter what Language apart from English I set and with different Users. 

Strangely the Setting in the demo-Instance with apparantly the same Version deployed, works as expected and translates all the Strings.

I deployed Version 1.5 on Docker (using SQLight).  Any idea/hint how to debug this behaviour?

**Comment by cdubz** [comment]
Hm, this reminded me of someone else reporting this issue back in May on Gitter -- https://gitter.im/babybuddy/Lobby?at=5eb1419414b48f0698ae2366

Unfortunately there was no real resolution there. Can you tell me anything else about your setup? E.g. the host machine OS, relevant Docker versions, etc.? I was able to reproduce this back then but others have apparently been using the Docker version successfully.

The demo runs in Heroku and does not use the Docker image so it does seem to suggest something about the Docker setup specifically...

**Comment by cephos** [comment]
I made another deployment to my local docker host and tried with the Postgres-Version. It shows the same problem. I verified that in the postgres-db the right language-code really is set, so that's not the source of the problem. 

Both hosts I have this problem are setup with english locales, perhaps that's the unusual setting I have, other german users don't use and you probably have too. Would fit the correct behaviour on heroku as docker uses more components/settings of the host system than other 'virtualisation'-Platforms.

The image runs on the following host-system:
Debian GNU/Linux 10 (buster)
4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
Docker version 20.10.1, build 831ebea

I was also able to reproduce it on my local ubuntu machine:
Ubuntu 20.04.1 LTS, 
Kernel  5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Docker version 20.10.3, build 48d30b5

I noticed there is no .po and no .mo file in the container (they arent copied in the dockerfile) so i found the following manual workaround. After these steps language-changes in settings work for german/english and back (I suppose other languages would too if I wgeted them). 

> mkdir /app/locale/de/LC_MESSAGES
> cd /app/locale/de/LC_MESSAGES
> wget https://github.com/babybuddy/babybuddy/raw/master/locale/de/LC_MESSAGES/django.po
> apt update
> apt install gettext
> ./manage.py compilemessages
> restart container

I don't know anything about how translations work in django/python so I'm a bit lost. As consequence I'll stick with this 'golden' image for the beginning. Would be nice if someone more skilled in django/python translations would be able to fix the dockerfile so it works for everyone. I'm glad to help testing on the two machines it failed.

**Comment by cdubz** [comment]
Oh! Well duh... yeah I think this is an easy fix of just adding a `ADD locale /app/locale` line to [`Dockerfile`](https://github.com/babybuddy/babybuddy/blob/master/Dockerfile). Thanks for sorting it out! I'll make that change soon or you can open a PR if you'd like credit for the fix.

**Comment by cdubz** [comment]
@cephos give the `matser` build a try from Docker when you get a chance. This should be resolved now. I'll test it later as well.
