### ISSUE TITLE
Sleep Pattern Error

### ISSUE THREAD

**Issue by clumsyCoder00** [babybuddy/babybuddy#198]
After updating to 1.5.0 I started to encounter an error when navigating to the sleep pattern section of the site.

`TypeError at /children/(redacted)/reports/sleep/pattern/`
`object of type 'float' has no len()`

Traceback info:
`Environment:

Request Method: GET
Request URL: http://baby.(redacted).com/children/(redacted)/reports/sleep/pattern/

Django Version: 3.1.7
Python Version: 3.8.8
Installed Applications:
['api',
 'babybuddy',
 'core',
 'dashboard',
 'reports',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'widget_tweaks',
 'easy_thumbnails',
 'storages',
 'import_export',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'babybuddy.middleware.RollingSessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babybuddy.middleware.UserTimezoneMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/app/reports/views.py", line 131, in get_context_data
    context['html'], context['js'] = graphs.sleep_pattern(instances)
  File "/app/reports/graphs/sleep_pattern.py", line 100, in sleep_pattern
    max_i = max(len(date_times), max_i)

Exception Type: TypeError at /children/(redacted)/reports/sleep/pattern/
Exception Value: object of type 'float' has no len()`

This may be related to [issue #116 ](https://github.com/babybuddy/babybuddy/issues/116)
Reverting back to version 1.4.1 resolves the issue. Please let me know if there is any further information I can provide to be of assistance.
Regards.

**Comment by cdubz** [comment]
Yeah could be something from #116. I’ll take a look soon.

**Comment by cdubz** [comment]
Hi @clumsyCoder00 -- this should now be fixed (on `master`) by e6838a0c0f64ee7e6a7d9a4b9eb05c07a2b5d59c. Will also get it in a release "soon" (:
