### ISSUE TITLE
Timer for medicine

### ISSUE THREAD

**Issue by luka-munjos** [babybuddy/babybuddy#200]
It would be nice if you could have timers for medication ( this especially nice if they are teething) then you are able to keep track of it easier this especially nice when you have others babysit for you etc

**Comment by cdubz** [comment]
See #153 and #66 for similar feature requests. This isn't something I've had time to prioritize as it would be a pretty big feature. I've got it tagged for a potential future v2 release of Baby Buddy but no timeline on that.

**Comment by cdubz** [comment]
Closing in favor of #66.
