### ISSUE TITLE
Add LDAP as authentication backend

### ISSUE THREAD

**Issue by nitnelave** [babybuddy/babybuddy#202]
Hello,

It would be great to have a possibility to re-use an existing LDAP backend for users. It shouldn't be too hard with django, hopefully.

Thanks,

**Comment by BenjaminHae** [comment]
How about OpenID Connect?

**Comment by cdubz** [comment]
There is a [django-auth-ldap/django-auth-ldap](https://github.com/django-auth-ldap/django-auth-ldap) plugin that would support this -- it looks well maintained but requires quite a bit of config. I don't have an LDAP server to test with but I'd be happy to consider a PR for this. Theoretically one could also just install the package on an existing BabyBuddy deployment and then configure it per their documentation.

**Comment by nitnelave** [comment]
I could have a look, but I'm not familiar with Django. From the plugin's page, I need to add some configuration (in python), but I'm not sure where to add it. Babybuddy doesn't seem to have a settings.py or equivalent.

**Comment by nitnelave** [comment]
Ah, I found it in babybuddy/settings/base.py. I'll have a look, and might also add authentication via REMOTE_USER header as well.

**Comment by cdubz** [comment]
We have support for `REMOTE_USER` now via [`REVERSE_PROXY_AUTH`](https://docs.baby-buddy.net/configuration/security/#reverse_proxy_auth) so I think this use case is covered well enough.
