### ISSUE TITLE
Docker-compose settings being ignored

### ISSUE THREAD

**Issue by Poewa** [babybuddy/babybuddy#204]
Im having issues with the docker image. No matter what port i choose the server always listens on port 8000.
This applies to other settings as well.

Im pretty new to docker so the fault is propoply in my end.

**Comment by cdubz** [comment]
@Poewa can you post your Compose config?

**Comment by Poewa** [comment]
H cdubz, 

Here it is as requsted.
https://gist.github.com/Poewa/3f92ce81ba338e0b986a769e695f1f9c

**Comment by cdubz** [comment]
The [`app.ports` config](https://gist.github.com/Poewa/3f92ce81ba338e0b986a769e695f1f9c#file-docker-compose-yml-L31) is where you tell Docker how to expose a port from the container. In your example you have it set to expose port 8001 as 8001 but the app is on port 8000. So if you want it to use 8001 you should set `8000:8001` or e.g. `8000:80` if you want to use port 80.

**Comment by Poewa** [comment]
Thanks for getting back to me. Changeing the settings to your example still produces the same result. 
example: 
8000:80 - Still makes the host listen on port 8000. 
netstat -an | grep '80' shows no listening ports. 
netstat -an | grep '8000' shows the host is listening on port 8000. 

Again this is porbably me doing something wrong, i might be better off learning a bit of docker before continueing. 👍

**Comment by cdubz** [comment]
Let me know what you find. I'm also not particularly strong with Docker. It sounds like you've got things setup correctly though :shrug:

**Comment by Poewa** [comment]
Hi again, 

I got everything working. As exspected the fault was me. 

Regarding the ports, i was reading them backwards. I thouht 80:8000 would mean that port was used on the docker container.
Regarding the database password. I had to recreate the datavolume that the db server used, to be able to change the password. 

docker volume rm idhere
