### ISSUE TITLE
Child slug may become empty

### ISSUE THREAD

**Issue by cben** [babybuddy/babybuddy#205]
Currently it is easy for a child with non-ascii name to get very short or empty slug, as the actual characters get filtered out:
`'Мааян' 'Паскин-Чернявский'` => slug `'-'` :laughing: 
`'Мааян' 'Паскин'` => slug `''` :boom: 

In first case, it works but is silly and it's easy to get slug collisions.

Once any child has an empty slug, the app is "semi-bricked": many pages (like children list) break with NoReverseMatch errors:
> Reverse for 'child' with arguments '('',)' not found. 1 pattern(s) tried: ['children/(?P<slug>[-a-zA-Z0-9_]+)/$']

and you can't edit or even delete this child as she has no working URL...

- How to confirm this situation: visit `/api/children/` and look for empty slug.
- How to **un-brick** if you have admin account: visit `/admin/core/child/`, edit that child's name to include English letters.  The slug is always re-computed on save.

----

Proposed directions (sending PR for first 2 in a moment):

- [x] at least prevent setting such names
- [x] allow unicode chars in slugs
- [ ] A migration to fix at least empty slugs in existing installs?
- [ ] A migration to re-compute all slugs?  
  Not sure if a good idea: If they worked before, users may have already bookmarked per-child URLs that will now break.  New URLs will make more sense with non-ascii letters retained, yes, but who cares.  If people care, they can edit child name (even if no changes) and save to force re-computation.
- [ ] Let admin view show and/or manually edit slugs?
  - Manual editing is IMHO not worth it :-1:.  Raises question whether future `save()` by regular editing should preserve existing slug.  Currently `save()` always re-computes it from name, which would lose admin-set name.
  - Already shown in list, but not in edit form.  If not editable, showing read-only in edit form would be confusing as it wouldn't reflect that it's going to be re-computed; so showing only in list after save is perfect.

**Comment by cdubz** [comment]
I don't think we need to put much effort in to a migration path here. Folks who hit this bug likely would have already either reached out for assistance or abandoned the app. I also don't think we need any level of admin edit for slugs.

I will leave this open for tests, though. I'd like to eventually add one to prove that the change in #206 was effective at supporting unicode slugs.

**Comment by cben** [comment]
Just now got the dev env working.  Here is a start:
```diff
diff --git babybuddy/management/commands/fake.py babybuddy/management/commands/fake.py
index 5dac448..3173445 100644
--- babybuddy/management/commands/fake.py
+++ babybuddy/management/commands/fake.py
@@ -17,7 +17,7 @@ class Command(BaseCommand):
 
     def __init__(self, *args, **kwargs):
         super(Command, self).__init__(*args, **kwargs)
-        self.faker = Factory.create()
+        self.faker = Factory.create(locale='ru_RU')
         self.child = None
         self.weight = None
         self.time = None
```
This generates names like Зосима Белов, Авдей Сорокина...
Can use another locale of course; I picked Russian as cyrillic script feels "close enough" to latin letters to be semi-pronouncable, and distinguishable to English speakers, yet has 0 overlap with latin letters so triggers this bug.

- When first run, this gave me:
  ```
  test_fake (babybuddy.tests.tests_commands.CommandsTestCase) failed:

      IntegrityError('UNIQUE constraint failed: core_child.slug')

  Unfortunately, tracebacks cannot be pickled, making it impossible for the
  parallel test runner to handle this exception cleanly.

  In order to see the traceback, you should install tblib:

      python -m pip install tblib
  ...
  
  TypeError: cannot pickle 'traceback' object
  ...
  .
  ----------------------------------------------------------------------
  
  Ran 1 test in 0.008s

  OK
  Destroying test database for alias 'default'...
  [22:20:48] Finished 'test' after 13 s
  Done in 13.39s.
  ```
  Pipfile already lists tblib a dev dependency.  Turns out I followed CONTRIBUTING.md instruction to run `pipenv install --three`, I think that should be changed to `pipenv install --three --dev`.

With `--dev` dependencies installed, before #206, this is failing/crashing multiple tests.  Ran 174; FAILED (failures=2, errors=11).

After #206, it still fails a couple.
- [ ] `test_dashboard_views` should be adjusted to expect %-encoded URL;
- [ ] not sure yet why `test_user_settings_language` fails?

- P.S. It initially confused me that tests crash/fail, yet the final thing printed from `gulp test` is "OK" and it exits with status 0.  I ignored the traceback assuming it's some kind of "expected exception" test...  Totally minor, but if it's easy to change might save future contributors some time.

**Comment by cdubz** [comment]
@cben thanks for making an effort at this. Baby Buddy's dev environment is a bit dated at this point and I do have #203 also referencing the `test_user_settings_language` fail. I know this used to work correctly so either some other older commit broke it or something changed with Gulp itself. You can safely ignore _that_ fail.

Anyway, I think this is a good idea generally (running all tests or a subset of tests with a cyrillic script) and we should pursue it. Ideally we would run once with the default locale and then re-run with `ru_RU`, if possible.

**Comment by cdubz** [comment]
Minor update -- I have fixed the tests to actually fail when they fail :tada:

Now I need to figure out why that language change test is failing...
