### ISSUE TITLE
iOS Shortcut: "Authentication credentials were not provided"

### ISSUE THREAD

**Issue by fosspill** [babybuddy/babybuddy#222]
I'm unsure if this is a bug, or a simple configuration issue but I've been unable to find the cause and solution on my own.

Running babybuddy 1.6, I believe.

Trying to get api calls to work from iOS shortcuts to use with siri (ie: Hey Siri, Start a baby timer) but the api calls are rejected with "Authentication credentials were not provided".

This is from curl:
```
$ curl -X GET https://XXXXXXX/api/children/ -H 'Authorization: Token ee6152XXXXXXXXXXXXXXXXXXXX'
{"count":1,"next":null,"previous":null,"results":[{"id":3,"first_name":"XXXXX","last_name":"XXXXX","birth_date":"2021-04-25","slug":"XXXXX","picture":"XXXXX"}]}
```
So, that works fine.

But with the exact same settings for Shortcuts I'm getting the error mentioned.

I found a stackoverflow question that seems very related, but sadly it's a bit above my head:
https://stackoverflow.com/questions/57157568/calls-to-api-always-return-authentication-credentials-were-not-provided-when-a

I'd be happy to provide any extra information, logs or testing!

**Comment by fosspill** [comment]
It is always very helpful to post issues such as these. It forces you to go through your configuration to ensure the issue is documented well enough.

If you use HTTP you'll get the error "Authentication credentials were not provided". Seems I missed the S key while typing the url.

**Comment by cdubz** [comment]
Glad you figured that out. I didn’t know one could do that with iOS shortcuts — neat!

**Comment by zakhenry** [comment]
I hit the same error with iOS shortcuts, the issue for me was that I forgot the trailing slash in the endpoint I was trying to use. Hope it helps someone else!
