### ISSUE TITLE
Disable autocomplete for date and time fields

### ISSUE THREAD

**Issue by svenvdmeer** [babybuddy/babybuddy#224]
![autocomplete](https://user-images.githubusercontent.com/8640505/120665514-229b4a00-c48c-11eb-8a9d-a16429030823.PNG)
When I want to a date and time I get the tool that helps me select the date and time but on top of that chrome shows the autocomplete field which shows dates and times I've already added which is not useful at all.

This is easily fixed by adding autocomplete="off" to the form. Autocomplete could be useful for the notes section of the form but not really necessary.

**Comment by cdubz** [comment]
Thanks for the information. Happy to take a PR for this -- otherwise I'll be working through some Baby Buddy backlog soon and can tackle.

There are probably also other areas where we could take better advantage of more fine-tuned autocomplete settings on fields.

**Comment by cdubz** [comment]
Actually @svenvdmeer could you tell me more about how to reproduce this? E.g. what version of Baby Buddy and what browser/device/OS you are using? I forgot about this but fields using the datetime picker are configured to be read only and should not be doing any sort of autofill. E.g. here is how this looks for me --

![image](https://user-images.githubusercontent.com/10456740/121121657-d8400300-c7d4-11eb-913b-be55b29a37e2.png)

**Comment by ntrecina** [comment]
@cdubz I'm able to duplicate this issue on the latest master. I first noticed it when upgrading to `v1.5.1` and I ended up rolling back to `v1.5.0`. I've duplicated it in Chrome, Edge, and Firefox all on MacOS. I dug into it a bit and it seems like it's an issue with the date picker component that's causing the readonly attribute to be removed.

**Comment by svenvdmeer** [comment]
I have v1.6.0 installed
[image: image.png]
In a docker container on a Synology Nas.

Im accessing baby buddy with chrome on windows and Android (oneplus 7 pro).
Having this issue on both and also on my wifes android phone (oneplus 6).

At first when I add a feeding, the start time field is empty, the end time
is pre-filled:
[image: image.png]
When I click on the start time field the date/time picker shows up but also
the autofill suggestions:
[image: image.png]

If I press the 'go to today' button, then click somewhere else and then
click the start time field, only the date/time picker shows.

[image: image.png]


Op di 8 jun. 2021 06:11 schreef Christopher Charbonneau Wells <
***@***.***>:

**Comment by JeanFred** [comment]
I have been struggling with this as well (on Firefox for Android and Chrome for Android)

For me it started after I upgraded babybuddy (can’t remember which hashes though) *and* I switched to 24h format (#148). I see that @svenvdmeer also uses 24h format so maybe that’s the reason.

**Comment by cdubz** [comment]
Ok -- I can reproduce this as well now in Firefox Nightly on Ubuntu 20.04. Seems to be inconsistent between systems... I'll try to look at this soon.

**Comment by cdubz** [comment]
And not inconsistent between systems -- I think I just had trouble reproducing because of browser caches 🤦

**Comment by cdubz** [comment]
I have pushed a2da7e32f94bb4b34f547cf9abc53db8003f4455 to disable autocomplete on the datetime picker fields. However, the actual issue is that the `readonly` property on those fields is being stripped when the datetime picker initializes. I haven't been able to figure out if this is an issue with jQuery, Bootstrap, or Tempus Dominus updates as reverting to previous versions of those libraries still doesn't resolve the issue. I'm not familiar enough with JS debugging in browser to figure out where exactly the property gets removed. I have confirmed that Django is not doing anything different here -- the rendered page source *does* have the `readonly` flag. It only gets removed when the datetime picker is initialized. Any help sorting this would be appreciated!

**Comment by ntrecina** [comment]
@cdubz I looked into this a bit more and I think I narrowed it down to the version change with Tempus Dominus. I reverted the versions back to the previous versions and tried it out locally and the readonly issues appear to be fixed. These are the versions I set in `package.json`:
```
"tempusdominus-bootstrap-4": "5.1.2",
"tempusdominus-core": "5.0.3"
```

**Comment by cdubz** [comment]
Thanks @ntrecina! I thought I tested that but maybe I missed it...

I wish I could find a replacement for Tempus Dominus. It seems such a mess but nothing has quite the same level of features that are really useful for this app. Sigh...

**Comment by ntrecina** [comment]
@cdubz No problem! Let me know if you're ok with reverting to that version I can get a PR up with the change.

**Comment by cdubz** [comment]
@ntrecina yep, absolutely. Would appreciate a PR.
