### ISSUE TITLE
Mobile UI Tweaks

### ISSUE THREAD

**Issue by lutzky** [babybuddy/babybuddy#229]
Looking to use babybuddy instead of our current tracking app, I noticed a few things that I *think* are low-hanging fruit for UI cleanup, pertaining mostly to phone usability. (I'm making it a checklist here in hopes of it being a [newfangled task-list thing](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists#about-issue-task-lists); ideally the owner would turn their favorite suggestions into issues of their own)

- Improvements to timeline view
  - [x] #244
  - [x] #270
  - [x] #271
  - [x] #243 
  - [x] #240
  - [x] #247
  - [x] #272
  - [x] #246 
- [x] #239 
- [x] #251 
- Less vertical scrolling please
  - [x] #213
  - [x] #230
  - [x] #231
- No horizontal scrolling please
  - These are things that can be done to reduce horizontal scrolling in activity log pages.
  - [x] #235
  - [x] #236
  - [x] #232
  - [x] #237
  - [x] #233
- Less clicking please
  - [x] ~~Unified event log~~ this is the timeline view
  - [x] #234

**Comment by BenjaminHae** [comment]
>   * [ ]  Dashboard: Hide any boxes that just say "None"
>     
>     * Or at least move them to the bottom
This was already implemented as part of #213, #215 additionally adds an option to hide old data.

**Comment by cdubz** [comment]
👋 @lutzky. Thanks for these recommendation. UI/UX has never been my thing so I'm always happy to get ideas like this. I have converted a few that are clear enough to issues and have some questions about others:

> Dashboard: Change "Last thing" timeformat from "duration ago" to "HH:MM (duration ago)" 

I'm not totally sold on this. I've always liked the current time format as being very clear and easy to parse. I.e. there is no need to understand or learn that "02:45" translates to "2 hours, 45 minutes" because it is stated literally. I also wonder about the L10n implications of this change...

> Move Color and Amount columns to far right

Could you mock this up one up? I'm unsure what you're thinking here.

> Allow shorter timestamp formats

Where do you see this as a problem? I think the default used in e.g. lists is sufficiently short but maybe that's only because the current month names I'm looking at as example are short (July and June) (:

> Unified event log 

Not sure I follow this one. The child page itself has a "timeline" of sorts but it's probably not the best format. Is that the kind of thing you are thinking? It's also not really easily discovered. The dashboard is king.

**Comment by lutzky** [comment]
Happy to help, thanks for reading!

> > Dashboard: Change "Last thing" timeformat from "duration ago" to "HH:MM (duration ago)" 
> 
> I'm not totally sold on this. I've always liked the current time format as being very clear and easy to parse. I.e. there is no need to understand or learn that "02:45" translates to "2 hours, 45 minutes" because it is stated literally. I also wonder about the L10n implications of this change...

Oh, that's not quite what I meant; see the mockup picture I attached in the first post. That being said, the opposite format of "2 hours, 45 minutes (11:23pm)" would also work fine. 

> > Move Color and Amount columns to far right
> 
> Could you mock this up one up? I'm unsure what you're thinking here.

The current column order in the Changes view is "child, wet, solid, color, amount, time, actions". I propose "time, child, wet, solid, color, amount, actions". The last few columns require horizontal scrolling to view on a phone, which is why I prefer this order.

> > Allow shorter timestamp formats
> 
> Where do you see this as a problem? I think the default used in e.g. lists is sufficiently short but maybe that's only because the current month names I'm looking at as example are short (July and June) (:

On mobile, all of the "activities" views currently require horizontal scrolling, and the date field is split to 5 lines, e.g.:

```
June
26
2021,
12:01
p.m.
```

This makes it difficult to scan through the list, especially as everything but the most important line-specific information (just 12:01 in this case) is repeated, burying the important-to-scan info.

> 
> > Unified event log 
> 
> Not sure I follow this one. The child page itself has a "timeline" of sorts but it's probably not the best format. Is that the kind of thing you are thinking? It's also not really easily discovered. The dashboard is king.

I mean a single page (dashboard or otherwise) showing something like this:

- 12:01 feed 130ml formula
- 12:10 change 💩
- 14:30 feed 110ml formula
- 14:35 change 💦

e.g. the last 10 entries or so.

Apologies for terseness, sending this from mobile. Let me know if I can clarify further.

**Comment by cdubz** [comment]
@lutzky OK I got ya now. I was thinking about the data entry screens and not the list screens. Those horizontal scroll recommendations all make sense.

> Oh, that's not quite what I meant; see the mockup picture I attached in the first post. That being said, the opposite format of "2 hours, 45 minutes (11:23pm)" would also work fine.

Ok I think I follow now. Still not sure if I like the idea. I'd need to see it implemented at higher fidelity I think.

> I mean a single page (dashboard or otherwise)

So there is a "timeline" view currently on the child page but its not really discoverable (and kind of dated). From the child dashboard click the child's name and you'll get a view like this:

![Screenshot 2021-07-02 at 08-04-35 Allison Weiss Baby Buddy](https://user-images.githubusercontent.com/10456740/124294098-2f06d700-db0c-11eb-8049-48b9e8258b3b.png)

**Comment by lutzky** [comment]
Huh, thanks! That timeline view is pretty much exactly what I want (and, heh, shows both time-ago and absolute-time). I did find it, but it's not working for me for some reason (it has basically `<ul class="timeline m-auto"></ul>` where the demo instance has all of the entries; separate issue, I'll debug it). I have additional tweak suggestions for it (also presented in checklist form for easy conversion to issues):

- [ ] Add prominent link to timeline view from dashboard
- [ ] Timeline view: Diaper change entries should detail diaper contents
- [ ] Timeline view: Feedings should show amount (if specified)
  - I think also, but am less sure
  - [ ] Timeline view: Feedings should show duration
- [ ] Timeline view: Activities should include their notes (or at least mark activities that have notes)

Seeing as the timeline view already does not require horizontal scrolling, I think these are higher-priority than the horizontal-scroll issues I mentioned originally.

**Comment by lutzky** [comment]
Alright, finally got a local dev env set up, #239 should help resolve whether it's a good idea or not.

**Comment by cdubz** [comment]
Alright, I'm on board with that one :+1:

**Comment by cdubz** [comment]
Also all the timeline view recommendations make sense to me. That's now a fancy task list though :D

**Comment by lutzky** [comment]
Alright, that's 17 of 20 tasks, and 100% of the "converted to task" ones. How do you feel about the remaining ones?

**Comment by cdubz** [comment]
@lutzky they all sound good to me. The timeline is sort of a forgotten feature so I'm very open to changes and improvements there.

**Comment by lutzky** [comment]
Cool! (That's odd to hear, I find it extremely useful). Would you be so kind as to hit the "convert to issue" button on them? I can't seem to, I think it's a weird ACL thing.

**Comment by cdubz** [comment]
Hopefully #270 will increase its visibility (:

**Comment by lutzky** [comment]
Damn, marked wrong issue as fixed by #281. It actually closes #270, not this.

**Comment by cdubz** [comment]
Oops! I noticed that but forgot to address.

**Comment by cdubz** [comment]
All done! Thanks @lutzky for all your feedback and ideas here. Lots of nice improvements and bug fixes out of this work!
