### ISSUE TITLE
`pipenv install` fails because of psycopg2

### ISSUE THREAD

**Issue by lutzky** [babybuddy/babybuddy#238]
When running `pipenv install --three -v`, I get:

```
creating pip-egg-info/psycopg2_binary.egg-info
writing pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
writing dependency_links to pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
writing top-level names to pip-egg-info/psycopg2_binary.egg-info/top_level.txt
writing manifest file 'pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'

Error: pg_config executable not found.

pg_config is required to build psycopg2 from source.  Please add the directory
containing pg_config to the $PATH or specify the full executable path with the
option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.

If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.

For further information please check the 'doc/src/install.rst' file (also at
<https://www.psycopg.org/docs/install.html>).


----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 82, in <module>
    main()
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 66, in main
    results = resolve(
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 56, in resolve
    return pipenv.utils.resolve_deps(
  File "/usr/lib/python3/dist-packages/pipenv/utils.py", line 417, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(
  File "/usr/lib/python3/dist-packages/pipenv/utils.py", line 336, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/resolver.py", line 297, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 174, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 222, in get_legacy_dependencies
    result = reqset._prepare_file(self.finder, ireq, ignore_requires_python=True)
  File "/usr/lib/python3/dist-packages/pipenv/patched/notpip/req/req_set.py", line 644, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python3/dist-packages/pipenv/patched/notpip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/req/req_install.py", line 435, in run_egg_info
    call_subprocess(
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/utils/__init__.py", line 705, in call_subprocess
    raise InstallationError(
pip9.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpd8afldflbuild/psycopg2-binary/
```

This is on Ubuntu 20.04.2. I find it surprising that this occurs, as it's the `psycopg2-binary` package that's listed in the first place. Commenting out `psycopg2-binary = "*"` in `Pipfile` works around the problem (I'll soon check if I can run it in sqlite-only mode this way, as the changes I'm interested in making are visual only). However, either this should be fixed, or the documentation be amended to install packages as necessary.

**Comment by cdubz** [comment]
Argh. The psycopg2 stuff has always been a PITA. I'll see if I can reproduce sometime soon. The dev environment for Baby Buddy is pretty dated at this point -- it really needs its own overhaul.

**Comment by cdubz** [comment]
@lutzky you eventually got yourself setup -- did you identify any other issue with the process? I just walk through the development install steps on a fresh Ubuntu 20.04 image and didn't hit this snag. Are you able to reproduce or provide steps to reproduce?

**Comment by lutzky** [comment]
This happens on a fresh Ubuntu 20.04 image in VirtualBox (as well as on WSL, which I suspected to be the culprit, but isn't). Indeed, on gitpod it doesn't happen, and indeed `pg_config` is available. It isn't installed in Ubuntu by default. Running `sudo apt install libpq-dev` does fix the problem (I was hesitant to do so because I thought it installs all of postgresql; it doesn't seem to). Maybe we just need to fix the documentation?

Do you, in fact, have `pg_config` installed? If so, can you please run this:

```
apt-cache rdepends --installed $(dpkg -S $(which pg_config) | cut -d: -f1)
```

**Comment by cdubz** [comment]
Hm OK. I'll give it a try in VirtualBox soon -- are you using the Ubuntu desktop or server variant when testing? I tested yesterday (without issue) by just spinning up an instance in Digital Ocean using Ubuntu 20.04 (assume server).

**Comment by cdubz** [comment]
Also FTR I just tested on a fresh Debian 10.10 install (because I happened to have that in VirtualBox already) and could not reproduce (i.e. was able to get the pipenv environment up and running). No `pg_config` present on the system.

**Comment by lutzky** [comment]
Very odd. I guess that the `-binary` package tries to find an appropriate prebuilt binary and, failing that, tries to build from source?
Indeed I'm not using the Ubuntu Server variant.

**Comment by cdubz** [comment]
> Very odd. I guess that the -binary package tries to find an appropriate prebuilt binary and, failing that, tries to build from source?

Ah yeah, I guess that makes sense. In that case it seems like if `libpq-dev` is lightweight there is no reason not to add it to the install steps.

**Comment by JeanFred** [comment]
Sounds like a pip issue, per https://github.com/psycopg/psycopg2/issues/699#issuecomment-377188700 ?

**Comment by lutzky** [comment]
Ah indeed, I'm on pip 20.0.2, and it appears this was added in pip 20.3?
