### ISSUE TITLE
Upgrade from 1.41

### ISSUE THREAD

**Issue by Luzr** [babybuddy/babybuddy#252]
Hi,

What is the best way to upgrade from 1.41?

**Comment by cdubz** [comment]
@Luzr how did you deploy the app? There are no major breaking changes between 1.4.1 and the latest release so upgrading should be straightforward.

**Comment by Luzr** [comment]
Thanks for the reply. I used the Docker Image.

**Comment by cdubz** [comment]
@Luzr I recommend hoping on gitter and asking there. A number of Docker users are in that channel and may be able to help better with your specific setup.

https://gitter.im/babybuddy/Lobby
