### ISSUE TITLE
Force periodic refresh for always-on-devices

### ISSUE THREAD

**Issue by lutzky** [babybuddy/babybuddy#253]
Using an always-on device, the browser never has a "got focus" event; however, the browser does support refresh-on-focus, so there is currently no way to force a refresh.

Proposal: Replace the text "This setting will only be used when a browser does not support refresh on focus" with a checkbox (off-by-default) "Force refreshes even if browser supports refresh-on-focus".

**Comment by cdubz** [comment]
This makes sense to me. I don't think we need to be too verbose here though -- let's change just change the field text to "Supported browsers will also refresh on focus."

And for the code change let's change the logic to check _for_ support (as opposed to lack of support) and add the focus handler and always add the refresh rate interval (if set). This should make the logic in there a little simpler.

**Comment by lutzky** [comment]
So this is pretty much https://github.com/lutzky/babybuddy/commit/acd8f9011c9fc95378d18f2887c96504816f4897, I figured I'd test it out before sending a PR. Seems to work well.

**Comment by lutzky** [comment]
Went ahead and made a pull request of it, after confirming that it's working well.
