### ISSUE TITLE
Start / finish times are treated as inclusive-at-both-ends ranges rather than standard half-open ranges

### ISSUE THREAD

**Issue by jbg** [babybuddy/babybuddy#263]
Entering a breastfeeding session like this:

left breast 01:00-01:15
right breast 01:15-01:30

is intuitive, but fails due to "overlap".

Really there is no overlap – ranges should probably be treated as standard form (inclusive at the start and exclusive at the end), like the default behaviour of the `tsrange` type in Postgres and other databases, and the range type in most programming languages.

**Comment by cdubz** [comment]
Makes sense. Happy to take a PR to address this or I’ll get to looking at it at some point.

**Comment by cdubz** [comment]
@jbg FYI this behavior is changed in `master`. I ended up making the check exclusive at both ends because I didn't feel like half-open ranges made sense (or I didn't understand the difference well enough). Interested to know if you have any feedback on that -- i.e. can you think of a example that shows a relevant difference between half-open ranges and exclusive at both ends?

**Comment by jbg** [comment]
Half-open ranges are quite standard, because they mean that ranges that follow each other don't have infinitesimal gaps between them:

01:00:00-01:15:00
01:15:00-01:20:00

Most people would say that a) there's no gap between those, and b) they don't overlap. With open-at-both-ends ranges, there's a gap between them, and with closed-at-both-ends ranges, they overlap.

It also means the duration of the range is simply `end - start`.

For some theoretical perspective, [Dijkstra discusses it here](https://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD831.html).

**Comment by cdubz** [comment]
Ok. I think I get it. I don’t believe the distinction is relevant for the intersection “check” that prevents the entry in your example but would be for dealing with durations and continuity of entries (for example). Not sure if further changes are needed for those scenarios but can keep an eye out.
