### ISSUE TITLE
Add prominent link to timeline view from dashboard

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#271]

**Comment by lutzky** [comment]
Added a couple of proposals, WDYT?

**Comment by cdubz** [comment]
@lutzky both PRs need static files updated. Sorry 😬

**Comment by lutzky** [comment]
:facepalm: done

**Comment by cdubz** [comment]
@lutzky I’m on the fence here. I have one primary concern for each proposal —

#277 looks nice but I think the card needs to have some information or else it’s kind of weird as part of the dashboard (which is meant to quickly show information). Maybe it’s content could be the last event of any type for the child?

#278 might be a little complicated to wire up (getting child context in menu) and confusing if the timeline link uses that context but the other two primary mobile links (start timer and add event) don’t (but they could!). But my bigger concern is that the icon is too similar to the timer icon. I think they’d need to be more visually distinct to be some prominently placed next to each other.

If we can find a more appropriate icon I think I like #278 but frankly I would also even be open to both.

**Comment by lutzky** [comment]
I think that the complication of #278 makes it not worth it for such a small cosmetic change (I thought I was missing something obvious), when we have a simpler alternative like #277.

As for #277, my concern is that it takes up too much above-the-fold space; previewing the demo in "iPhone X 375x812" layout makes it push the "Today's Feeding" content below the fold. Adding details to the card would make it worse. Maybe it's actually worth making it the *last* card of the dashboard?

**Comment by cdubz** [comment]
Is the last card prominent enough though? I like the idea of making this much more prominent particularly since you've been making so many positive changes to the timeline recently. But maybe the bottom make the most sense for now. I really need to get to #34 some day.

**Comment by lutzky** [comment]
I guess it wouldn't be prominent enough :/
Then again, top seems... *too* prominent?

How about a whole different direction:

![Screenshot from 2021-08-09 20-58-31](https://user-images.githubusercontent.com/8140/128766624-a5d25781-f04d-460c-b14d-dca895e93604.png)

That is, just adding the `icon-history` bit to the breadcrumb.

**Comment by cdubz** [comment]
I don't think that does enough either. Although it does highlight the fact that we already have a quick link directly to the timeline right at the top (by clicking the child's name). I honestly kind of forgot that myself lol. I really think #278 is the way to go despite the additional complexity.

**Comment by lutzky** [comment]
Alright then, I'd appreciate some help with this one; I'm not familiar enough with django to easily find a quick way to wire everything neatly. (...and it is the last blocker for #229!)

**Comment by cdubz** [comment]
Yeah, it's on my radar but won't get to it until after next week due to travel.

**Comment by cdubz** [comment]
Alright this will be a bit complicated but I think it's worth it to make the timeline more of a first class citizen --

- [ ] Add new timeline view to core (similar to dashboard view -- redirects to child detail page for one child).
- [ ] Create handling for a multiple child timeline view (to create a central timeline when more than one child is present).
- [ ] Add timeline link to child button group.
- [ ] Find and use a better icon for timeline (or replace the timer icon with something less like the timeline icon).
- [ ] Add tests
