### ISSUE TITLE
v1.8 shorter timestamps using UTC time

### ISSUE THREAD

**Issue by Xe138** [babybuddy/babybuddy#274]
The v1.8 shorter timestamps in the list views are showing the UTC time of the entries rather than the local time.  The entries are correctly using local time.

Feeding Entry:
![image](https://user-images.githubusercontent.com/50377201/128416545-83d093f5-f1f0-46e2-a08d-93a99af575f4.png)

Feeding List:
![image](https://user-images.githubusercontent.com/50377201/128416600-d9a1d40d-b6ad-4957-8f52-6c88331a245e.png)

**Comment by cdubz** [comment]
Damn. Thanks for reporting. I always manage to mess up _something_ when dealing with localization (:

Will try to get a quick fix for this.

**Comment by AhmetCelikbasBMX** [comment]
Hi @cdubz, Thanks for your support ! 

I'm also affected by this issue (First line was set to 9:45am but showing 7:45am). 

I also got other localisation/translation issues when i put the language to French :
![image](https://user-images.githubusercontent.com/70146550/128480212-3474dd97-bc96-4e25-8e87-11a720ef1b16.png)

Here is the same page when i choose English language : 
![image](https://user-images.githubusercontent.com/70146550/128480810-93430c11-873e-4331-80c7-6179933a7d63.png)


i have the same issue on all other activities (Feedings, sleep ...)
