### ISSUE TITLE
Sleep graph issues

### ISSUE THREAD

**Issue by fodi666** [babybuddy/babybuddy#283]
- [x] #286
- [x] #287
- [x] #288
- [x] #289
- [x] #290

--

Hi,
I have found that the sleep pattern plot is misaligned. I attach an image with the problem.
![newplot](https://user-images.githubusercontent.com/1128180/130141653-02077737-1ea5-439f-8ed0-bcba164a3ff1.png)

The first column is supposed to be 17 August while the second column of sleep entry is today (19 August), with no entries from 18 August. Yet, the two days are connected, so it seems that the patterns are valid for two days, but most importantly, the times don't match between the two columns. The first column seems to be at the good position, while today's plot is at weird time slots.
Actually the first problem (weird x-axis representation) is also present on other graphs, for example the feeding graph:
![feeding](https://user-images.githubusercontent.com/1128180/130141996-9344cf5b-6afd-4bf6-9448-94fbed3fab69.png)

I think that the columns should range from 0:00 to 23:59 each day.

Also, I'd have a suggestion with this: could you invert the y-axis, so the day goes from top to bottom instead of bottom to top? It would make it easier to follow.
Thanks

**Comment by cdubz** [comment]
Hm yeah... I'm guessing that somewhere along the line we assume that entries for the sleep pattern graph do not have any gaps. That's definitely a bug of some sort.

@fodi666 re: the other parts of your comments on weird x-axis representation and inverting to y-axis -- I'm not totally clear what the ask/desired functionality is. Could you clarify? Or maybe rough up an example graph of what you are thinking?

**Comment by fodi666** [comment]
OK, so it seems that the missing day gets compensated once I had some more days added and now it honors the missing day correctly.
However, Aug 19 is still shifted, if you check the screenshot, the bottom sleep for Aug 19 is 1258 AM to 0350 AM, yet it is lined with a sleep from the other day at 1053 AM to 1230 PM. This for some reason stayed. I actually have a 24h setting with environmental variables set and the UI uses 24h, however this graph for some reason uses 12h format, which is also strange.
The weird x-axis is the fact that it is shifted by 12 hours if you check the columns and the x axis labels. This is also visible on the other plots (the start of the day on the axis is actually in the middle of the columns).

![Inkedsleep pattern bug](https://user-images.githubusercontent.com/1128180/130329330-6163ea5c-78fc-455f-b843-994194893aa6.jpg)

Regarding the y-axis inversion, I was thinking only about the sleep pattern plot, to have midnight at the top instead of the bottom and then having the day progress downwards instead of going upwards as it does now. If you have for example a TV grid you also find the day going downwards, this would make more sense to me.

**Comment by fodi666** [comment]
So, in the meanwhile I poked around in my database and it looks like long gaps can mess up the pattern chart.
First I added a dummy 1-minute sleep (0:00:00 to 0:01:00) to Aug 18, and while this fixed the column of Aug 19, now this dummy sleep was shifted upwards. I saw that my Aug 17 is still missing some entries, and while I added them from our paper records, this shift began to decrease and once I got to midnight of the previous day with sleep, it became fine. Then I deleted the dummy one.minute sleep and started filling up Aug 18, and once I deleted this dummy item, the shift from Aug 19 returned and then once I added an item to midnight it normalized.
![newplot (1)](https://user-images.githubusercontent.com/1128180/130331072-fd660932-e45c-4350-ace1-983ebbcf3de6.png)
.
One more thing which I found in the process: if I only had an entry for Aug 18 with a sleep starting the night before and only ending this day, I got a django error on the chart and I had to add another entry for that day which started that day.

**Comment by cdubz** [comment]
Ok, I think I've got you now. The tasks I think are --

- [ ] Sleep graph has incorrect positioning when there is a gap in days. (bugfix)
- [ ] Sleep graph uses 12h format when 24h is enabled. (bugfix)
- [ ] Graph x-axis date labels should not show times, only dates. (bugfix)
- [ ] Sleep graph y-axis should go "down" from midnight at the top. (enhancement)
- [ ] If there is only one sleep entry and it starts one one day and ends the next day the sleep graph excepts. (bugfix)

Sound right?

**Comment by fodi666** [comment]
yes, that's it I think
the 12-hour format occurs also on the y-axis labels and the priod (area) labels. If you need I can send you the exported data presented in comment 3.

**Comment by cdubz** [comment]
It sounds like I should be able to repro easily enough when I get around to looking at this. But maybe keep a copy of the comment 3 DB in that state just in case (:

**Comment by codisart** [comment]
Hello @cdubz I was motivated to check this bug out. But the sleep_pattern.py is a little bit hard to comprehend. Are you ok with maybe few simple PRs to reduce the complexity and to help me understand what is going on ?

**Comment by cdubz** [comment]
Absolutely I am! That code is a mess 😬

**Comment by fodi666** [comment]
@codisart if you are planning tweaking the sleep graph, could you maybe prepare it to accept other actitivies as well? (feeding, diaper, tummy time) or at least in a way that would allow it more (aka #218 )
