### ISSUE TITLE
Allow manual editting of datetime values

### ISSUE THREAD

**Issue by Expro** [babybuddy/babybuddy#284]
Please restore ability to correct time entry from keyboard by deleting and writing down numbers, instead of several clicks through GUI. Baby can be demanding and requiring attention, so slowing down ability to add correct entry is unwelcome.

**Comment by cdubz** [comment]
@Expro this is actually intentional and the previous behavior was treated as bug (see #224 and comments). Are you saying to prefer to be able to click in to the date/time field and manually change the text after making a selection with the date picker? If so, why? Just wondering if there is also a datepicker UX issue to be considered here.

**Comment by Expro** [comment]
> If so, why?

This are scenarios where it comes handy:

- App was inaccessible for some reason, and I have noted time as text somewhere else. With date and time field as text field I can just dismiss datepicker and copy-paste in time. In newer version, I have to go through GUI and recreate time value, which is slower and less comfortable.
- I have started timer with some delay (usually with 2 / 3 minutes late, cause baby comes first), so I just want to correct time value. With time being text, I can just delete 2 last numbers. With GUI only, I have to switch from date to time and then do several clicks to fix time value.
- Text field allows me to use speech to text to dictate time. 

> Just wondering if there is also a datepicker UX issue to be considered here.

There is definitely one thing that could be improved - datepicker opens with view focused on date, rather than time, and it should be reversed. I rarely have to provide time different than "today" (either when putting in old notes, or on action that started yesterday, but ended today) but I provide time many times per day. Please optimize default view for more common action.

Other than that, date / time picker is very well done.

**Comment by cdubz** [comment]
Ok. That all makes sense. Interesting use case with speech text!

**Comment by Expro** [comment]
I think there is enough space even on mobile screens to layout with button for date picker, button for time picker and textbox with resulting date + time that is editable (without triggering pickers when focused). That would allow user to select if he wants to pick date, time, or edit it by hand.

**Comment by cdubz** [comment]
Interesting idea. Not sure if the existing picker library BB uses supports that but I have also been looking for excuses to move away from it because it’s had lots of weird refactoring over the years. Though every time I have looked I haven’t really been able to find a comparatively good picker.

**Comment by cdubz** [comment]
@Expro I’d be interested in your thought on #304 related to this.
