### ISSUE TITLE
Sleep graph uses 12h format when 24h is enabled.

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#287]

**Comment by cdubz** [comment]
#288 makes this no longer relevant.

**Comment by fodi666** [comment]
This is still present on 1.8.3, unfortunately, both on the y-axis and both on the labels of the individual sleep sessions (see attached image).
![image](https://user-images.githubusercontent.com/1128180/131229203-ac0cb918-dff7-4ec1-97f7-e5574e4beb73.png)

**Comment by cdubz** [comment]
Oh shoot I forgot about the data labels! I was only thinking about this for the x-axis labels.  Oops :grimacing:

**Comment by fodi666** [comment]
and don't forget the y-axis either ;)

**Comment by cdubz** [comment]
Haha yes I see that, too.

**Comment by cdubz** [comment]
I address this in what I think is the "right" way (using locale-aware time formatting) but it has pretty interesting effect on 12-hour formatted strings --

![image](https://user-images.githubusercontent.com/10456740/131230934-5aa3bf96-bd78-4529-97df-94e456a4413a.png)

It was kind of jarring at first because the y-axis labels don't line up like they used but I'm not sure if I dislike that or its just different :shrug:

Anyway this will solve nicely for the 24-hour use case and I'll sit on it for a bit re: the changes in look of the 12-hour.

I also updated the deprecated graph library config so the labels don't print inside the bars (in teeny unreadable text), just on hover.

**Comment by fodi666** [comment]
that is nice and looks really nice on 24-h format, indeed
I copied manually the change to my instance via docker bash and also added `layout_args['yaxis']['autorange'] = 'reversed'` around line 158, so now the timeline goes from up to down
![image](https://user-images.githubusercontent.com/1128180/131231246-5f4deb9b-6574-4708-8043-2e8c76115499.png)

**Comment by cdubz** [comment]
Oh is it really that simple? Hah. Hadn’t looked at that ticket yet. The code for generating this graph is kind of bananas and I figured I’d have to refactor for that.
