### ISSUE TITLE
If there is only one sleep entry and it starts one day and ends the next day the sleep graph excepts.

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#290]

**Comment by cdubz** [comment]
@fodi666 I wasn't actually able to reproduce this. I did just push a fix for #293 that seems like it would be related. Could you see if you can still repro?

**Comment by fodi666** [comment]
I'll check it in 1.8.2 tonight and then update to 1.8.3 tomorrow and check again.

**Comment by fodi666** [comment]
@cdubz ,
finally I went to the database manager and did a test running 1.8.2: my entries start on the 17 Aug. So I added a sleep entry that starts 15 Aug 23:00 and ends 16 Aug 00:05. 16 Aug has no other sleep entries. Then I checked the sleep pattern and that's what I got:
`KeyError` at /children/bubu/reports/sleep/pattern/
'2021-08-16'
Request Method:	GET
Request URL:	http://homeassistant.local:47074/children/bubu/reports/sleep/pattern/
Django Version:	3.2.5
Exception Type:	KeyError
Exception Value:	
'2021-08-16'
Exception Location:	/app/babybuddy/reports/graphs/sleep_pattern.py, line 39, in sleep_pattern
Python Executable:	/usr/bin/python3
Python Version:	3.9.5
Python Path:	
['/app/babybuddy',
 '/usr/bin',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/usr/lib/python3.9/site-packages',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf']

Once I deleted this item or I added a new sleep for 16 Aug it works fine.

**Comment by cdubz** [comment]
@fodi666 OK I think that is fixed by #293. I had recorded this ticket as a different issue having to do with a use case of only one total sleep entry. Verify with 1.8.3 when you can and if that scenario you deceive is fixed I’ll close out this issue as well.

**Comment by fodi666** [comment]
I have pulled the 1.8.3 docker image and now it works fine, no keyerror
