### ISSUE TITLE
Timer view should show today's totals

### ISSUE THREAD

**Issue by lutzky** [babybuddy/babybuddy#294]
The timer buttons should show the total-so-far for the buttons, see mockup below.

Usecase: Timer is open for feeding, baby seems not too keen. Turns out baby already ate a lot today, and it's fine. However, my tablet-in-the-livingroom-for-showing-babybuddy isn't showing me that, as the whole screen is used for the feeding timer.

Should be straightforward to implement, but I was looking to get your thoughts first.

![timer-with-totals](https://user-images.githubusercontent.com/8140/131161226-21a2ab2b-16fc-4840-8a9b-70d705262c69.png)

**Comment by cdubz** [comment]
Interesting... I like the idea but I wonder if total "amount" is the right context to give for feedings? Maybe it should be total feedings on the day? And I also kind of wonder if better context would be the _last_ occurrence of each event instead of day totals?

**Comment by lutzky** [comment]
Hmm, for me the total was definitely the number I was interested in, but I can see how other people would want different numbers. How about something like this:

> :spoon: Feeding (Last: 100.0, Today: 400.0 / 4x)

The information can definitely all fit there, if abbreviated, but I do wonder if there's a clearer abbreviation to be made. (I particularly wonder why Sleep is listed as 2**h** but Tummy Time is 8 **minutes** as opposed to 8**m**; this is copied from the dashboard)

**Comment by cdubz** [comment]
Do you think it would like bad if we broke it in to two lines? That just feels like a lot of data to jam in to the button text on a single line.

**Comment by lutzky** [comment]
Maybe. On phones, sure, I have plenty of vertical real estate remaining. However, on my tablet, there's actually a lot of unused *horizontal* space, but not so much vertical. So perhaps some CSS magic to split it neatly on narrow displays?

**Comment by cdubz** [comment]
Ah yeah good point. Those buttons are looooong on desktop hah.

**Comment by lutzky** [comment]
Alright, I'd need some guidance with this as I'm not experienced with django; how would I go about getting child data in `timer_detail.html`? (If you could point me to an existing place that does something similar in the code)

**Comment by cdubz** [comment]
The timer object has a `child` key that you can use. It is set automatically if there is only one child in the DB but the default is `None` so that will need to be checked for.

**Comment by ntrecina** [comment]
It seems like adding this info makes the screen really busy and it may or may not be useful considering that it's duplicated information from the dashboard. If it were to be implemented perhaps the info could be added behind a toggle of some kind (a tooltip or more details link) and hidden by default or maybe this feature could be disabled via a user setting.

**Comment by cdubz** [comment]
Yeah I’m concerned about that as well @ntrecina. Interested to see how it looks before thinking about that though.

**Comment by lutzky** [comment]
Come to think of it, I'm also interested in making this user-configurable. There's another feature that I'm hesitant to add (although I did have it in my local version for a while) is a plain clock. Such things would indeed make more sense as configurable options, be it per-user (saved in the DB, more complicated?) vs global (environment variable, simpler?) - is there an open issue for such a concept?

**Comment by cdubz** [comment]
@lutzky I don’t believe there is an existing issue re: a plain clock. Though I’m also not sure what you mean by that? Just something (in the dashboard?) showing the current time?

**Comment by lutzky** [comment]
Ah, apologies, I mean an issue regarding "more configurable options". The clock thing is just something I hacked together myself (it's for the top navbar; it's useful when using babybuddy on a wall-panel in a dark room with no other backlit clock), which I'd only think makes sense to merge into master if it's configurable.

**Comment by cdubz** [comment]
I’m slightly hesitant to make too many things configurable. But that’s only my personal opinion.

I think a more immediate issue would be how to improve the user settings screen to make it easier to understand and navigate. Right now it’s just a long list with some minor categorization and some of the existing options are kind of confusing.

And re: ENV vars, I would rather use per-user settings for most things. I the ENV config pattern is kind of a relic of initial development of the app that didn’t have any substantial per-user settings.
