### ISSUE TITLE
Favicon is hard to see on dark backgrounds

### ISSUE THREAD

**Issue by lutzky** [babybuddy/babybuddy#297]
Switched my browser to a night-mode dark blue theme and... where did babybuddy go? Oh yeah, it's dark-blue-on-slightly-darker-blue. I don't have the know-how to do this neatly, especially with the smaller pixel sizes, but I'd advise:

* Easy, but would look very different: Make eyes, mouth and clock-hands white
* Hard, but would retain general aesthetic: Add a thin white border around the entire silhouette

**Comment by cdubz** [comment]
I think the favicon and icon both have too dark a color -- i.e. it has never been the "brand" color (which has no changed to be lighter as well). Can you add some screenshots of where you see it as bad now?

**Comment by lutzky** [comment]
Sure. For the favicon, see if you can spot it here (using [this Chrome theme](https://chrome.google.com/webstore/detail/a-passion/elbejlmapdnkbjofccadjlkmcpggfclg)):

![Invisible](https://user-images.githubusercontent.com/8140/131551560-f73b00fe-013d-4c65-bfba-931db98d566a.png)

For the icon, frankly, right there in the header, the dark-blue-on-dark-grey seems low-contrast to me. Text is a slightly brighter blue, too.

**Comment by lutzky** [comment]
Header I was talking about:

![Header](https://user-images.githubusercontent.com/8140/131562577-32ed6150-2b3f-40e2-a03a-2b0a10319814.png)

Note how the word "baby" is brighter than the icon. For the contrast between the icon and the background, we get a [constrast ratio of 1.4](https://webaim.org/resources/contrastchecker/?fcolor=07547D&bcolor=343A40) (same page explains that the recommendation is at least 3).

**Comment by cdubz** [comment]
Those blues are different because [you changed the blues](https://github.com/babybuddy/babybuddy/blame/f643ad7771108cad1c6a585033e3b41752954236/babybuddy/static_src/scss/themes/blueorange.scss#L7) 😛

If the icon used the _new_ blue would it be passable? Or do we really need to do more here? Also, FTR, I think the icon blue has never been right, hah.

I need to dig up the original icon files...

**Comment by cdubz** [comment]
Ok finally started working on this. There is a certain ghostly them to current iteration lol :ghost: 

![image](https://user-images.githubusercontent.com/10456740/133872402-4ee8e9be-6449-4f4b-a984-922ec0e09bab.png)

I may need to find/enlist some help from someone who actually knows how to work with SVG files...

**Comment by lutzky** [comment]
That's, uh, terrifying :sweat_smile: on a blue background, you'd see just the eyes, too. I'd drop the white eyes in favor of an outline around the whole shape.

**Comment by cdubz** [comment]
Thoughts on this? It has a very light white border --

![image](https://user-images.githubusercontent.com/10456740/134006111-e232c8fb-e866-4e3f-aaf7-463d1e48215e.png)

**Comment by lutzky** [comment]
*[squints]*

Does it? The best test is "how would it fare on a background that happens to be the same color as the foreground", and my guess is that it would disappear.

**Comment by cdubz** [comment]
It does! Anything thicker looks really mashes up the details. The only option that would that well, I think, would be to use a background with the image but I think that is the less attractive option --

![image](https://user-images.githubusercontent.com/10456740/134009874-bb8f4348-7862-40ba-b3e7-7854f62f387c.png)

**Comment by lutzky** [comment]
Here's what I had in mind - I made this in gimp starting with `icon-brand.png` - which, incidentally, is partially transparent! Is that on purpose? I fought it by duplicating the layer 4 times. (Border was added by adding another layer below, "alpha to selection" + grow selection by 2px.

Option 1:

![icon-border](https://user-images.githubusercontent.com/8140/134051231-fb1821c3-592e-4a27-bd95-37f8f07fc002.png)

Option 2:

![icon-border2](https://user-images.githubusercontent.com/8140/134051498-c2ee92ef-4966-47b8-a3c6-e38b887ad070.png)

**Comment by cdubz** [comment]
Haha yeah the current brand icon on `matser` is a mess. I'm also updating these assets generally in https://github.com/babybuddy/babybuddy/pull/312 so there are better starting points there (including SVGs).

I'll give a thicker stroke a try again later. To me it seemed like it would look bad on dark backgrounds...

**Comment by lutzky** [comment]
Looks pretty good to me on Github Dark Mode.

**Comment by cdubz** [comment]
Yeah but at favicon size?

![image](https://user-images.githubusercontent.com/10456740/134054617-83ea9c6b-6262-4079-823e-d1027e1ded19.png)

![image](https://user-images.githubusercontent.com/10456740/134054713-f41dd88e-ef8e-4737-93e4-438a41c630db.png)

**Comment by lutzky** [comment]
Yeah, still looks good to me... I gather you don't like it. I'm not much of an artist 😅

**Comment by cdubz** [comment]
Haha me neither. The second one with filled in details look like it _may_ work so I'll run a variant of that through a full test. There is also some way to handle different versions for dark/light mode but I'm unclear on that standard/how it integrates with browser usage of the favicon.

**Comment by cdubz** [comment]
Alright I fiddled with this _a lot_ and didn't come up with a "works in all scenarios" version that I liked. I'm sticking with the updated theme blue and changing to an SVG icon (that does have a dark mode setting that browser may or may not use :shrug:).
