### ISSUE TITLE
iOS Shortcuts

### ISSUE THREAD

**Issue by kejadlen** [babybuddy/babybuddy#299]
A few basic iOS shortcuts that can be used as templates if other people want to use Siri to add diaper changes and start/stop timers. I’ve only implemented the functionality I need, but putting them here for now so other people can pull them down and configure it for their own needs.

- [Add Diaper Change](https://www.icloud.com/shortcuts/10824127057043eeb7e1edc8fb7ad3e9)
- [Start Baby Buddy](https://www.icloud.com/shortcuts/ecd626a6a08b427cb333290a7e444569)
- [Stop Baby Buddy](https://www.icloud.com/shortcuts/2f61fac844354f729bfb40c67df69955)

**Comment by cdubz** [comment]
Thanks for sharing, @kejadlen! I didn’t know you could do form POST operations like this with Shortcuts… it would be nice to have a full set of functionality available for this. I’ll probably play around with adding more at some point.
