### ISSUE TITLE
Buttons icon glyphs missing in time selector

### ISSUE THREAD

**Issue by lutzky** [babybuddy/babybuddy#302]
When clicking a time selector, e.g. in the "add activity" screen, the glyphs are missing - the buttons are functional, but have no icons on them. Presumably this has to do with the recent fontawesome transition.

**Comment by cdubz** [comment]
Ah good catch. I didn't realize the picker relied on FA as well as BS. Will need to pull in the necessary icons in the fontello config...

**Comment by lutzky** [comment]
See, this is why it's important to be able to easily run the equivalent of a nightly at home ^_^ (I have a modified version of the linuxserver docker build which builds straight from lutzky/babybuddy:master)
