### ISSUE TITLE
Possible to manually assign nap / sleep?

### ISSUE THREAD

**Issue by sfgabe** [babybuddy/babybuddy#323]
Working with a newborn here and the idea of a "nap" depends more on where the sleeping happens - ie: in the swing is a nap / back sleeping in bed is sleep.

Is it possible to create a checkbox for "nap" instead of relying on the config? Also, bed times are going to change as sleep gets more regular - can this be something that is configurable in the UI instead of editing the config whenever that happens?

**Comment by cdubz** [comment]
Closing in favor of tracking in #513.
