### ISSUE TITLE
Help with API - Only Receive Todays Results

### ISSUE THREAD

**Issue by Shaun-Harrison** [babybuddy/babybuddy#328]
Hi, I'm integrating the baby buddy into my HA instance - I've managed to get some of the basics working but noticed the results won't be for todays date, only for all the records available 

Is it possibly to query the API and have a filter to only include results from today?

**Comment by cdubz** [comment]
Hi @Shaun-Harrison 👋  Looks the API indeed does not have a date filter… this would definitely be a useful enhancement. Happy to get a PR or I’ll take a look when I can.

**Comment by cdubz** [comment]
This is in `matser` now -- thanks for pointing it out! I will probably do a release sometime in the next few days or week here,

**Comment by Shaun-Harrison** [comment]
Hi @cdubz - seen that a new release has gone through - what is the formatting for getting it to filter by time now?

**Comment by Shaun-Harrison** [comment]
Hi again @cdubz 

Just an update on the above query, got filtering by date on feeding and sleep working, but using

?time=[DATE]

for Changes is not working for me at all, any suggestions?

**Comment by cdubz** [comment]
@Shaun-Harrison sorry I haven’t follow up yet. Been traveling but wanted to test myself before responding. The [schema doc](https://github.com/babybuddy/babybuddy/blob/master/openapi-schema.yml ) should point you in the right direction for available filters. If something is documented there and not working please open a new ticket (or ditto if you find that this filtering is not available somewhere it should be).

**Comment by Shaun-Harrison** [comment]
@cdubz No need to apologise! hope your well and enjoying the travels!

Will open a new issue now with what I've found, the schema doc is a big help though, stops me guessing what they are :D
