### ISSUE TITLE
OPTIONS API returns results instead of parameters

### ISSUE THREAD

**Issue by phoenixfangor** [babybuddy/babybuddy#329]
Current: Using the API on version 1.6.0, send an Options request for children or changes (perhaps others, too). The response is as follows:
`{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 1,
            "first_name": "xxxx",
            "last_name": "xxxxxxxx",
            "birth_date": "2021-05-23",
            "slug": "xxxx-xxxxxxxx",
            "picture": null
        }
    ]
}`

Expected: I would expect the Options call to respond with like the documentation:
`{
    "name": "Child List",
    "renders": [
        "application/json",
        "text/html"
    ],
    "parses": [
        "application/json",
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "actions": {
        "POST": {
            "id": {
                "type": "integer",
                "required": false,
                "read_only": true,
                "label": "ID"
            },
            [...]
        }
    },
    "filters": [
        "first_name",
        "last_name",
        "slug"
    ]
}`

**Comment by cdubz** [comment]
Thanks for reporting! That definitely worked at some point…

**Comment by cdubz** [comment]
@phoenixfangor could you provide steps to reproduce this? Testing from the API browser and Postman I am able to get the correct `OPTIONS` responses --

# Request
```
curl --location --request OPTIONS 'http://127.0.0.1:8000/api/children/' \
--header 'Authorization: Token 1a78dd73df63003f77ac89109c414674d1ef482d'
```

# Response
```json
{
    "name": "Child List",
    "renders": [
        "application/json",
        "text/html"
    ],
    "parses": [
        "application/json",
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "actions": {
        "POST": {
            "id": {
                "type": "integer",
                "required": false,
                "read_only": true,
                "label": "ID"
            },
            "first_name": {
                "type": "string",
                "required": true,
                "read_only": false,
                "label": "First name",
                "max_length": 255
            },
            "last_name": {
                "type": "string",
                "required": true,
                "read_only": false,
                "label": "Last name",
                "max_length": 255
            },
            "birth_date": {
                "type": "date",
                "required": true,
                "read_only": false,
                "label": "Birth date"
            },
            "slug": {
                "type": "slug",
                "required": false,
                "read_only": true,
                "label": "Slug"
            },
            "picture": {
                "type": "image upload",
                "required": false,
                "read_only": false,
                "label": "Picture",
                "max_length": 100
            }
        }
    },
    "filters": [
        "first_name",
        "last_name",
        "slug"
    ]
}
```

**Comment by phoenixfangor** [comment]
Turns out it was a mis-configuration with Postman, it was not following the redirect with the original HTTP method by default and is working once I enabled that setting.
