### ISSUE TITLE
en_GB Time Format (24 Hour)

### ISSUE THREAD

**Issue by Amith211** [babybuddy/babybuddy#333]
Following on from #332, `en_GB` needs have an implementation for `USE_24_HOUR_TIME_FORMAT`.

The default Django implementation for `en_GB` using 12h as the default seems incorrect to me for the following reasons: 

1. In the UK, pretty much all digital clocks will use the 24h format as will bus & train timetables.
2. To help evidence this, with `en_Gb` as the locale both linux and windows use the 24h as the default.
```bash
#bash 
date

#Fri Nov 12 22:55:46 GMT 2021
```
```posh
#powershell
Get-Date

#12 November 2021 22:56:04
```
I must admit I was surprised to see a couple of big television websites, ITV (Channel 3) and Channel 4 (4OD) that have the time in 12h format. 

I would suggest that today's standard when it comes to digital displays is 24h as the default, with 12h as an option. That being said, I would not disagree with 12h being the default for technical reasons or to be consistent with other language conventions or the default Django implementation, either way the 24h formation must have an implementation.

For more background see [Wiki](https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_Kingdom#Time_notation_in_English)

@cdubz If my understanding of how this should be implemented is correct, I'll submit a PR tomorrow or Sunday.

**Comment by cdubz** [comment]
This all sounds right. I’d actually agree with you that I’d rather have 24H be the standard with a 12H option but I feel like that would introduce confusion and delay here.

That said, I’d also entertain deprecated the env var and letting users set this as part of their own user settings but that can be a follow up issue 😁

**Comment by AndreKR** [comment]
Do I understand this correctly that if I choose "English (UK)" as language I should get proper 24-hour clock?

It doesn't seem to work for me:
![image](https://user-images.githubusercontent.com/1188538/209620312-abd07e5a-a66b-4d16-93c7-4689c7f2692c.png)
![image](https://user-images.githubusercontent.com/1188538/209620340-a0448e4e-bd95-4c9a-b202-c2c38258038c.png)
![image](https://user-images.githubusercontent.com/1188538/209620370-d41ef5fd-5f89-4646-84a1-ceeb4ee24b88.png)

**Comment by AndreKR** [comment]
Ah, got it, it also requires setting the environment variable `USE_24_HOUR_TIME_FORMAT` to something.

**Comment by balintbabics** [comment]
Sorry to reopen this closed issue, but I feel like my issue is connecting here the best.

I just upgraded my instance to the latest version (v2.0.1) and I realized, that the `USE_24_HOUR_TIME_FORMAT` env variable was retired unfortunately, and while the application supports our native language (HUN), we prefere(d) to use it in English. However, at the moment for both of the English language options, the 12h format is the default/fixed value.

Is there any workaround available to be able to use the app in English language but with 24h format?

**Comment by cdubz** [comment]
@balintbabics do me a favor and open a new issue referencing this one. I would like to support this but it was a big headache in v1. I’m not totally sure if the v2 changes would make it easier or harder to support but I’ll give it a fresh look. I also prefer 24h time generally so it annoys me to not support this 😆
