### ISSUE TITLE
"Deploy to Heroku" button broken now README is separated.

### ISSUE THREAD

**Issue by jfgxyz** [babybuddy/babybuddy#340]
clicking the "Deploy to Heroku" button located in the [Deployment](https://github.com/babybuddy/babybuddy/blob/master/docs/DEPLOYMENT.md) page of the README generates the URL:

https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fbabybuddy%2Fbabybuddy%2Fblob%2Fmaster%2Fdocs%2FDEPLOYMENT.md&template=https%3A%2F%2Fgithub.com%2Fbabybuddy%2Fbabybuddy%2Fblob%2Fmaster%2Fdocs%2FDEPLOYMENT.md

which gives the error on Heroku:

> No app.json located in the repo URL provided.

It looks like by splitting the README into multiple files in the commit: https://github.com/babybuddy/babybuddy/commit/9a584481f9e32fa90b620a6de6970b45091af1e5, it broke the auto generated URL, which should link directly to the repository rather than the Deployment page. The correct URL is:

https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fbabybuddy%2Fbabybuddy&template=https%3A%2F%2Fgithub.com%2Fbabybuddy%2Fbabybuddy

**Comment by cdubz** [comment]
Thanks for reporting this! Fixed.
