### ISSUE TITLE
New filters on date for changes

### ISSUE THREAD

**Issue by Shaun-Harrison** [babybuddy/babybuddy#342]
Hello!

Working on getting the amount of nappy changes there's been today by filtering on date

Looked at the [schema-doc](https://github.com/babybuddy/babybuddy/blob/master/openapi-schema.yml) for /api/changes it says that date is an option - but when using just date it gives the following 

![image](https://user-images.githubusercontent.com/46562010/142393691-782da053-5b39-43f5-a571-b1c0d2a762b3.png)

(using time btw doesn't seem to filter the results and returns all results)

It is possible to get around this though by using date_min & date_max 

`date_min=2021-10-21&date_max=2021-10-21`

So not an urgent issue to resolve

**Comment by cdubz** [comment]
Thanks for reporting! This filter was indeed broken. Fixed now in `master` and will probably have a 1.9.2 release soonish given a couple other small bugs.
