### ISSUE TITLE
Connection to Home Assistant

### ISSUE THREAD

**Issue by MaikelvdB07** [babybuddy/babybuddy#345]
Please help me out.

I've deployed the Baby Buddy on Heroku, but when I try to integrate it in Home Assistant it asks for a host and API.

What do I enter as the host?

It keeps saying that it can't connect when I enter the URL.

Thanks in advance!

**Comment by cdubz** [comment]
@jcgoette any input here? I have not used HA myself.

**Comment by jcgoette** [comment]
@MaikelvdB07 , please move this issue to https://github.com/jcgoette/baby_buddy_homeassistant.

**Comment by jcgoette** [comment]
Fixed at https://github.com/jcgoette/baby_buddy_homeassistant/issues/50.
