### ISSUE TITLE
Wrong language after logging in

### ISSUE THREAD

**Issue by Alberdi** [babybuddy/babybuddy#346]
When I log in, all the texts appear in English even though my user has Spanish as the default language. I'm using Firefox 94.0.2 with Galician as default language (not supported by Baby Buddy) and Spanish as second, in case it matters.

Steps to reproduce:
1. Open Baby Buddy on an incognito window.
2. The login screen appears in English (extra: should appear in Spanish because it's the second language of my browser?).
3. After logging in, all the texts are in English even though my user has Spanish as default language.
4. Go to settings, confirm that I have Spanish as default language. Submit the form.
5. Baby Buddy is now in Spanish (extra: the "settings saved" text appears in English instead of Spanish).

[Video of the issue](https://user-images.githubusercontent.com/1556349/143495209-0eb2d66b-ab33-4183-a303-5f8a9abc85ef.mov).

I can open additional issues for the "extra" issues, in case you want to track them.

**Comment by cdubz** [comment]
Thanks for the detailed report 👍 There was a recent change to the way language settings are handled that probably caused this. Will take a look when I can.

**Comment by cdubz** [comment]
@Alberdi thanks again for the report. These issues should be fixed and will be in the next release here soon.
