### ISSUE TITLE
column core_sleep.napping does not exist

### ISSUE THREAD

**Issue by Michaelpalacce** [babybuddy/babybuddy#348]
After a database restart i am encountering the following error:

<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(232, 230, 227); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ProgrammingError at /children/luna-genova/dashboard/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(177, 170, 160); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">column core_sleep.napping does not exist
LINE 1: ...ELECT "core_sleep"."id", "core_sleep"."child_id", "core_slee...
                                                             ^
</pre>

Request Method: | GET
-- | --
http://192.168.1.182:30100/children/luna-genova/dashboard/
3.2.9
ProgrammingError
column core_sleep.napping does not exist LINE 1: ...ELECT "core_sleep"."id", "core_sleep"."child_id", "core_slee...                                                              ^
/usr/lib/python3.9/site-packages/django/db/backends/utils.py, line 84, in _execute
/usr/bin/python3
3.9.5
['/app/babybuddy',  '/usr/bin',  '/usr/lib/python39.zip',  '/usr/lib/python3.9',  '/usr/lib/python3.9/lib-dynload',  '/usr/lib/python3.9/site-packages',  '/usr/lib/python3.9/site-packages/odf',  '/usr/lib/python3.9/site-packages/odf',  '/usr/lib/python3.9/site-packages/odf',  '/usr/lib/python3.9/site-packages/odf',  '/usr/lib/python3.9/site-packages/odf',  '/usr/lib/python3.9/site-packages/odf',  '/usr/lib/python3.9/site-packages/odf']
Wed, 01 Dec 2021 15:16:38 +0200

</body>
</html>

**Comment by Michaelpalacce** [comment]
Adding the column manually in postgres fixed this issue

**Comment by cdubz** [comment]
@Michaelpalacce do you have you updated recently? That column was added in the most recent release (v1.9.1) and should be added when you run database migrations after updating.

**Comment by Michaelpalacce** [comment]
I did yes but I did not see this issue before... Which is weird. I am using docker, not really sure how to run migrations.

Would just adding it with a type of boolean be an issue?

**Comment by cdubz** [comment]
Hm I'm not sure the exact method for Docker but essentially you need to run `python manage.py migrate` in the app container somehow. You'll want to do this after any update to ensure you database schema is kept up-to-date for the application.

**Comment by Michaelpalacce** [comment]
Seems simple enough. Thank you for the info, closing
