### ISSUE TITLE
Add ability to export/import data

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#35]
[Suggestion](https://news.ycombinator.com/item?id=15558683) comes from Show HN feedback.

I suspect something already exists for Django that would allow basic import of data from a csv or tab-delimited file. Perhaps that would be useful on its own, initially.

**Comment by cephos** [comment]
Simple import could be done by using the following django project: https://github.com/edcrewe/django-csvimport

**Comment by cdubz** [comment]
[django-import-export](https://github.com/django-import-export/django-import-export) also looks good for this. It would be nice to have simple file-based exports in addition to the API.

A useful import would likely need to include some sort of workflow where a child is created (or imported?) first, and then records for a specific model (e.g. diaper changes, feedings, etc.) would be imported for that child (only).

Importing for multiple children or trying to do some sort of bulk import seems like it would be troublesome given that almost all the models have a relationship to a child. One model for one child at a time would simplify things greatly.
