### ISSUE TITLE
Hardcoded English strings on timeline

### ISSUE THREAD

**Issue by Alberdi** [babybuddy/babybuddy#352]
Just some texts that cannot be translated at the moment:
- [x] [Duration](https://github.com/babybuddy/babybuddy/blob/f643ad7771108cad1c6a585033e3b41752954236/core/templates/timeline/_timeline.html#L38)
- [x] [since previous](https://github.com/babybuddy/babybuddy/blob/f643ad7771108cad1c6a585033e3b41752954236/core/templates/timeline/_timeline.html#L43)
- [x] [Edit](https://github.com/babybuddy/babybuddy/blob/f643ad7771108cad1c6a585033e3b41752954236/core/templates/timeline/_timeline.html#L48)
- [x] [No events](https://github.com/babybuddy/babybuddy/blob/f643ad7771108cad1c6a585033e3b41752954236/core/templates/timeline/_timeline.html#L72)
- [x] [wet](https://github.com/babybuddy/babybuddy/blob/f643ad7771108cad1c6a585033e3b41752954236/core/timeline.py#L154)
- [x] [solid](https://github.com/babybuddy/babybuddy/blob/f643ad7771108cad1c6a585033e3b41752954236/core/timeline.py#L156)

**Comment by cdubz** [comment]
Thanks for reporting. I gotta remember to watch out for those in PRs…
