### ISSUE TITLE
Boolean environmental variables 

### ISSUE THREAD

**Issue by MagiX13** [babybuddy/babybuddy#354]
Hi,

I'm running babybuddy via the linuxserver docker container and failed to turn off the debug mode via environmental variables. Note that the linuxserver docker container sets DEBUG to False if not set, but this is interpreted as a string and thus treated as True.

Some investigation showed that the dotenv package does not support boolean variables, and thus whatever non-empty value the DEBUG env variable takes, it evaluates to True. See this issue: theskumar/python-dotenv#86 for reference
A potential fix could be converting the strings that are supposed to be boolean into a proper boolean, similar to [how it's done for the 24h format](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/base.py#L198), i.e.
`DEBUG = bool(strtobool(os.getenv.get('DEBUG','False')))`

Let me know if you would be willing to accept a pull request on this issue.

**Comment by cdubz** [comment]
@MagiX13  a PR would be great. Thank you!
