### ISSUE TITLE
Issue with timer API for Feeding, Sleep, and Tummy-Time

### ISSUE THREAD

**Issue by dpadGit** [babybuddy/babybuddy#363]
Hi there!

I'm currently running into an issue with the API when trying to convert an active timer into an activity. I created the timer with a Siri Shortcut for Child 1, but it fails to complete when I attempt to turn that timer ID into Feeding, Sleep, or Tummy-Time. I tried to troubleshoot the best that I could before logging this issue. Currently running the latest build/image (v1.9.3) from Linuxserver.io on Docker. Troubleshooting images from Postman are below.

Verify at least one timer was active with GET:
![BB-API-1](https://user-images.githubusercontent.com/61484406/148148204-c90eb2ad-9858-4e5d-8a73-a188adecfa04.png)

Checked OPTIONS to verify that the 'child,' 'start,' and 'end' fields are not required:
![BB-API-2](https://user-images.githubusercontent.com/61484406/148148212-f02877bf-07bc-4996-be42-8c68b253e81a.png)

Attempted a POST with the timer as the only value set:
![BB-API-3](https://user-images.githubusercontent.com/61484406/148148217-0d331018-1982-456e-a809-43f8a3d021bc.png)

**Comment by cdubz** [comment]
Hm yeah I think what you’re doing there should work. I’ll take a look soon.

**Comment by cdubz** [comment]
This appears to be working for me in the demo. Hm...

Here's what I tried:

Request:
```
curl --location --request POST 'http://demo.baby-buddy.net/api/timers/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Token ac1a634c6e61ec033560c3629e0158217afa8692' \
--data-urlencode 'child=1&name=sleep%20timer'
```

Response (`201 Created`):
```
{
    "id": 4,
    "child": 1,
    "name": "sleep timer",
    "start": "2022-01-06T15:09:34.690820Z",
    "end": null,
    "duration": null,
    "active": true,
    "user": 1
}
```

Request:
```
curl --location --request POST 'http://demo.baby-buddy.net/api/sleep/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Token ac1a634c6e61ec033560c3629e0158217afa8692' \
--data-urlencode 'timer=1'
```

Response (`201 Created`): 
```
{
    "id": 161,
    "child": 1,
    "start": "2022-01-06T15:09:34.690820Z",
    "end": "2022-01-06T15:14:24.372809Z",
    "duration": "00:04:49.681989",
    "nap": true,
    "notes": null
}
```

Could you also show the headers you're using for the request?

**Comment by dpadGit** [comment]
Interesting! The only header that I'm using other than auth is "Content-Type: application/json"

I flipped it to the content type you used in your command, and it's still doing the same thing for me. I also started a session on the demo website to rule out any issues with my self-hosted setup and had the same result.

It could be how Postman is handling the request, but what's weird is that it's not working in the Siri Shortcut that I'm attempting to use either. Tracking diaper changes works without a problem, but converting a timer doesn't.

**Comment by cdubz** [comment]
I’m surprised you got the same result on the demo. Could you export and post your queries from Postman so I can try um?

**Comment by dpadGit** [comment]
Absolutely! I saved the attempts against the demo. Let me know if there is anything else I can grab.
[Baby-Buddy.postman_collection.zip](https://github.com/babybuddy/babybuddy/files/7824406/Baby-Buddy.postman_collection.zip)

**Comment by cdubz** [comment]
@dpadGit Ok so it seems the documentation could use a little improving here. You should be able to set `Content-Type: application/json` _if_ you are sending the payload in the body as JSON (e.g., `{"timer": 1}`) but this won't work when passing via parameters. In fact I don't think any of the `POST`/`PATCH` endpoints will use query parameters -- you need to either use the json method or `Content-Type: application/x-www-form-urlencoded` with the parameters in the request _body_.

Could you try importing the [openapi-schema.yml](https://github.com/babybuddy/babybuddy/blob/master/openapi-schema.yml) to Postman and testing from there?
