### ISSUE TITLE
Error during add/edit action for fed and diaper

### ISSUE THREAD

**Issue by nos86** [babybuddy/babybuddy#374]
Hello, 
I recentrly installed this app in my docker server.

When I try to add or edit an entry for fed or diaper change, I receive this error. If I go back to the dashboard however I find the entry.

The error in app is risen at:
>Exception Value:  unsupported format character '!' (0x21) at index 36
Exception Location: /app/babybuddy/core/views.py, line 37, in get_success_message

The invalid character and its position changes every time, so I assume it is not related with the info I add in the entry.

Please find below the complete traceback

> Environment:
Request Method: POST
Request URL: http://192.168.62.4:8000/changes/add/
Django Version: 3.2.7
Python Version: 3.9.5
Installed Applications:
['api',
 'babybuddy',
 'core',
 'dashboard',
 'reports',
 'axes',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'widget_tweaks',
 'easy_thumbnails',
 'storages',
 'import_export',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'babybuddy.middleware.RollingSessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babybuddy.middleware.UserTimezoneMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'axes.middleware.AxesMiddleware']
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/usr/lib/python3.9/site-packages/django/contrib/messages/views.py", line 12, in form_valid
    success_message = self.get_success_message(form.cleaned_data)
  File "/app/babybuddy/core/views.py", line 37, in get_success_message
    return self.success_message % cleaned_data
Exception Type: ValueError at /changes/add/
Exception Value: unsupported format character '!' (0x21) at index 36

**Comment by cdubz** [comment]
Curious. Where does that error show up? And how are you running the app in Docker? With Docker Compose? Could you share whatever config you have for the setup as well?

**Comment by nos86** [comment]
I'm using the customized version for Home Assistant, in order to install BabyBuddy as a component of home assistant.
Repository is https://github.com/OttPeterR/addon-babybuddy
This will create a container in docker.

Regarding the error, it appears when you submit the data using the button at the end of the form

**Comment by cdubz** [comment]
Looking at the area where this is triggered the only thing I can think is that something about the child's name is causing this.

https://github.com/babybuddy/babybuddy/blob/5964eed6010403ad36c1dc18b1a07091cd816204/core/views.py#L30-L37

If you are comfortable doing so, could you also share the child name you are using? If you don't want to share, try changing it to something like first name "Child" and last name "One" (just a string I use in tests a lot) temporarily and see if you still get the issue.

**Comment by nos86** [comment]
His name is Lorenzo and if I change it with Child One, the situation doesn't change because I receive the same error.

**Comment by cdubz** [comment]
Ok. I spent some time earlier trying to reproduce this with no luck. I don’t have an HA setup so can’t really test fully. It may make more sense to raise this issue over in the HA addon repo.

**Comment by nos86** [comment]
I tried to override the entire method with a: 
`return "OK"`
at the start of the method, with no success. So I think the problem is to be searched in the environment. I will try to do additional investigation and may involve the owner of the HA addon repo.

Thank you so much for your availability
