### ISSUE TITLE
Feature suggestion: Add user editable tags to "notes"-sections

### ISSUE THREAD

**Issue by MrApplejuice** [babybuddy/babybuddy#380]
# Problem

We find ourselves using the "notes" function quite a bit for writing taking medical notes or other standard findings that we would like to keep track of. These tend to be single-events like "Took a bath" or similar, so very much fitting into the "notes" category. However, for some of them (medical ones especially), they tend to become _very_ repetitive and cumbersome to type out: "Took vitamins" ... every day... and then often on a phone...

# Suggested solution

Pretty much all of the different pages have the handy "notes" field already:

![grafik](https://user-images.githubusercontent.com/542105/151405464-5e254a75-7698-48fd-90c4-dc5af73f7661.png)

Instead of typing out the note every time, I propose adding another "tags" section (like the labels here on the issues page), that allows quickly adding a tag to the entry - just like a note. But instead of typing, these will be stored in the database and are quickly accessible from the interface with a simple click. See doodle below:

![grafik](https://user-images.githubusercontent.com/542105/151406293-ad22b652-a8ca-490a-b63f-122fe93b8822.png)

(I just realized that adding _these_ tags to a "temperature" entry does not make a lot of sense - picture those tags on the generic "notes" page instead, maybe)

The tags would be stored in a new model in the database and the most recent 10(?) would be offered as a quick-list (most recently used by user, maybe?). Alternatively the (+) can be clicked to create a new tag on-the-fly. Text and color are user-editable. The design would be the "bootstrap pill" or "bootstrap badge" style (https://getbootstrap.com/docs/5.0/components/badge/).

For the database design, I propose adding a new table "tags" to the core-models and then adding a Many-To-Many relation for all items that can contain "Notes" right now to that table.

# Other related issues

I have found #217 which could also be a solution to this issue (create a custom event "took vitamins", "took baby bath"). However, to me it looks like that issue is way more complex to solve migrations and proper database design. This would solve the "single repetitive events" usecase neatly and quickly. In addition, I think that this might also offer utility once #217 is implemented as this feature could be recycled as a means to tag (and therefore index) events across different "types". Seems handy to me, in cases where someone wants to tag "will be done by dad/mom" or something. Point is: Even if #217 is implemented, I think that this offers utility.

-------------------

I would be willing to give this a go as I was thinking of shoehorning this into my Android-app, but then was thinking that proper server support would be even nicer. Before working (wasting) tome on the feature some green-lighting would be nice :-)

**Comment by cdubz** [comment]
I'm all for tagging but it might be fairly complicated on its own.

Check out this page for a quick list of tagging libraries: https://djangopackages.org/grids/g/tagging/

I'm betting the jazzband offering (https://github.com/jazzband/django-taggit) would be a solid choice.

Note that we are stuck on Bootstrap 4 until I can get time to address upgrading from Tempus Dominus 5 to 6 ([currently in beta](https://github.com/Eonasdan/tempus-dominus)) and then sorting out any other necessary BS4 -> BS5 changes.

**Comment by MrApplejuice** [comment]
Hey there! Thanks for the thumbs-up :smile: Also thanks for the project links. I did not do any research for projects that might help here myself. django-taggit seems like a nice choice indeed, it even seems to have the REST-Framework calls sorted out, which I was concerned about!

Anyway, I will draft something over the next few days and post updates over here!
