### ISSUE TITLE
Select list options intermittently invisible when used as a PWA iOS 15+

### ISSUE THREAD

**Issue by ocdtrekkie** [babybuddy/babybuddy#381]
Alright, so I'm still trying to nail down what could cause this. We now have a kid and can now test this app thoroughly! We have Sandstorm added to homescreen, so this would be in iOS Safari, with BabyBuddy in a Sandstorm iframe.

My wife reported she could not add a feeding or diaper change because the dropdowns would not populate and could not be changed from default/null selections. Thought it was weird and saw some artifacts like the dropdowns persisting after leaving the page. I closed the app and reopened it and things worked fine.

I then returned to my own phone, which had worked fine, doing the same thing for a bit, until I once again closed the app.

My best guess so far is that it happens if you had the app open already on Sandstorm and then return to it without closing it in between. It's very possible this could be caused by something like the Sandstorm grain being closed but the app front end not noticing.

**Comment by amorphobia** [comment]
I encountered this issue, too.

I recognize that the bug is on iOS side, but can we have a workaround, use something like [radio toggle buttons](https://getbootstrap.com/docs/5.0/forms/checks-radios/#radio-toggle-buttons) instead of dropdowns?

**Comment by cdubz** [comment]
I’m open to ideas here. I don’t know if radio toggles are really the answer but I’d be happy to test a PR if someone wants to try it out. Keep in mind we are stuck on BS4 due to the datetime picker library so we can’t use BS5 components.

**Comment by cdubz** [comment]
In the mean time someone has created a very detailed bug report for this: https://bugs.webkit.org/show_bug.cgi?id=238318

Hopefully that helps move the issue along 🤞

**Comment by cdubz** [comment]
@ocdtrekkie check out #494! Looks like this approach will help workaround this issue and I like that its not _just_ because of this iOS bug.

**Comment by cdubz** [comment]
This appears to be fixed in iOS 16.2 🎉

**Comment by ocdtrekkie** [comment]
Awesome!
