### ISSUE TITLE
Show type breakdown on feeding_amounts report

### ISSUE THREAD

**Issue by alzyee** [babybuddy/babybuddy#383]
I would like to see the breakdown of various feeding types in the feeding amount report. I don't do much python coding so my code is just a hack to get the thing I wanted as a demo. Ideally it would show only / all the types that have values.

https://github.com/alzyee/babybuddy/commit/34b6ecaf22f84b833cf4a36ebd2aada7e6253fd6

**Comment by cdubz** [comment]
Sounds interesting and the code looks like a good start, if you open a draft PR I can take a closer look in review.

**Comment by alzyee** [comment]
I think I see a route to implement the features I suggested. It seems like I can make an array of dictionaries then into an array of traces which can be passed into the  data attribute of the figure. I will make an effort to get the code functioning as described and make a PR.

* show only / all the types that have values
* breakdown of various feeding types

**Comment by cdubz** [comment]
Closed by #384.
