### ISSUE TITLE
v1.9.0 update to manual timer edit makes mobile UX worse

### ISSUE THREAD

**Issue by yetdog** [babybuddy/babybuddy#385]
When editing a timer, and tapping on the calendar icon, the time box popup tucks in behind the keyboard on iOS and requires vertical scrolling to realign and thus alter the time.

**Comment by cdubz** [comment]
Can you share a screenshot and some device details? This has been a pain in the past but I can't repro right now on my smaller screen iPhone SE 2 with iOS 15 -- the calendar popup stays above the keyboard for me.

**Comment by yetdog** [comment]
Thanks Christopher; sorry for the delay on this. Really appreciate your support. I've attached a couple examples, one for each field (start/finish). It seems the major issue is, even when avoiding tapping on the editable text/time field, and only clicking directly on the calendar icon, the keyboard still comes up and covers part of the interface.

![IMG_4322](https://user-images.githubusercontent.com/6452866/152656521-d5877aa0-59c0-40c1-b6a0-e9bb8a3e1d4b.jpeg)
![IMG_4321](https://user-images.githubusercontent.com/6452866/152656523-39ee3e34-511b-41b2-a8b9-272224352a35.jpeg)

**Comment by cdubz** [comment]
Ok yeah I see it now. This is caused by #284   I do want to keep that functionality so will have to fiddle around to see if we can improve this.

**Comment by cdubz** [comment]
@yetdog fix is in and will be in next release. Thanks for reporting!
