### ISSUE TITLE
Remove/Change Drop-down Options

### ISSUE THREAD

**Issue by netspear** [babybuddy/babybuddy#389]
Is that a way to remove to change the drop down options when you want to add to a child?

Or example, the children watched are older and don't drink breast milk. Can I remove that as an option in the drop down menu under adding a feeding?

**Comment by cdubz** [comment]
Not currently -- #79 is essentially the same request I think. Not something I've had time to investigate but I'd be open to PRs.

**Comment by cdubz** [comment]
Closing this in favor of #79 as a feature request.
