### ISSUE TITLE
Tagging refinements

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#415]
Supplemental tasks following the merge of #414.

- [x] [Fix verbose name of Tags model](https://github.com/babybuddy/babybuddy/commit/1398239ecf54c29a87726e9c5fe42bf06bf15c43)
- [x] [Include random tags and instance tagging in fake data generation process.](https://github.com/babybuddy/babybuddy/commit/5159e97affc483a7d7e1a351eaf94b0d62b30bb1)
- [x] #416
- [x]  [Add single tag filter support to core views](https://github.com/babybuddy/babybuddy/commit/09e08530670f71146fcea2dd46e6d9e0943ff3fb)
- [x] #430 
- [x] [Move tag widget customizations to form classes](https://github.com/babybuddy/babybuddy/commit/379f9b1e867c0b5670b290762460189abc1e2433)
- [x] #429
- [x] [Update OpenAPI schema file with tags endpoint/functionality.](https://github.com/babybuddy/babybuddy/commit/7804fe8f2dfec750a3f8f67f342f049bdbf6b14c)
- [x] #458 (add tags tests)
- [x] [Add latest endpoints to documentation](https://github.com/babybuddy/babybuddy/commit/af5253585e680f262f29e7aefd0e8dbd6d3c0530)
- [x] [Update OpenAPI schema](https://github.com/babybuddy/babybuddy/commit/af8b2cc1bdaa133bf74f77af9135831271acfd70)

CC @MrApplejuice -- just getting this stuff down somewhere. You may already been working on some aspects of this.

**Comment by MrApplejuice** [comment]
Yes sure. Wish I could edit the issue, then I could add a task-link to https://github.com/babybuddy/babybuddy/pull/416.

What does "exporting tags" mean?

**Comment by cdubz** [comment]
Exporting is not well exposed but it is there. If you navigate to the Django admin and load a list view of one of the core models (e.g. Feedings) there is a button available to export the data in various formats.

**Comment by cdubz** [comment]
Closing this up! I broke out #460 as a future enhancement.

**Comment by cdubz** [comment]
Nice! Thanks for bringing the idea and contributing (: This issue ended up being a nice excuse to catch up a bunch of tests, documentation, and API features that had been lagging behind with other recent additions as well so I was glad to work on it.
