### ISSUE TITLE
Diaper change without wet/solid 

### ISSUE THREAD

**Issue by myxor** [babybuddy/babybuddy#426]
For me it makes sense to add a diaper change event without selecting any of _wet_ and _solid_ types.

We sometimes change the diaper for the child to feel more fresh even though nothing is actually in it.

I would like to still keep track of these changes but currently it is not allowed to add such an event without selecting wet and solid state.

**Comment by cdubz** [comment]
I suppose this seems reasonable enough. Tracking "diaper changes" is really meant more as a proxy for tracking the baby's bodily functions but that doesn't necessarily mean we have to enforce in this way. I'm open to PRs for this but be aware that there may be assumptions made throughout the app about the presence of those fields beyond just there required-ness in the model.
