### ISSUE TITLE
Feature request: Support for tea and water as feeding type

### ISSUE THREAD

**Issue by myxor** [babybuddy/babybuddy#432]
Feature request: Support for tea and water as feeding type.

Or are these supposed to be logged as "formula"?

**Comment by ocdtrekkie** [comment]
I've definitely noticed it was a challenge to mark things that weren't formula in here. Pedialite, cereal, etc. It looks like the tagging feature has landed... so maybe this is addressed in the latest now? (Would spinning a Sandstorm package for this be a lot of trouble?)

**Comment by cdubz** [comment]
@ocdtrekkie v5 is submitted! I didn't test upgrade path so... tread carefully (:

**Comment by ocdtrekkie** [comment]
Thanks! I will upgrade a backup grain first.
