### ISSUE TITLE
Sleep Pattern giving 500 Internal Server Error

### ISSUE THREAD

**Issue by kazzaw** [babybuddy/babybuddy#440]
Probably goes back a couple updates now, but the wife has reported that attempting to access the Sleep Pattern gives a 500 Internal Server Error

**Comment by cdubz** [comment]
This most likely #174 -- you can get a little more info if you set the `DEBUG` environment variable to something truthy and hit the page again.

**Comment by kazzaw** [comment]
Hi, yes, appears to be that issue according to logs.

Probably could correlate to DST ending here, I've probably only been using BB since DST was active. 

For reference 

`KeyError at /children/frankie-baby/reports/sleep/pattern/

'2022-04-16'

Request Method: 	GET
Request URL: 	https://baby.domain.id.au/children/frankie-baby/reports/sleep/pattern/
Django Version: 	4.0.2
Exception Type: 	KeyError
Exception Value: 	

'2022-04-16'

Exception Location: 	/app/babybuddy/reports/graphs/sleep_pattern.py, line 194, in _add_adjustment
Python Executable: 	/usr/bin/python3
Python Version: 	3.9.5
Python Path: 	

['/app/babybuddy',
 '/usr/bin',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/usr/lib/python3.9/site-packages',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf',
 '/usr/lib/python3.9/site-packages/odf']

Server time: 	Sat, 16 Apr 2022 11:17:57 +1000`

**Comment by cdubz** [comment]
Yeah sorry. Some damn day I will deal with #174... :goberserk:

**Comment by cdubz** [comment]
This was fixed by #445 in v1.11.0 🎉
