### ISSUE TITLE
Can't filter notes by capitalized tags

### ISSUE THREAD

**Issue by Alberdi** [babybuddy/babybuddy#467]
I want to thank everyone involved in the new tag support; it's very useful!

When I try to filter the "Notes" by tag it doesn't find any:
https://user-images.githubusercontent.com/1556349/171914065-0a6f5462-7dda-4088-9ecb-e0748f75b706.mov

**Comment by cdubz** [comment]
Interesting. I can't reproduce this in the [demo](https://demo.baby-buddy.net/). Does the filtering work for tags in other entry types?

**Comment by Alberdi** [comment]
It only seems to happen when the tag has the first letter capitalized! Also in other entry types.

**Comment by Alberdi** [comment]
I guess it happens when the name of the tag doesn't match the internal slug. Maybe related to this: https://github.com/babybuddy/babybuddy/blob/379f9b1e867c0b5670b290762460189abc1e2433/core/filters.py#L10

**Comment by cdubz** [comment]
Nice — thanks for figuring that out. I can reproduce as well.
