### ISSUE TITLE
"Recently used" shouldn't appear if no tags were recently used

### ISSUE THREAD

**Issue by Alberdi** [babybuddy/babybuddy#470]
It looks a bit strange if there are no tags:
<img width="781" alt="Screenshot 2022-06-03 at 20 06 13" src="https://user-images.githubusercontent.com/1556349/171921438-2e8559bf-7780-486f-96d5-30c21590e489.png">

Also, the text below could change to reflect that state.

**Comment by cdubz** [comment]
This could be pretty easily achieved by wrapping the "recently used" container in a conditional but the field description ("Click on the tags to add [...]") is actually a little tougher. There's not really an existing pattern for including/excluding that and the field display logic is very generic.

Relevant places to hack on this --

- https://github.com/babybuddy/babybuddy/blob/master/core/templates/core/widget_tag_editor.html#L27
- https://github.com/babybuddy/babybuddy/blob/master/babybuddy/templates/babybuddy/form_field.html#L44

**Comment by earthcomfy** [comment]
Hi, @cdubz I was also checking this out and I have found a solution not just to hide the recently used container, but also the "Click on the tags to add [...]"). I did the latter using this:point_down: CSS trick and it works.

```
<style>
    {% if not widget.tag_suggestions.quick %}
        .help-block{
            display: none;
        }
    {%endif%}
</style>
```
Let me know if this approach is acceptable to you. I can then take the issue and submit a PR.

Thanks

**Comment by earthcomfy** [comment]
Okay, I will see if I can find a cleaner solution.
