### ISSUE TITLE
Handle plurals with `count` tag of `blocktrans`

### ISSUE THREAD

**Issue by amorphobia** [babybuddy/babybuddy#472]
Currently, several plurals are generated with `pluralize` filter. I found it wired when translating to Chinese.

Usually, nouns do not have plural forms in Chinese, and the `%(plural)s` term will append an extra "s". However, if I delete `%(plural)s` in the `msgstr`, it would not pass the checker and leave original English message there.

Instead, if `count` tag is used, it can be solved by only translate `msgstr[0]`. I made a [commit in my forked repo](https://github.com/amorphobia/babybuddy/commit/568a0b1ff0a5b0cc4cebbcbcabd497c48580c48a). But this may break all other translations, so I did not open new PR. If you think it make sense, I will open one.

**Comment by cdubz** [comment]
Interested -- I didn't know about the `count` tag. This does look like a better solution and I'd take PR for it. Breaking other translations is unfortunate but I think it's worth using this as a better approach anyway.

**Comment by cdubz** [comment]
#473 is merged. Thanks for contributing!
