### ISSUE TITLE
Improve asset minification

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#492]
### Discussed in https://github.com/babybuddy/babybuddy/discussions/491

<div type='discussions-op-text'>

<sup>Originally posted by **gbballpack** June 28, 2022</sup>
Using Cloudflare with Baby Buddy, Baby Buddy running inside of Docker with an external reverse proxy, Cloudflare is able to minify about 80 KiB from the vendor JS file.

Would it be possible to have everyone run a minified vendor JS file? Minified files generally run quicker and can reduce power consumption when on mobile compared to non-minified JS files.

I am curious if it is possible to share the benefits of the minified JS with those not using Cloudflare?

Before and after screenshots are attached, using https://web.dev/measure to verify the Cloudflare JS minification.
![IMG_1425](https://user-images.githubusercontent.com/39963341/176254529-3fe168c2-6552-4fcb-b0b9-c8ad65b039a3.jpg)
![IMG_1426](https://user-images.githubusercontent.com/39963341/176254561-8fdb094a-c5db-4025-ab60-f67a0a91351d.jpg)</div>

**Comment by mikejgray** [comment]
Would you still like help on this?

**Comment by cdubz** [comment]
Yes for sure!
