### ISSUE TITLE
One user does not see the "Pumping entry" menu, the other one does

### ISSUE THREAD

**Issue by farfade** [babybuddy/babybuddy#493]
Hello,

First of all, thank you for this great app :)

With 1.11.2,  I've got a setup with two users.

Everything works correctly, excepting that one user sees the menu list "pumping entry" whereas the other does not.

Promoting the user as staff user does not have any impact.
Changing the locale does not have any impact.

Any idea ?

Cheers,

farfade

**Comment by farfade** [comment]
Could it be related to permissions problem in [babybuddy/templates/babybuddy/nav-dropdown.html](url) ?

```
{% if perms.core.add_pumping %}
                        <a class="dropdown-item p-2" href="{% url 'core:pumping-add' %}">
                            <i class="icon-pumping" aria-hidden="true"></i>
                            {% trans "Pumping" %}
                        </a>
                    {% endif %}
```

But how to grant such permissions ?

**Comment by cdubz** [comment]
Hmmm I haven’t worked in permissions in a while but I’m pretty sure that’s unintentional. I’m reopening this as a bug and will take a look at it.

**Comment by cdubz** [comment]
I'm not able to reproduce this -- creating a user via the interface the user has all the correct default permissions (i.e., you shouldn't need to grant any additional ones). Feel free to reopen this ticket if you come with steps to reproduce.
