### ISSUE TITLE
Fix for Django Framework SQL Injection vulnerability

### ISSUE THREAD

**Issue by gbballpack** [babybuddy/babybuddy#496]
According to the advisory, "Trunc() and Extract() database functions were subject to SQL injection if untrusted data was used as a kind/lookup_name value."

At a quick glance at the code, I could not find Trunc() or Extract() database functions called directly, but I am admittedly not all that familiar with the Django Framework. From my understanding, even if Baby Buddy is subject to this SQL injection, it appears it should only be theoretically possible for authenticated users to launch an SQL injection.

Changing the Python Django dependency to 4.0.6 should completely mitigate the Trunc() and Extract() SQL injection, as described in the advisory.

[https://www.bleepingcomputer.com/news/security/django-fixes-sql-injection-vulnerability-in-new-releases/](https://www.bleepingcomputer.com/news/security/django-fixes-sql-injection-vulnerability-in-new-releases/)

**Comment by cdubz** [comment]
Thanks for the note. This is addressed in the latest round of dependency updates (see https://github.com/babybuddy/babybuddy/commit/a51dbf370e3e4a710bf639c20ce3dc2d4c16cd6e).
