### ISSUE TITLE
DateTime fields don't load the current values or fail to validate in some languages

### ISSUE THREAD

**Issue by MiguelCosta** [babybuddy/babybuddy#498]
Hi,

Every time I need to edit an entry or create a new one, the DateTime fields are always empty when I'm using the Portuguese language. If I switch to English the problem does not occurs. 

Can you help?

Screen recorder:
https://photos.app.goo.gl/A1bMnKrregQTUNii9

**Comment by cdubz** [comment]
Thanks for reporting and for the video. I can reproduce in the demo and it doesn't seem to be an issue for other locales. Will take a look when I can.

**Comment by MiguelCosta** [comment]
Sorry, the version 1.12.0 doesn't resolve the bug ☹️ 

Can you reopen the issue? 

![BabyBuddy](https://user-images.githubusercontent.com/645482/182035828-1159a2ec-0dc9-4c1b-881c-d655bd51e8b6.gif)

**Comment by cdubz** [comment]
@MiguelCosta this will be in the v1.12.1 release. I'll make that one in the next week or so -- just one other thing I want to track down before I do.

**Comment by cdubz** [comment]
If you're curious to confirm the fix the change is in the demo instance if you want to test there: http://demo.baby-buddy.net/

**Comment by MiguelCosta** [comment]
Thanks!!!

The demo (http://demo.baby-buddy.net/) is working correctly 💪 
I will wait for the next release. 

Good job 💪

**Comment by orcunkutlu** [comment]
i have date time problem with turkish language. cant submit any from with required date/time.

**Comment by cdubz** [comment]
Argh. Thanks for reporting, @orcunkutlu. I can reproduce this issue in the demo instance. I will try to work on this and #532 in the bear future. Increasingly it's seeming like #335 and #337 are doing to need to be re-evaluated or rolled back. #483 is also related somehow.

**Comment by orcunkutlu** [comment]
Hi,
Forgot upload pic for problem.

English date/time / UTC
![english](https://user-images.githubusercontent.com/3457734/213687155-216a2510-f4e9-48f9-bbcb-c894866e0950.jpg)

Turkish date/time / Europe/Istanbul
![turkish](https://user-images.githubusercontent.com/3457734/213687295-8d1de587-631f-45c2-a9aa-6a83f24f3dc3.jpg)

Date format problem.
