### ISSUE TITLE
"Child" dropdown intermittently not accessible when used in PWA mode on iOS

### ISSUE THREAD

**Issue by HarmlessSaucer** [babybuddy/babybuddy#501]
When using Baby Buddy in PWA mode on iOS, the "Child" dropdown is intermittently not accessible.

Example process:
- Press the icon to quick start a timer.
- Press the edit button.
- Tap on the "Child" dropdown.

At this point, every few times, nothing happens in response.  All other elements on the page respond as expected.
If you swipe up on the iOS device to get into multi tasking then close the "app" and re-open (performing the same steps), the issue is resolved.  
If you simply swipe up (but keep the app open) or navigate to another page in the app and then come back - the issue persists.

Baby Buddy Version: 1.11.2
Installed via Docker-compose on Ubuntu 22.04 Server.
Behind NGINX Proxy Manager to enable HTTPS.

Replicated issue on:
- iOS 16 Developer Beta - iPad Pro (2020)
- iOS 16 Public Beta - iPhone 12
- 2x iOS 15.6 iPhone 12 mini and iPhone XR
- 1x iOS 15.5 iPhone 12

**Comment by ShaneK** [comment]
This is a [known issue with iOS](https://github.com/babybuddy/babybuddy/issues/381)

**Comment by HarmlessSaucer** [comment]
> This is a known issue with iOS [and there's already a bug report for it for babbybuddy](https://github.com/babybuddy/babybuddy/issues/381)

Damn.  Apologies!  I just spent a few mins going through the issues, but obviously my search terms weren't good enough and I missed this! 🤦 Thanks!

**Comment by cdubz** [comment]
#494 will be a convenient workaround for this issue. I’ll try to get a new version out with that one today or tomorrow.
