### ISSUE TITLE
Nap vs sleep

### ISSUE THREAD

**Issue by lukyjay** [babybuddy/babybuddy#503]
Hi

Some of my sleep entries are being recorded as 'naps' and others as 'sleep'. It seems to depend on whether it comes from the Home Assistant addon or directly from BabyBuddy interface. Neither of these interfaces offer the option of selecting nap vs sleep as far as I can see.

The nap function appears to be pointless. What is the difference between nap and sleep?

My suggestion is to remove the nap function and only track sleep. If needed on the frontend, perhaps naps could be defined based on time of day or duration of sleep.

Any clarification would be appreciated :)

Thank you

**Comment by cdubz** [comment]
Nap classification is based on the [`NAP_START_MIN`](https://docs.baby-buddy.net/setup/configuration/#nap_start_min) and [`NAP_START_MAX`](https://docs.baby-buddy.net/setup/configuration/#nap_start_max) settings for the app. #325 made the classification in to a field and there was meant to be a follow-up PR to make it togglable by the user but that work never happened.

If you look in to you'll find there is information and recommendations about number and length of naps specifically (in addition to sleep overall) based on age that may be of interest to some parents ([example article](https://www.thebump.com/a/how-many-naps-do-babies-need)).

For our part back when we used the app we received a chart with information about naps and sleep from the hospital so we used Baby Buddy to compare and sometimes inform our own decisions about, e.g., when to put a child down for a nap.

Different parents will of course have differing opinions about the relevance or usefulness of this information but my philosophy for Baby Buddy has always been to try to support as many caregivers as possible (with a sometimes not so vigilant eye on potential bloat).

Hope that clarifies a bit about why the configuration is the way it is currently.

**Comment by lukyjay** [comment]
I agree naps are important and see the why every parent should know about them. I raised this issue to question the need for a seperate 'nap' function in BabyBuddy, and if it is needed, to raise some concerns on how it is currently implemented.

I'd be happy to track my naps as 'sleep' and will know that they are naps via their shorter duration.

To summarise some defects for the 'nap' implementation:

1. Sleep entries appear to default as 'naps' if there is no nap data provided (e.g. the Home Assistant addon doesn't provide any data on whether nap is 'true' or 'false', so BabyBuddy defaults all sleep entries to true (shouldn't nulls always default to false?))
2. No information in the BabyBuddy documentation on the 'nap' feature
3. No way to toggle whether sleep is a nap or sleep via the BabyBuddy timer interface
2. No way to edit past sleep as a nap vs sleep via the BabyBuddy sleep screen
4. No way to edit the 'nap' column on entries using the BabyBuddy database admin interface
5. The dashboard duplicates sleep data in both the 'sleep' and 'nap' widgets
6. (external issue) Home Assistant Addon doesn't offer this option (https://github.com/jcgoette/baby_buddy_homeassistant/issues/49)

Appreciate your support and love this software :) I have a 5 week old and this has made our lives so much easier! It's also helped with our medical appointments since we have data to show sleep and feeding patterns. I am very greatful for the work the volunteers put into this software.

**Comment by lukyjay** [comment]
Pending #504 being successful, outstanding suggestions from this issue:

1. Sleep entries appear to default as 'naps' if there is no nap data provided (e.g. the Home Assistant addon doesn't provide any data on whether nap is 'true' or 'false', so BabyBuddy defaults all sleep entries to true (shouldn't nulls always default to false?))
2. No information in the BabyBuddy documentation on the 'nap' feature
3. ~~No way to toggle whether sleep is a nap or sleep via the BabyBuddy timer interface~~
4. ~~No way to edit past sleep as a nap vs sleep via the BabyBuddy sleep screen~~
5. ~~No way to edit the 'nap' column on entries using the BabyBuddy database admin interface~~
6. The dashboard duplicates sleep data in both the 'sleep' and 'nap' widgets
7. (external issue) Home Assistant Addon doesn't offer this option (https://github.com/jcgoette/baby_buddy_homeassistant/issues/49)

**Comment by cdubz** [comment]
@lukyjay thanks for the PR -- the changes needed here are a bit more complicated (see my review in #504) so let me know if you are interesting in continuing work on the PR. If not someone else may want to pick it up or I will get to it eventually. I do think this worth addressing.

**Comment by lukyjay** [comment]
>@lukyjay thanks for the PR -- the changes needed here are a bit more complicated (see my review in https://github.com/babybuddy/babybuddy/pull/504) so let me know if you are interesting in continuing work on the PR. If not someone else may want to pick it up or I will get to it eventually. I do think this worth addressing. 

I'm struggling for time with the newborn at the moment and that's not something I can complete without spending more time learning. I will make a donation to the project through Github instead, hopefully it can compensate for the hard work you've done so far and help you work on this. Thanks again for everything.

**Comment by cdubz** [comment]
Closing in favor of tracking in #513.
