### ISSUE TITLE
Enhancement: Feeding method - add "nanny fed"

### ISSUE THREAD

**Issue by bsaurusrex** [babybuddy/babybuddy#507]
Enhancement: It would be nice to add another Feeding method option : "Nanny fed"

**Comment by cdubz** [comment]
I have resisted adding too many items to list for the most part. One thing you could do is use tagging to track this. Would that serve your use case?

**Comment by ahgray** [comment]
I've been using tags with Bottle Fed, and it seems to do everything I want, allows me to filter etc to see how the Grandparents/Babysitter whoever did.
