### ISSUE TITLE
Make nap user toggleable

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#513]
*Steps reworked from #504*

- [x] Remove the calculated `core.models.Sleep.nap` property entirely.
- [x] Create migration to add a true `nap` field to the `Sleep` model.
  - [x] Update existing data based on `NAP_START_MIN` and `NAP_START_MAX`.
  - [x] Remove `napping` field.
- [x] Remove `core.models.NapsManager`.
- [x] Update `core/templates/core/sleep_list.html` to use new `nap` property.
- [x] Create new **application level setting** (feature TBD) for default nap start min/max.
  - [x]  Set initial values to `NAP_START_MIN` and `NAP_START_MAX`  environment variables.
  - [x] Find and refactor any usages of the `NAP_START_MIN` and `NAP_START_MAX`  environment variables to use new application level setting.
- [x] Add a new method to `core.forms.SleepForm` to evaluate  nap start min/max setting and pre-select (or not) the nap checkbox in the form.
- [x] Update documentation
- [x] Update existing tests
- [x] Add tests
- [x] Re-evaluate whether `Sleep.nap` can be non-nullable without a default.

This issue supersedes #504, #503, and #323 for tracking this issue.

**Comment by tango2590** [comment]
Has any progress been made with this? If there is no way to control to why some entries are considered "naps" and others aren't, it should just be removed from the UI until a working toggle or separate nap tracking is implemented to clean up the UI.
