### ISSUE TITLE
Ver 1.12.1 regression - date is reversed with en_gb locale 

### ISSUE THREAD

**Issue by paradox00** [babybuddy/babybuddy#516]
Hi,
With latest update, some of the date forms (like in start timer or add note) initializing the time form with date in reversed format.
Instead of "04/08/2022" is shows "08/04/2022".

From quick debugging is looks related to #505.

Thanks,
Aviv

**Comment by cdubz** [comment]
What locale are you using?

**Comment by paradox00** [comment]
en_gb

**Comment by cdubz** [comment]
Ok yeah confirmed this causes issues with most locales. Grrr. Reverting now and will cut a new release. Thanks for reporting!

**Comment by cdubz** [comment]
Fixed by https://github.com/babybuddy/babybuddy/commit/5a257f5b11b259812bfab3fcff03122138edeb2c

**Comment by cdubz** [comment]
Also I just noticed you gave the locale in the issue title 😆 Sorry for the redundant follow up!

**Comment by paradox00** [comment]
Thank you for the quick fix!
