### ISSUE TITLE
Allow REMOTE_USER authentication 

### ISSUE THREAD

**Issue by EnsuingRequiem** [babybuddy/babybuddy#517]
I'd like to see the RemoteUserMiddleware and RemoteUserBackend be able to be added via environment variable similar to how Tandoor Recipes implemented it (https://github.com/TandoorRecipes/recipes/commit/55777fd948e1fb18683ac833ba72cdc78c95ec75) in order to allow for forward-authentication/sso when setup behind a reverse proxy.

**Comment by cdubz** [comment]
Should be doable! Happy to take PRs or I’ll take a look at this eventually.

**Comment by EnsuingRequiem** [comment]
Cool! Since I have a bit of a guide to work from, I'll see if I can put together a PR. I should probably make sure that I have it working properly on my Tandoor container to have a comparison.
