### ISSUE TITLE
Data mismatch

### ISSUE THREAD

**Issue by matthieu-kr** [babybuddy/babybuddy#520]
There is a discrepancy in the way feeding data is reported on the dashboard vs the graphs, which sometimes causes them to report different values.
![Data](https://user-images.githubusercontent.com/34589622/184425789-cc375b48-871b-420c-bbd0-ff5040977d8f.jpg)

Looking at the data, it appears the dashboard uses the feeding start time to sum the total. The graphs appear to be using the end times.
![DB](https://user-images.githubusercontent.com/34589622/184425963-2085b7d1-baf6-4527-9e6d-3ffea8ab104b.jpg)

**Comment by cdubz** [comment]
Nice catch! Not sure there is a "right" way here. I think I'd lean towards using end date over start date. Happy to PRs to get these in line.

**Comment by matthieu-kr** [comment]
The end dates make sense to me as well. 

I don't know if it's related, but I think the time between feedings on the dashboard should continue to be calculated from the start.

**Comment by cdubz** [comment]
> I don't know if it's related, but I think the time between feedings on the dashboard should continue to be calculated from the start.

Yeah I believe there is a reason for that... I don't recall it, hah, but I think that's generally what medical professionals ask for when this information needs to be tracked.

**Comment by cdubz** [comment]
Fixed by #527
