### ISSUE TITLE
French translations updated on POEditor

### ISSUE THREAD

**Issue by moonpyk** [babybuddy/babybuddy#521]
Hi,

I made a big pass on the French translation to fix some mistakes and correctness issues. babybuddy should sound more "French" now.

This small issue is also an occasion for me to thank the whole dev team, me and my wife are using it since day 3 of the life our newborn son, this app is a gift to us.

Have a wonderful day

**Comment by cdubz** [comment]
Thanks for updates! Glad to hear Baby Buddy is helping you out 😄

**Comment by HydrelioxGitHub** [comment]
I just want to thanks for the French upgrade. 👍🇫🇷

**Comment by moonpyk** [comment]
@HydrelioxGitHub you're welcome, take care of you and your loved ones <3
