### ISSUE TITLE
Feeding via API returns 400

### ISSUE THREAD

**Issue by dillwishlist** [babybuddy/babybuddy#522]
Hello,

I'm attempting to add a feeding via the API (though Bitfocus Companion).  I got everything working for a diaper change, so I know the basic connection is correct.  I am unable to get the feeding to work though.  Does anyone see my error?

```
URL: https://url.tld/api/feedings/

JSON: { "child":"1", "method": "$(internal:custom_feedMethod)", "type": "$(internal:custom_feedType)", "amount": "$(internal:custom_feedQty)" }

Header: {"authorization": "Token abc123"}

Returns:
172.17.0.4 - - [16/Aug/2022:12:55:46 +0000] "POST /api/feedings/ HTTP/1.1" 400 71 "-" "-"
```

Thanks

**Comment by cdubz** [comment]
@dillwishlist If you look at the response body you should get a more detail error. In this case, when I test this on the demo I get:

```json
{
    "method": [
        "This field is required."
    ]
}
```

However if you add the `method`, you'll also hit:

```json
{
    "start": [
        "This field is required."
    ],
    "end": [
        "This field is required."
    ]
}
```

Here's a full example payload that I just tested successfully against the demo instance:

```shell
curl --location --request POST 'http://demo.baby-buddy.net/api/feedings/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Token 39a178af0e317bfe25a82551ed71f2763579e340' \
--data-urlencode 'type=fortified breast milk' \
--data-urlencode 'method=self fed' \
--data-urlencode 'child=1' \
--data-urlencode 'start=2022-08-16T23:19:30.583Z' \
--data-urlencode 'end=2022-08-16T23:30:30.583Z' \
--data-urlencode 'amount=23'
```

**Comment by dillwishlist** [comment]
Thank you for the info.  It's allowed me to get much further, though I'm still struggling since both the source (companion) and the destination (babybuddy) don't have good debug logging.  So I have to use NC and curl to intercept and forward the request.

I've gotten to the point where I can send a manually crafted request successfully, but the same request doesn't work through companion.  Do you have any thoughts based off the info/screenshots below?

Thanks again,

Successful via curl:
```
curl --header "Content-Type: application/json" \
--header 'Authorization: Token 3319b238fae272b73577e1aed9da4a65635ddce5' \
--request POST \
--data '{"child":"1","method":"both breasts","type":"solid food","amount":"70","start":"2022-08-19T07:54:09","end":"2022-08-19T07:54:19"}' \
http://demo.baby-buddy.net/api/feedings/

{"id":164,"child":1,"start":"2022-08-19T07:54:09Z","end":"2022-08-19T07:54:19Z","duration":"00:00:10","type":"solid food","method":"both breasts","amount":70.0,"notes":null,"tags":[]}
```

Unsuccessful - captured by nc:
```
POST /api/feedings/ HTTP/1.1
Content-Type: application/json
authorization: Token 3319b238fae272b73577e1aed9da4a65635ddce5
Content-Length: 129
Host: 127.0.01
Connection: close

{"child":"1","method":"both breasts","type":"solid food","amount":"70","start":"2022-08-19T08:03:38","end":"2022-08-19T08:05:28"}

```

**Comment by cdubz** [comment]
Hmmm. Have you tried repeating the exact request that nc gives you? And what is “companion”?

**Comment by cdubz** [comment]
One thing I notice in the nc output — it looks like the host is wrong?

```
Host: 127.0.01
```

If you mean to use local host it should be `127.0.0.1`

**Comment by dillwishlist** [comment]
Companion is Bitfocus Companion.  Allows you to use an Elgato Stream Deck with custom buttons to trigger actions.  I'm making an easy to use button panel so we can click it rather than getting out our phones.

https://bitfocus.io/companion/

The host should be localhost, that was a typo on my part.  I would test against the demo or my install, then if it failed I would resend it to 127.0.0.1 and capture with Nc to see what the message was.  I would then retransmit with CURL to the babybuddy instance.  The Companion-BabyBuddy connection would fail, but the Curl-BabyBuddy message using the captured message would succeed.  I'm happy to make a video if that would be useful.

Thanks!

**Comment by cdubz** [comment]
Hm yeah I’m a little confused. A video would probably be very helpful 👍

**Comment by cdubz** [comment]
@dillwishlist just out of curiosity I poked around with the Companion application to test this out myself. I was able to make successful a `POST` to the demo instance for a diaper change, for example. Here's the (abbreviated) export that worked for me --

```json
{
  "version": 2,
  "type": "page",
  "config": {
    "1": {
      "style": "png",
      "text": "Diaper Change",
      "size": "auto",
      "alignment": "center:center",
      "pngalignment": "center:center",
      "color": 16777215,
      "bgcolor": 0,
      "latch": false,
      "relative_delay": false,
      "show_topbar": false
    }
  },
  "instances": {
    "zWVu3_wYG": {
      "instance_type": "generic-http",
      "product": "HTTP Requests",
      "label": "Baby Buddy",
      "_configIdx": 1,
      "rejectUnauthorized": false,
      "prefix": "http://demo.baby-buddy.net/api/"
    }
  },
  "actions": {
    "1": [
      {
        "id": "j9WSbHxOV",
        "label": "zWVu3_wYG:post",
        "instance": "zWVu3_wYG",
        "action": "post",
        "options": {
          "url": "changes/",
          "body": "{\"child\": 1, \"wet\": true, \"solid\": false}",
          "header": "{\"Authorization\": \"Token a0ee65d9e572f8463f30fabb6ebc2028cf0644cf\"}",
          "contenttype": "application/json"
        },
        "delay": 0
      }
    ]
  },
  "release_actions": {
    "1": []
  },
  "feedbacks": {
    "1": []
  },
  "page": {
    "name": "PAGE"
  }
}
```

**Comment by dillwishlist** [comment]
I have success with diaper changes, but not with feedings.  Here are my exports in Gists.

Diaper change:
https://gist.github.com/dillwishlist/d1f17fba8d67508492e8430cf32fdd9d

Feeding:
https://gist.github.com/dillwishlist/db2ca3421bcc07d255a23d9d70d8c967


And a video of what I'm doing.  I changed my token after I recorded this to be safe, don't worry!
https://www.youtube.com/watch?v=sQw2rmHh9Ko

**Comment by cdubz** [comment]
@dillwishlist OK interesting... I imported your Feeding export in to my Companion, added the relevant variables (apparently they aren't part of the export) and was able to submit successfully (as long I set the `feedStartDate` and `feedStartTime` manually... I'm unclear on how those are meant to get set). I tested both on a local instance and to the demo.

It's frustrating that there doesn't seem to be a way to capture the response from the API request. I noticed the "internal: Set custom variable from a stored JSONresult via a JSONpath expression" action but couldn't figure out how to use it (or if it is even relevant hah).

It would be very helpful if we could find some way to capture and store the response body because it will contain more detailed error information.

**Comment by dillwishlist** [comment]
@cdubz Agreed.  Those start variables are set via the button on the first page which I didn't think to export.  It takes the date (gmt) and time (local) and concatenation them together into the custom variable.  Then the submit one does the same thing for the end custom variable.  I pointed the URL to local host and captured via 'nc -l 80' to see what the body is.  If I send that via curl, it works.  Hence my confusion!  I already have a bug open Anthony companion about the time zone inconsistency, I'll do some more digging to see if I can enable some debug output or something.

Thanks!

**Comment by dillwishlist** [comment]
Is there a way to put babybuddy in a debug mode so it logs all input to a file we can inspect?

**Comment by cdubz** [comment]
No there is nothing like that I am aware of.

I’m betting this has something to do with the date and time values. What time zone do you have configured for each of the instances you’re testing with?

**Comment by dillwishlist** [comment]
I have US Eastern set on my personal computer.  The server host is set to EDT as well.  Babybuddy is running in docker, I didn't set any time zone in the config there.  Is there somewhere to set that globally?  I set it on my user account.

**Comment by cdubz** [comment]
So there is the [`TIME_ZONE`](http://docs.baby-buddy.net/configuration/application/#time_zone)  environment variable for setting the default TZ. It’s something I want to get rid of in a 2.x release. Anyway it may be causing an issue here? I’m actually unsure how it plays in to the date and time data sent to the API…

**Comment by dillwishlist** [comment]
That does seem to have helped.  The date command now returns the same value on the container, host, and laptop.  Using the companion emulator seems to reliably submit values to BabuBuddy.  I'll test out and confirm with my stream deck when I get home this afternoon!

**Comment by dillwishlist** [comment]
I ended up setting both the TZ and TIME_ZONE variables to be America/New_York to get things to work.

**Comment by cdubz** [comment]
To be clear -- setting both the TZ and TIME_ZONE on the Baby Buddy Docker instance? I suppose one sets the system TZ and the other is what Baby Buddy looks at. Hmmmm. I really hate time zones lol.

**Comment by dillwishlist** [comment]
Yes that's correct.  I'm setting both.

So it turns out this was a multi part issue, all related to time.  Setting the time zone fixed several things.  I was still getting the 400 though.  It turns out the culprit was my Linode wasn't running NTP so was off by a few seconds.  This would cause the "can't be in the future" error.  Now that we're in the right timezone and synchronized down to the second we're in business.

I do wonder though, would it be possible to have BabyBuddy set the timestamp to the current time if not specified by the API?  That would solve this case in the future.

Thanks!

**Comment by cdubz** [comment]
It does default to "now" does models that just have a `time` but it does not do any defaulting for those with a `start` and `end`. I could see maybe default for `end` but `start` would still need to be supplied.

**Comment by dillwishlist** [comment]
Understood, but both `start` and `end` default to "now" in the web interface...

**Comment by cdubz** [comment]
Ah yeah that's true. A relatively recent change. I think the API is probably behind on a couple of different defaults that have changed over time 😬

**Comment by dillwishlist** [comment]
Great project, it's helping my wife and I a ton.  We appreciate all your hard work a ton!  Thanks!
