### ISSUE TITLE
Pumping graph entries do not line up with totals (time zone issue?)

### ISSUE THREAD

**Issue by dillwishlist** [babybuddy/babybuddy#523]
Hello,

On the Pumping graph specifically, the 8th entry is invisible even though the daily total is correct.![image](https://user-images.githubusercontent.com/31589434/186697389-835f5bbf-980f-49b3-a6a2-bc53b5fa57bb.png)

**Comment by dillwishlist** [comment]
![image](https://user-images.githubusercontent.com/31589434/186697877-f4214e42-771c-4560-8f41-efd2758655b0.png)

**Comment by cdubz** [comment]
@dillwishlist can you clarify what you mean by the "8th entry"?

**Comment by dillwishlist** [comment]
The graph colors the 7th pump per day pink.  The 8th doesn't show up, or is the same color as the background.  For instance the Aug 24th at 11:40 entry of 45 ml is calculated on the daily total from the graph but isn't colored.

**Comment by cdubz** [comment]
@dillwishlist Ok I see now. And the first entry for 24 Aug also appears to be from the day before. I'm guessing there is some time zone handling issue with the graph for determining which entries to include.

**Comment by dillwishlist** [comment]
Oh that makes sense!  Let me know if there's anything you want me to do testing wise.

**Comment by garyglatfelter** [comment]
I've been playing around with this for a little bit. It does not appear to me to be a time zone thing.

![graph_data1](https://user-images.githubusercontent.com/51980155/196002805-30de14d1-eca5-453c-9fe4-4ddcd1bfdb73.png)
![graph_data2](https://user-images.githubusercontent.com/51980155/196002811-51c73f1f-3361-4ef9-8488-70fcb9f4f0ca.png)
![graph_report](https://user-images.githubusercontent.com/51980155/196002815-42bd2dce-d6a0-4c08-9b40-86a756411dc9.png)
It's hard to see all the numbers on the graph, but it does include all points for Oct13th including the 11:59pm entry of quantity 50( 40+20+30+50+100+15+50).
However, as soon as 8 or more feeding entries are recorded within the same day, the very last feeding won't be included in the bar graph. 

Totals still add up correctly. I'm not sure why that is yet. I can try to fix it. If that would be ok, any ideas where I should start?
