### ISSUE TITLE
Create a user add management command

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#528]
Somehow all 3 of my users are locked out, which leaves me with no way of getting in to fix. Would be super helpful if there was some type of documentation on how to deal with this.

_Originally posted by @five2seven in https://github.com/babybuddy/babybuddy/issues/449#issuecomment-1239682469_

**Comment by earthcomfy** [comment]
Hi, I will work on this issue.

**Comment by earthcomfy** [comment]
@cdubz Is the custom management command supposed to create one user or should it accept the number of users to be created as an argument? In addition, is the command supposed to create users with the `superuser` status? If so there is already a built-in command that does this `python manage.py createsuperuser`.

Looking forward to hearing from you :smile:

**Comment by cdubz** [comment]
Hi, @earthcomfy! I _thought_ there was a command for this, hah.

Anyway I think it would still be ideal to have a custom command with prompts for the user properties (including the option to make the user an admin or not).

Relevant properties would be what you see in the custom user create page in the app — username, first name, last name, email, staff status, active status, and password.

**Comment by earthcomfy** [comment]
@cdubz I see. Thanks for the clarification.
