### ISSUE TITLE
In Portuguese: events created from timers don't inherit times (start/end)

### ISSUE THREAD

**Issue by renatose** [babybuddy/babybuddy#532]
This is a bug happening in Portuguese only as I tried changing to other languages and the function behaved as expected.
I'm using docker latest from linuxserver.io

**Comment by renatose** [comment]
The issue is reproducible in the demo
http://demo.baby-buddy.net/

**Comment by cdubz** [comment]
Probably related to or a duplicate of #498. It’s a nasty bug that I really need to dig in to…

**Comment by renatose** [comment]
When my kid allows I'll try to dig into it as well and I'll post any findings.

**Comment by cdubz** [comment]
Fixed by 1d9577a.
