### ISSUE TITLE
Delete Inactive Timers shouldn't appear if there are no timer entries

### ISSUE THREAD

**Issue by earthcomfy** [babybuddy/babybuddy#533]
The **Delete Inactive Timers** button shows up even when there are no entries :point_down: 

![Inactive timers](https://user-images.githubusercontent.com/66206865/193020587-960462b9-f96f-426c-9ab7-f039342f6e89.png)

If you approve the issue, I would love to work on it.

**Comment by cdubz** [comment]
Sure, go for it. Thanks!
