### ISSUE TITLE
Dutch Translations updated on POEditor

### ISSUE THREAD

**Issue by almer-t** [babybuddy/babybuddy#535]
Hi,

I updated the Dutch translations on POEditor a while ago, I hope this'll be useful and can be merged in.
Thanks for the great work on developing and maintaining BabyBuddy!

Best!

**Comment by cdubz** [comment]
Thanks for the ping. My workflow with POEditor is not strong 😬 

TIL to not use POEditor's integrated upgrade... I assumed it would create a PR but instead it just made 22 separate commits, one for each translation file 😭 

Anyway your updates should be in now -- thank you!!
