### ISSUE TITLE
Database Admin: 500 Error v1.13.0

### ISSUE THREAD

**Issue by TomLyon** [babybuddy/babybuddy#540]
#### Issue description
Accessing database admin while on the latest version 1.13.0 causes a 500 error.

#### Steps to reproduce the issue

1.  Update to the latest version of babybuddy (1.13.0)
2.  Login to dashboard
3.  Attempt to access database admin from dropdown menu

#### Additional details
Reverting back to v1.12.2 fixed the database admin page.

![image](https://user-images.githubusercontent.com/90040568/195249108-62ad4d61-9c48-4aa4-ae58-807888f2653b.png)

**Comment by cdubz** [comment]
I'm not able to reproduce this locally or in the demo. I think Django included some migrations -- did you run migrations after updating? If so or if that doesn't help, could you enable debug (set `DEBUG` environment variable to `1`) and see if you get more information about the error?

**Comment by starbuck93** [comment]
Also seeing this. Deployed on Heroku (for the time). My plan was to update, get my data out of the Heroku database and migrate to a Home Assistant add-on. Looks like the papertrail log add-on in Heroku is just the web server logs.

**Comment by cdubz** [comment]
@starbuck93 same Q -- did you run migrations after your update?

**Comment by starbuck93** [comment]
> @starbuck93 same Q -- did you run migrations after your update?

No, I'm unsure how to do that in the Heroku deployment via a forked repository. I did find how to get to the `bash` shell inside of the Heroku instance.

**Comment by cdubz** [comment]
> > @starbuck93 same Q -- did you run migrations after your update?
> 
> No, I'm unsure how to do that in the Heroku deployment via a forked repository. I did find how to get to the `bash` shell inside of the Heroku instance.

Run `python manage.py migrate` from the bash shell.

**Comment by TomLyon** [comment]
No, I haven't run any data migrations. I'm running BabyBuddy using Docker and MySQL. I attempted the above command inside the container:

`root@fcfb82645475:/app/babybuddy# python3 manage.py migrate
Traceback (most recent call last):
  File "/app/babybuddy/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.9/site-packages/django/core/management/base.py", line 93, in wrapped
    saved_locale = translation.get_language()
  File "/usr/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
  File "/usr/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 72, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`

**Comment by starbuck93** [comment]
Had to run manage.py makemigrations first, then the migration was successful for something about timezones but I'm still getting the 500 error on the Admin panel
![Screenshot_20221012-191046](https://user-images.githubusercontent.com/5626027/195470268-58abea8a-41d4-40fc-b0ed-5ecf27cdc46c.png)

**Comment by TomLyon** [comment]
I set DEBUG=1 and restarted the container, this is odd but the Database Admin page worked fine when I enabled debug mode. As soon as I remove DEBUG the page gives a 500 error.

**Comment by cdubz** [comment]
Not quite sure why, but somehow outdated static files were causing this 🤷

New releasing coming...

**Comment by starbuck93** [comment]
Thank you!

**Comment by TomLyon** [comment]
All is working now, thanks!
