### ISSUE TITLE
Improve user permissions structure

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#544]
Currently any user added to Baby Buddy via the user form is marked a superuser and bypasses all permissions. Instead Baby Buddy should probably abstract three user types:

- Read only (default, can access all data but not make new entries)
- Standard (can access and make/edit any type of entry)
- Staff (bypasses permissions, can access Database Admin area)

This will likely require creating a maintaining programmatic groups and ensuring permissions are kept up-to-date within.

Related issues:

- #70 
- ~~#187 (maybe too complex for this issue)~~
- #449
- #528 
- #534 
- #543

**Comment by earthcomfy** [comment]
@cdubz Are you thinking of using Django groups? We can add the user's group when the user is created via the form or from the command line. 

Then we can have object-level permissions for the [API](https://github.com/babybuddy/babybuddy/blob/master/api/views.py) as well by checking if the user belongs to a particular group.

**Comment by earthcomfy** [comment]
I see, so there should be 3 options when creating a user. I will look at it and send a PR.
