### ISSUE TITLE
Issue with winter/summer time

### ISSUE THREAD

**Issue by Anoerak** [babybuddy/babybuddy#557]
Hi again 😅,

I've found a new issue. 
When you try to create an entry on the day we change time (summer to winter or winter to summer) as on October 30th, when your try to create an entry with a time start or end at 02:.. am, an error shows up and denied the creation. 
So no other choice than create the entry with a start/end at 01:.. or 03:...

![image](https://user-images.githubusercontent.com/79709673/198877382-e833cc0c-e661-4522-8a8d-ff41d8270eb0.jpeg)

**Comment by cdubz** [comment]
Yeah this is #174 -- open to PRs to assist with this but I've never taken the time to try to dig in to it. Hard prioritize something that happens twice a year hah 😄
