### ISSUE TITLE
Feeding pattern

### ISSUE THREAD

**Issue by savaloi** [babybuddy/babybuddy#567]
Hi, loving using baby buddy for my week old newborn, wondering if there’s a similar report to the ‘Sleep Pattern’ report, but for feeding instead?

Thanks

**Comment by cdubz** [comment]
There is not currently a report like that. I am hesitant to add new reports generally because they tend to be complicated and require the most maintenance effort but I would consider PRs for this.

**Comment by simon-bd** [comment]
I really think Feeding pattern would a great addition, could we look into it?

**Comment by cdubz** [comment]
I'm not actively looking in to this but I am open to PRs. It may help the issue if those are interested in this provide some examples/mock ups on what a graph like this would show.
