### ISSUE TITLE
Unable to add feeding

### ISSUE THREAD

**Issue by Coleej** [babybuddy/babybuddy#572]
Adding a feeding produces the following error:

Error: Another entry intersects the specified time period.

I have been using the app for 2 months and it's worked flawlessly. Also, other activities can be entered.

Let me know how I can help troubleshoot.

**Comment by cdubz** [comment]
Any chance you have an accidental conflicting entry with a far future end date?

**Comment by Coleej** [comment]
I dont think so. I was about to restore from backups, but, Iit stopped happening the next day.

My wife said this also happened during the Daylight Savings time change.

**Comment by cdubz** [comment]
Yeah my guess was going to be somehow related #174. I know that issue number by heart now 😞 Damn DST.

I’m gonna assume this is related and close but feel feee to update if it pops up again.

**Comment by cdubz** [comment]
This will be fixed (with a migration to fix existing incorrect entries) in the next release. Tracking other DST issues over in #893.
