### ISSUE TITLE
Can't add event in the future

### ISSUE THREAD

**Issue by axelsimon** [babybuddy/babybuddy#579]
Trying to add a change event in the future returns a 500 internal server error.

I know what you might say "if something hasn't happened yet, just wait until it's happened", but i think there's a use case:
a parent/carer gets ready to go change the child, so the other one knows a change will be done in 3 min and just adds it to Baby Buddy there and then to not forget.
Without the possibility of adding events in the future, you have to stay concentrated on the upcoming event and not forget to put it one once done.

Opinions welcome on this, obviously.

**Comment by cdubz** [comment]
We’ll if nothing else you shouldn’t be getting a 500 error but a regular error message. Can you reproduce at all in the demo instance?

Did you ever do any more digging over in #542?
