### ISSUE TITLE
Pumping entries should be taggable

### ISSUE THREAD

**Issue by btoconnor** [babybuddy/babybuddy#584]
It would be good if pumping entries had tags.  We have more than one pump and my wife would like to associate which entry comes from which pump - tags seems like a reasonable solution to this (rather than her manually entering things).  It seems like a fairly straightforward change to accomplish as well (based on a quick look at the code - if that's not the case would definitely be open to correction!)

**Comment by cdubz** [comment]
Yeah this an oversight. Everything should be taggable and I thought that was already the case 😃

**Comment by cdubz** [comment]
Closed by #590
