### ISSUE TITLE
Enhancement: Add support for tracking weaning?

### ISSUE THREAD

**Issue by martsa1** [babybuddy/babybuddy#591]
Hey folks, first off, huge thanks for creating/maintaining babybuddy, its been fantastically helpful through my first child's first few months.  

I wanted to ask if its currently possible, or would potentially be possible in the future, to add support for weaning?

In essence, I'd like to easily record in a feed what my child was given (potentially grouping food types or some such), but specifically also to track things like reactions (or hopefully, lack thereof) to allergens and stuff like that, from within the system.

Alongside tracking what my child ate and when, it'd then be nice to try and visualise which food-types etc. she's eaten recently, to assist in meal planning.

Have other users come across similar desires, and if so, was there a nice way you handled that with BabyBuddy's current capabilities, or would something like this be of potential value to other users (not just me) as well?

**Comment by cdubz** [comment]
👋 Welcome -- there have been requests in the past for more (or configurable #79) food options but I have tried to resist them to limit complexity (I feel like feeding is already too complex). I think you could achieve what you want to do with the "Solid food" type and tags to assign specifics like type of food and reactions. The demo is a good place to poke around and try out ideas. If that feature combo is missing anything key, feel free to follow back up.

**Comment by martsa1** [comment]
Ah thats a nice suggestion, thanks. Agree that it'd be difficult to maintain if food options were something hard-coded or required separate management (tags are a nice suggestion since we can add new ones on the fly when logging a feed).

I'll give that approach a go, thanks again!
