### ISSUE TITLE
Today's Feedings should be rounded

### ISSUE THREAD

**Issue by btoconnor** [babybuddy/babybuddy#595]
My dashboard is showing me this today:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/81829/217338368-e5b8c1ba-446e-4630-8cd9-7baad5d9f55d.png">

I'm assuming this is due in some form to floating point values.  It seems like these values should probably be rounded to either tenth or hundredth degree (no opinions).

**Comment by cdubz** [comment]
Haha weird... what values do you have for the day?

**Comment by btoconnor** [comment]
We've got 3 bottle feedings today - 5.5, 3.3, and 4.4.

From a python shell:
```python
>>> 5.5 + 3.3 + 4.4
13.200000000000001
```
So, yeah - floating point numbers 🙃

**Comment by btoconnor** [comment]
Seems like it might make sense to use Django's `floatformat` template tag on these: https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#floatformat

I think the values just come from here?https://github.com/babybuddy/babybuddy/blob/master/dashboard/templates/cards/feeding_day.html#L18

**Comment by cdubz** [comment]
Nice. Yeah I think `floatformat` would be improvement here. Probably in a lot of places in those cards.
