### ISSUE TITLE
Additional Dashboard Tile - Pumping

### ISSUE THREAD

**Issue by nbanderso** [babybuddy/babybuddy#601]
Hello,

Thanks for putting together and maintaining such a great tool for the sleep deprived parents out there!  

Would it be possible to add an additional "tile" on the dashboard for pumping information?  More specifically, here is how I envision it looking:

Title: Last Pumping (clickable link to pumping log)
 - How long ago; ie "3 hours, 6 minutes ago"
     - Time; ie "5:31 p.m."
     - Amount; ie "60 mL"

Thanks again!

**Comment by rikrdo89** [comment]
My wife would be so happy to have this feature added!

**Comment by cdubz** [comment]
Test environment from #604 adding this — http://pr-604.dokku.baby-buddy.net (admin/admin). Does this card information look good?

**Comment by nbanderso** [comment]
@rikrdo89 it's perfect!  You are a true life saver.  Thank you!

**Comment by rikrdo89** [comment]
Thanks @cdubz ! It looks great 👍

**Comment by cdubz** [comment]
Thanks for flagging -- I forgot to update the locales. Should be there now!
