### ISSUE TITLE
PROXY_HEADER - Documentation update

### ISSUE THREAD

**Issue by p-b--** [babybuddy/babybuddy#608]
This isn't really an issue with your docs exactly, and you do specify to read the the django docs [here](https://docs.djangoproject.com/en/4.1/howto/auth-remote-user/#configuration).

When setting up this config -- I found that you had to convert all headers to follow the django spec for [request.meta](https://docs.djangoproject.com/en/4.1/ref/request-response/#django.http.HttpRequest.META)  namely this part:

> With the exception of CONTENT_LENGTH and CONTENT_TYPE, as given above, **any HTTP headers in the request are converted to META keys by converting all characters to uppercase, replacing any hyphens with underscores and adding an HTTP_ prefix to the name. So, for example, a header called X-Bender would be mapped to the META key HTTP_X_BENDER.**

As a result, using a header (like the one you provided in your example) as `X-Auth-User` would be have to be converted to `HTTP_X_AUTH_USER`

If you could add a line similar to what's included in the docs for how headers are mapped, that would go a long way in reducing the time it takes to figure this out.

**Comment by cdubz** [comment]
Thanks for bringing this up -- I'm not sure I follow the issue here. Is there specific language you'd recommend adding to the docs?

**Comment by p-b--** [comment]
Sorry I wasn't more clear, I'd suggest including the bolded content directly along with an example showing how the header would map. For example:

**Note:** HTTP headers in the request have all characters converted to uppercase, replacing any hyphens with underscores and adding an HTTP_ prefix to the name.
For example `X-Auth-User` would be converted to `HTTP_X_AUTH_USER`.


I would also add this link: https://docs.djangoproject.com/en/4.1/ref/request-response/#django.http.HttpRequest.META to the "See Also" section as it explicates what headers are converted.

**Comment by cdubz** [comment]
Ok, gotcha. Are you interested in opening a PR for these changes?
