### ISSUE TITLE
Daylight Saving time change breaks daily feeding sum

### ISSUE THREAD

**Issue by poldim** [babybuddy/babybuddy#612]
Noticed this yesterday but forgot to post. He's typically around 30 per day so this is definitely not accurate.
![image](https://user-images.githubusercontent.com/16869713/224863663-550db2c1-76cd-41b3-bfe7-cc1d70304235.jpeg)

**Comment by ShaneK** [comment]
We also noticed that our daily feedings for yesterday were combined with the day before. Seems to be properly reset today though. I assumed it was just a weird hiccup with DST, but now that there's an issue open for it I'll just add that it did happen to me too (this is mL). I also included screenshots of the values that were summed together so you could see that the app _does_ know that they were on different days, it just won't display them as separate.
<img width="511" alt="image" src="https://user-images.githubusercontent.com/561207/224865385-cd3d0385-7560-41d1-b157-756958e531b2.png">
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/561207/224865485-3d86dc49-349d-4dc4-a6d1-bc78a6d0c0a9.png">
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/561207/224865530-f53bd128-2a38-48e0-93db-45fba5092811.png">

**Comment by cdubz** [comment]
Yeah this is related to #174 but also distinct and specific enough to keep open separately. Thanks for reporting!

**Comment by one-lightning** [comment]
Hello,

Also want to report daily feeding issue for yesterday. Now is difficult to distinct which data is duplicated.

![image](https://github.com/babybuddy/babybuddy/assets/49819514/befcb30c-6621-4ae5-8025-bd3641810621)
![image](https://github.com/babybuddy/babybuddy/assets/49819514/57fdcc38-1c63-448f-bd4f-cde873f1da37)
![image](https://github.com/babybuddy/babybuddy/assets/49819514/7a6b37d2-94b9-4ba7-9ab4-3b5ea0284081)
![image](https://github.com/babybuddy/babybuddy/assets/49819514/e31bc779-9f17-4ad9-ac6b-91a4285e5489)

**Comment by cdubz** [comment]
This should be fixed in the next release. Continuing to track other DST issues over at #893.
