### ISSUE TITLE
Changing display up till time brings up persistent 500 server error

### ISSUE THREAD

**Issue by TaddyJ** [babybuddy/babybuddy#613]
I recently updated from 13.2 to 15.0. after doing so it was showing some outdated pumping information on the home screen which we didnt need since my wife no longer expresses.. 
I seen in the settings you could adjust the time in which information is displayed up till. So I changed it to 4 weeks.
After I clicked save it refreshed the screen and came up with a "500 Server Error".
I tried restarting the container a few times. re creating it. no luck.
I downgraded back to 13.2 (since I knew that was working fine) and its working again.
I tried pulling the latest image again and recreating it. and after it had booted I got the same 500 error.
So I downgraded again till we get some work around. :)

**Comment by cdubz** [comment]
Thanks for reporting! I can reproduce this in the demo so definitely needs a look.
