### ISSUE TITLE
Wrong even/odd row coloring on lists with notes

### ISSUE THREAD

**Issue by Alberdi** [babybuddy/babybuddy#615]
On the lists like `/feedings/` or `/height/` when the entries have notes the alternate row coloring can become off. I don't know how to reproduce it, but it seems fairly common. [Screenshot](https://user-images.githubusercontent.com/1556349/227047038-6d2619c7-6353-4e2e-b9de-f3d4c97cc7c1.png) from the demo app after adding a few notes here and there.

It seems like some odd rows get their colour from `.table-striped tbody tr:nth-of-type(2n+1)` when they shouldn't, but take this with a grain of salt because CSS is not my thing.

**Comment by cdubz** [comment]
Thanks for flagging! I feel like I have noticed this before and then forgot about it multiple times 😆

**Comment by Kauetheadventurer246** [comment]
Do you know where this big is located in the files? I’m trying to find it with no luck so far.

**Comment by Alberdi** [comment]
My totally unexperienced guess is that the CSS is wrong and both the `nth-of-type(odd)` lines should simply apply to the `tr` with the `odd` class without having to count their actual position:
https://github.com/search?q=repo%3Ababybuddy%2Fbabybuddy+nth-of-type&type=code

**Comment by cdubz** [comment]
This should be resolved in v2.
