### ISSUE TITLE
Unable to install Baby Buddy in Home Assistant via Add-Ons

### ISSUE THREAD

**Issue by jwilters** [babybuddy/babybuddy#618]
Hi there, I have downloaded the repository and when clicking Install, I get the below error in Home Assistant:

The command '/bin/bash -o pipefail -c echo "**** install build packages ****" && apk add --no-cache --virtual=build-dependencies build-base curl jpeg-dev libffi-dev libxml2-dev libxslt-dev postgresql-dev python3-dev zlib-dev' returned a non-zero code: 15

Any idea how to solve this?

![image](https://user-images.githubusercontent.com/96946602/228184217-61485468-bd34-4a09-af86-66d93cad2ec3.png)

**Comment by huntedhawk** [comment]
I think you would be better off asking the plugin author on thier report https://github.com/OttPeterR/addon-babybuddy

**Comment by jwilters** [comment]
Thanks Chris, also logged an issue there..

Cheers,
Jaco
