### ISSUE TITLE
Overlapping Times Error if Entries Have Same HH:MM

### ISSUE THREAD

**Issue by tango2590** [babybuddy/babybuddy#619]
A good example of this would be if the mother starts breast feeding, ends at 15:26:11, and starts a bottle feeding at 15:26:47. Even though the seconds are different, submitting the bottle feeding will result in an error that says the times are overlapping. Changing to the minute fixes this issue.

![228964628-26291b28-dc2b-4584-8ad6-9d642eebe544](https://user-images.githubusercontent.com/78666662/229212570-8bf9abd5-9aa7-4e92-87c0-48b099449d83.jpg)

**Comment by cdubz** [comment]
> A good example of this would be if the mother starts breast feeding, ends at 15:26:11, and starts a bottle feeding at 15:26:47. 

That's a fair use case. For feeding the app does not track seconds granularity. I think it make sense to modify the intersection check to allow for this, will just need to check if that interferes with anything (graphs?).

**Comment by Kauetheadventurer246** [comment]
But where in the files is the big hiding in?

**Comment by cdubz** [comment]
Actually this is resolved by 353533a6ef83baf7a54e553ad79bf08ac657a467 as we have removed the fronted library for datetime handlers. The default browser-based handlers will have second granularity. This will be in the 2.0.0 release.
