### ISSUE TITLE
Feature Request - Potty Training

### ISSUE THREAD

**Issue by mcbrown1010** [babybuddy/babybuddy#620]
Maybe add a new potty activity where parents can track potty training progress. 

this could include
- options for if the child made it to the potty or had an accident.
- wet or solid options 
- if the child sat on the toilet but didn't go
- perhaps a visual chart as well, featuring a star system for if they made it or not

**Comment by cdubz** [comment]
I'd be a tough sell on a specific activity for this. If you're interested in tracking this you could use the Diaper Change activity and tags to get a decent analog. E.g. --

- Child made it to toilet (DC entry w/type + "self-led" tag)
- Child had an accident (DC entry w/type + "accident" tag)
- Child sat on toilet but didn't go (DC entry w/o type + "false alarm!" tag)

Re: charting -- through various influences (co-op preschool education sessions, primarily) I am not a big fan of reward chats generally. If you want to do a star chart without the rewards it's probably more fun for everyone to use a real chart and stickers for the child to stick. More they can on their own! 😄
