### ISSUE TITLE
Hide unused fields from dashboard

### ISSUE THREAD

**Issue by poldim** [babybuddy/babybuddy#622]
Not sure if this is easy based on last time the data was updated for that field or maybe having options in the config page. But it would be nice to get rid of this from the dashboard. 

![image](https://user-images.githubusercontent.com/16869713/230227713-d99ead29-4818-4e1b-9b04-611fa8ba55f2.jpeg)

**Comment by cdubz** [comment]
Under user settings there is a "Hide data older than" option --

![image](https://user-images.githubusercontent.com/10456740/230630722-4e088055-ddbc-47aa-95a4-787fe48394b4.png)

Does this do what you want?

**Comment by poldim** [comment]
@cdubz thanks that did it! I didn't realize that option would solve it.
