### ISSUE TITLE
Events less than 1 minute old show incorrect "time ago" on dashboard

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#628]
![image](https://user-images.githubusercontent.com/10456740/232224836-22fef45f-e609-43c2-8538-f094d14a9616.png)

**Comment by sanchej** [comment]
Hi can I be assigned this issue?

**Comment by cdubz** [comment]
Sure thing!

**Comment by sanchej** [comment]
I apologize cdubz can I be removed from this issue? I have been swamped with work and do not want to stray people from helping until I can have an opportunity to help.

**Comment by cdubz** [comment]
Hmmmmmmmmmmmmmmmmmm 🤔

**Comment by billybonks** [comment]
https://github.com/babybuddy/babybuddy/pull/768
