### ISSUE TITLE
new feature : add wash the baby activity

### ISSUE THREAD

**Issue by tomamplius** [babybuddy/babybuddy#630]
New feature to track when baby was waching

**Comment by cdubz** [comment]
I’m a tough sell of new specific types like this. I often recommend using the notes and tags features for capturing specific events that are not covered by the core models.

Will leave this open for discussion though.

**Comment by axelsimon** [comment]
This makes me think though, the problem with putting arbitrary data in notes is that you get no reports, no quick way of seeing when the last bath was,  how often they happen, etc.
It's not really any different from keeping that in a txt file on your computer. Or am i missing something?
