### ISSUE TITLE
Birth date when adding time does not format correctly 

### ISSUE THREAD

**Issue by B08Z** [babybuddy/babybuddy#631]
If you set a birth date and time the field does not save correctly

For example

2023/04/22 11:23 changes to 2023/04/22 23:57

Any help greatly appreciated

**Comment by cdubz** [comment]
The birth date is a date only field. Where are you setting and seeing a time?

**Comment by B08Z** [comment]
Sorry for late reply.

And a quick intro.

We have just had Triplets I found your app and it is amazing it's so
important to be able to keep track of everything.

These are the screen shots it would be great if you could add a time of
birth as a feature..

**Comment by cdubz** [comment]
@B08Z did you mean to add screenshots? There aren't any with your note.

**Comment by B08Z** [comment]
Hmm odd. 
I did but will try again! 

I think it's just an odd auto format when using it on android. 

A time field would be great through. 

I have just become a parent to Triplets so keeping track is really key.

**Comment by cdubz** [comment]
Ah weird... OK. I'll give this a test on an Android device. That field only supports a date so there shouldn't be any time designation in the there :thinking:

**Comment by B08Z** [comment]
> Ah weird... OK. I'll give this a test on an Android device. That field only supports a date so there shouldn't be any time designation in the there :thinking: 

Argh ok. Makes sense. Time would be nice to have as an optional field?

**Comment by cdubz** [comment]
@B08Z FYI I fixed the bug here but please do feel free to open a separate issue with the feature request for supporting time granularity for the birth date field.
