### ISSUE TITLE
Failed to start when using Home Assistant add-on 

### ISSUE THREAD

**Issue by Yogi195** [babybuddy/babybuddy#646]
Failed to start add-on
Image ottpeterr/image-amd64-babybuddy:1.16.0 does not exist for addon_68152197_baby_buddy

**Comment by MrApplejuice** [comment]
This probably should go on the [homeassistant addon-repo](https://github.com/OttPeterR/addon-babybuddy), right? 

However: I noticed the problem as well - happens when you press "install", right? When I tried a few times, it ultimately succeeded anyway. Does that work for you as a workaround?

**Comment by Yogi195** [comment]
This happened when I try to start the add-on

**Comment by Yogi195** [comment]
> This probably should go on the [homeassistant addon-repo](https://github.com/OttPeterR/addon-babybuddy), right?
> 
> However: I noticed the problem as well - happens when you press "install", right? When I tried a few times, it ultimately succeeded anyway. Does that work for you as a workaround?

This happened when I try to start the add-on after install

**Comment by cdubz** [comment]
@Yogi195 the error message doesn’t come from Baby Buddy — looks like HA had issues downloading the correct tag for some reason.

**Comment by Yogi195** [comment]
> @Yogi195 the error message doesn’t come from Baby Buddy — looks like HA had issues downloading the correct tag for some reason.

I just tried a reinstall again  still getting the same error I used the url referenced in the instructions

**Comment by cdubz** [comment]
Any chance you've got something on your network that could be blocking access to the image?

For reference the image is there: [ottpeterr/image-amd64-babybuddy:1.16.0](https://hub.docker.com/layers/ottpeterr/image-amd64-babybuddy/1.16.0/images/sha256-ab75e65f852573e7c9012b4a22968924e0b78c51ce5b143bf2dc4cf99487d943?context=explore)

@OttPeterR any ideas?

**Comment by Yogi195** [comment]
> Any chance you've got something on your network that could be blocking access to the image?
> 
> For reference the image is there: [ottpeterr/image-amd64-babybuddy:1.16.0](https://hub.docker.com/layers/ottpeterr/image-amd64-babybuddy/1.16.0/images/sha256-ab75e65f852573e7c9012b4a22968924e0b78c51ce5b143bf2dc4cf99487d943?context=explore)
> 
> @OttPeterR any ideas?

I don't have any blocking enabled and I can get to the image site manually

**Comment by OttPeterR** [comment]
Using either the SSH add-on or connecting directly, can you run this command to see if you have the image locally?
`docker images | grep baby`

I expect it to not show up, so then try this to manually force a download 
`docker image pull ottpeterr/image-amd64-babybuddy:1.16.0`

And try that first command again to see if it downloaded and is available, then try to download and run the ads on again.

**Comment by Yogi195** [comment]
Thank you needed manual download
