### ISSUE TITLE
Nap field always False when adding Sleep entries via API

### ISSUE THREAD

**Issue by Cadair** [babybuddy/babybuddy#657]
I haven't had a chance to look at this yet, but I updated to beta2 today and now all the sleep entries are showing as not naps despite the site wide settings.

It was working well on beta1

**Comment by Cadair** [comment]
I still haven't looked properly at a PC, but it seems that when entering a sleep in the web ui the nap toggle is correctly pre-populated. However, when i enter a sleep from home assistant via the api it is always not-a-nap.

**Comment by Cadair** [comment]
Yeah it seems that all the historical data is fine.

**Comment by cdubz** [comment]
FTR I haven’t least confirmed this. The API always defaults to `False` and does not respect the map boundaries. Haven’t had a chance yet to dig in to potential solutions though.

**Comment by Cadair** [comment]
Thanks! Looks like it's working as intended for us :smile:
