### ISSUE TITLE
Start Time Default to Current Date/Time

### ISSUE THREAD

**Issue by tango2590** [babybuddy/babybuddy#670]
This is just a minor bug, but whenever we go in to add a Sleep or Tummy Time activity, the Start Time is always blank. Not sure if that's by design, since the Feeding activity defaults both the start and stop time to the current date/time. It would be helpful if the Start Time was also prefilled for the Sleep and Tummy Time activities in the same way, especially since Tummy TIme will *usually* start and stop on the same date, just like a Feeding. I know a few taps can autofill based on the current time, but the boss lady suggested I "tell them about the bug because the extra taps are too much". 😂

**Comment by cdubz** [comment]
I think there are all normalized already in the upcoming 2.0.0 release. Can you reproduce the issue at https://demo.baby-buddy.net/?

**Comment by tango2590** [comment]
Looks like the times all autofill properly on the demo site. Looking forward to the update. Thanks!

**Comment by cdubz** [comment]
Thanks for confirming! Hoping to get the next release out with a week or two here...
