### ISSUE TITLE
Quick start timer icon no longer working

### ISSUE THREAD

**Issue by joemcmonagle** [babybuddy/babybuddy#677]
After upgrading to v2.0.0, the quick start timer no longer works when the stopwatch icon appears. This happens on my Android phone, my wife's Android, and our Fire tablet. When rotated to landscape on any device, the icon goes away and the timer dropdown appears and works. Also can still access timer in landscape by choosing the hamburger icon>Timers>Start Timer.  The + icon does still work to add activities though. It is only the stopwatch icon that stopped working after upgrade
Thanks

**Comment by cdubz** [comment]
Thanks for reporting. This was also reported over at https://github.com/linuxserver/docker-babybuddy/issues/32 but I wasn’t able to reproduce.

Are you able to reproduce the issue in the demo? https://demo.baby-buddy.net/

**Comment by joemcmonagle** [comment]
First off - thanks for all of the time youve put into this. My wife and I would be totally lost without it! The tracking helped us really get both of our babies to the weights the doctor was hoping to see and now we can all get a bit more sleep overnight.

I was actually able to reproduce on the demo site with some extra steps! When first trying, the timer works exactly as expected, but when I add a second child to the demo site, then the timer icon no longer works. We have twins which is why I'm guessing not as many other folks have noticed the behavior. Sorry for not including more detail in the initial opening. 

Do you see the same behavior after adding a second child?

**Comment by cdubz** [comment]
Just pushed a v2.0.1 bug fix release that addresses this. Thanks for helping to pinpoint the issue!
