### ISSUE TITLE
Recent Sleep arrow buttons don't work on v2 dashboard

### ISSUE THREAD

**Issue by btoconnor** [babybuddy/babybuddy#680]
Hitting right / left on "Recent Sleep" card on the dashboard no longer works in v2.  The other cards, AFAICT, still work.

<img width="479" alt="image" src="https://github.com/babybuddy/babybuddy/assets/81829/b0085f2a-57af-44da-816d-567a6c7dc5e6">

**Comment by cdubz** [comment]
Hm yeah I can see that in demo. Looks like those arrows need a little styling improvement as well after the BS5 dark mode update.
