### ISSUE TITLE
Integration with Babybuddy doesn't work anymore

### ISSUE THREAD

**Issue by Tiitto** [babybuddy/babybuddy#685]
Hi,

As many have pointed out, that timers **Active** switch was removed from the API, it no longer works after stopping the timer.

Here is my use case, and I think many would love this integration in their setup as well:
![image](https://github.com/babybuddy/babybuddy/assets/107300844/e1cc5a14-5eeb-4fdb-894c-7b20d1059d3a)

As before, I could have start the sleep timer from a tablet which has many other controls of our house and when wife or I wake up, we were able to stop the timer from this one as well. It showed the duration of last sleep. Right now, since it doesn't store **Active** timers, it deletes the timer right after you stop it.

Is there some kind of workaround to make this work?

**Comment by Tiitto** [comment]
> This looks like home-assistant. Is that correct? Or what kind of integration is this?

Yes, that is correct

**Comment by cdubz** [comment]
@Tiitto were you able to get things worked out?
