### ISSUE TITLE
Suggestion: collapse feedings with no duration on timeline

### ISSUE THREAD

**Issue by jschollenberger** [babybuddy/babybuddy#686]
I'm not sure if people are doing this differently, but I don't track the duration of bottle feeds, just the quantity. This results in two entries in the timeline for the feeding entry where really it only needs to be one. It also adds some confusion because both the start and end cards have a listed amount.

Perhaps if duration is zero the start card is hidden and the end card's "duration" text instead reads the time since? I suppose the "finished feeding" text could optionally be changed as well if desired -- "Baby had a feeding / baby was fed" since it is more like a diaper entry at that point.

![image](https://github.com/babybuddy/babybuddy/assets/1499565/d7a81d69-1a48-429d-a572-7ac80af82bbb)
vs
![image](https://github.com/babybuddy/babybuddy/assets/1499565/c055b166-83d8-443a-8948-2afa7350644e)

**Comment by cdubz** [comment]
I think tracking feeding duration is the much more common use case here but I'm open to implementing this if someone wants to work on it :+1:

**Comment by jschollenberger** [comment]
Thanks for implementing this! I'll give it a shot once it's released.
