### ISSUE TITLE
Django-imagekit library does not support Pillow 10+

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#692]
> Ok fixing this for now by locking Pillow at 9.5.0.
>  
> See https://github.com/matthewwithanm/django-imagekit/issues/566 and https://github.com/matthewwithanm/pilkit/issues/64. It looks like both of those packages may be abandoned but we'll give it some time before looking for a replacement. I'll open a separate issue to track that.
>
> I'll cut a new 2.0.4 release this this fix (and the login fail should be fixed in 2.0.3).

_Originally posted by @cdubz in https://github.com/babybuddy/babybuddy/issues/684#issuecomment-1656720822_

I'm watching the django-imagekit and pilkit issues for resolution. If nothing comes in the next few months I'll explore alternatives.

**Comment by cdubz** [comment]
Pilkit fixes are in. Now watching https://github.com/matthewwithanm/pilkit/issues/67 for the 3.0 version at https://pypi.org/project/pilkit/.

**Comment by vstoykov** [comment]
The new version is uploaded to PyPi ;)
