### ISSUE TITLE
Dark mode is gone, light mode has unreadable contrast at places

### ISSUE THREAD

**Issue by MrApplejuice** [babybuddy/babybuddy#695]
I am not sure if I missed something, but now that I updated to the new babybuddy, it came up in light mode:

![image](https://github.com/babybuddy/babybuddy/assets/542105/4e13c32f-bd5a-4dca-a648-0f7641088619)

I personally found dark mode a lot more functional for Baby Buddy because it does not tend flood a dark room with light as much when you pull up the website on your mobile waking up everybody in the process but that could be just my taste...

However, what _is_ a problem is that:
- There seems to be no way to switch back to the glorious dark mode? If there is, I cannot find it. Did I miss something?
- And the light mode itself is unreadable at places - see screenshot!

_Maybe_ an issue as well:
- Light mode seems to still inherit designs from the old dark mode, like the color of the nav-bar.

# Suggested solution

I think a simple theme-toggle would make me happy right now already, and maybe in the long run light mode could be repaired.

Also I would suggest setting dark-mode as the default again because of the before mentioned reasons.

**Comment by cdubz** [comment]
Hmmmm it should only be dark mode 🤔 eg check out the demo: https://demo.baby-buddy.net/

Maybe you need a browser cache refresh? Though I wouldn’t expect that…

**Comment by MrApplejuice** [comment]
Oh, ok... mmmh, thanks for the fast response. I will check if my build-dir is borked somehow. I confirm that the demo is working as expected for me, but my `master` build is very much "light mode only" right now for unknown reasons...

**Comment by MrApplejuice** [comment]
Yeah, I even see the dark-mode root element. 

![image](https://github.com/babybuddy/babybuddy/assets/542105/83c9f8d1-ae6b-424f-946d-0a203f143bb7)

Could be likely a false alert... I will dig a bit deeper to see what the issue is just in case!

**Comment by MrApplejuice** [comment]
Yes, false alert, sorry!

Reason: node_modules needed an update. Seemingly forgot to do that after the update this time before reporting a bug. Sorry!

**Comment by MrApplejuice** [comment]
From my testserver:

![image](https://github.com/babybuddy/babybuddy/assets/542105/45b2ffd8-de2a-4953-8316-269d3996fbd9)
