### ISSUE TITLE
Pumping API Doesn't Respect Parameters

### ISSUE THREAD

**Issue by tango2590** [babybuddy/babybuddy#696]
When calling the API to retrieve data using the below line, the results consist of all feedings, regardless of the `date_min` parameter. This seems to be new since updating to BB 2.0.

http://1.1.1.1:1234/api/pumping/?date_min=2023-07-30T00:00:00

**Comment by tango2590** [comment]
<img width="1114" alt="Screenshot 2023-07-30 at 20 23 43" src="https://github.com/babybuddy/babybuddy/assets/78666662/930bbe90-c7ca-4618-9fab-46e0dcb08b59">

**Comment by tango2590** [comment]
Looks like the parameter changes to `start_min` and `start_max`. Can we update the API schema doc to reflect this?

**Comment by cdubz** [comment]
Yes -- updated! Thanks for catching.
