### ISSUE TITLE
Feature request: update dashboard DC graph to include "both"

### ISSUE THREAD

**Issue by seanhagen** [babybuddy/babybuddy#699]
![image](https://github.com/babybuddy/babybuddy/assets/444767/e926a68a-689d-475f-a1b9-bef205a41484)

It's hard to tell how many diaper changes actually happened when the graph shows wet and solid separately. Could the graph be updated to have a third color for changes that are both?

If I'm just not reading the graph properly then that's fine, it's just tricky to tell how many total changes there have been in a day from this graph.

**Comment by cdubz** [comment]
Hm yeah I have thought about this in the past and not been sure exactly what direction to take. My take is that the important thing to show here is how many times the child peed and pooped in a given day not necessarily how many diaper changes took place.

Maybe adding a bit of textual metadata here would be useful? E.g show the label as “today (10 changes)” or have a secondary header with the number changes.

**Comment by josevh** [comment]
My use-case for this was in guess-timating how many diapers I'm going through daily when deciding whether or not to purchase more of the current size. It might just be a first-time-parent worry though 😅
