### ISSUE TITLE
FR/Question: Is it possible to make a read-only user/dashboard?

### ISSUE THREAD

**Issue by mattgphoto** [babybuddy/babybuddy#70]
Would be nice to have a read-only user who could not make changes to anything, just to view. Is that something that is possible already or could be done easily enough?

**Comment by mattgphoto** [comment]
Never mind, I think I found out how to do this :-)

**Comment by mattgphoto** [comment]
My apologies. Reopening as it looks like setting up a 'view only' user still allows them to see API Key and change their password, etc. Is there a way to get rid of this? These are the permissions the user has: https://m.purrbox.org/2QD4WLl

**Comment by cdubz** [comment]
Hm, I could see a use case for restricting access to the API (though assigned permissions are respected there, e.g. a user with the permissions in your screenshot would only be able to read the same data found in the app) based on the available `authtoken` permissions. But I'm hesitant to restrict a user's ability to change profile settings like name, email, language, etc.

**Comment by mattgphoto** [comment]
I can completely understand that! The use case here would be a parent who wants to share either some of the information/growth progress with the public (which, if the public user can change their password, defeats the purpose as they could lock out future logins). I'm not looking to turn this off for every user, just something like that specific use case.

**Comment by cdubz** [comment]
I see. I had not thought of that use case. Generally I feel like the presentation of the dashboard is pretty strongly focused on actionable information for caregivers, as opposed to general information relevant to others.

I am hesitant to build in support for a "read only" user in this sense. I think I would be more inclined to consider adding some way to build "public dashboards" with configurable cards and shareable links that don't require any authentication at all.

Either way, this isn't something I am compelled to prioritize over the current items I have tagged for [v1.3.0](https://github.com/cdubz/babybuddy/milestone/1) so it will be a bit of time before I can really consider it. Happy to have PRs, or course, with a lean towards the "public dashboards" approach.

**Comment by cdubz** [comment]
This is now possible thanks to #551 (with the CLI command, at least). #563 will also bring this feature to the regular users management form.
