### ISSUE TITLE
Entry pop ups persistent across refreshes

### ISSUE THREAD

**Issue by FiveVoltLogic** [babybuddy/babybuddy#701]
Not sure what to call them, but when you delete an entry or change something, the green pop ups that tell you the entry has been updated or removed etc.. are persistent on refresh, regardless of whether the X is pressed or not. Currently I have to scroll down through 20 of them. It seems this is happening when accessing through ingress on home assistant both on desktop and mobile. When accessing through IP:Port I don't have this issue.

![image](https://github.com/babybuddy/babybuddy/assets/65986111/e4dbbf77-5d64-4d0e-aeba-4e493312d09a)

**Comment by viniciuscmartins** [comment]
I found out that if you open the admin- database admin and go back to website it will clear them. Not sure why this happens

**Comment by cdubz** [comment]
This is an issue specific to Home Assistant. You can track it over at OttPeterR/addon-babybuddy/issues/31.
