### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by bembembene** [babybuddy/babybuddy#705]
hey everyone

instaling BB addon : Can't install ottpeterr/image-armv7-babybuddy:2.0.4: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=2.0.4&fromImage=ottpeterr%2Fimage-armv7-babybuddy&platform=linux%2Farm%2Fv7: Not Found ("manifest for ottpeterr/image-armv7-babybuddy:2.0.4 not found: manifest unknown: manifest unknown")

i have no clue...

greetings and thanks for helping

**Comment by cdubz** [comment]
Paging @OttPeterR ☎️

**Comment by OttPeterR** [comment]
Wanna open up an issue over in the Addon's GitHub page? https://github.com/OttPeterR/addon-babybuddy

Over there can you also tell me about your setup, how you're installing, and where you see that error?

**Comment by cdubz** [comment]
Continued over in OttPeterR/addon-babybuddy/issues/56
