### ISSUE TITLE
Some reports have end date +1 week in the future

### ISSUE THREAD

**Issue by MisterPhilip** [babybuddy/babybuddy#706]
Since upgrading to v2.x.x, I noticed that a couple of the graph's automatic date x-axis uses a future date. Thus, when you switch to a shorter time frame (e.g., 1 week, 2 weeks) you are potentially missing a lot of data.

This seems to only happen on Average Feeding Duration and Diaper Change Types reports, but we also aren't using all of the reports so it could be happening on others. Other reports we use (Feeding Amounts, Sleep Totals, and Sleep Pattern) show the correct last date.

![image](https://github.com/babybuddy/babybuddy/assets/950141/4812f9dc-ccbd-4980-ae3f-3fa1b7287a72)
![image](https://github.com/babybuddy/babybuddy/assets/950141/60322946-815e-47b1-8cf3-f84b84c998df)

Neither of these have an accidental log in the future, and the JS returned does show the correct date for the latest entry.
![image](https://github.com/babybuddy/babybuddy/assets/950141/829dc82e-8146-4fd5-a91f-87c3585ddd7a)
![image](https://github.com/babybuddy/babybuddy/assets/950141/faf49901-c3c3-4ec1-8ce1-e59b660899b0)

I suspect this is a ploty issue as I was able to [replicate it with the JS version](https://codepen.io/MisterPhilip/pen/vYvJKgG) with the same data points. Interestingly, if I remove some of the data points (any of them), it renders the x-axis correctly. It might be a limit to the number of plots before autorange freaks out? Anyways, manually setting the range and disabling autorange seems to fix the issue. I'm not sure it is worth the trouble to change the graph configs for Baby Buddy but thought I'd log the bug anyways!

**Comment by cdubz** [comment]
Hmmm weird. In your codepen if I set `autorange` to `false` it does indeed work better on the initial view but I still see the extra dates e.g. if I click "1w", then "all", then "1w" again...

**Comment by cdubz** [comment]
Referencing this issues for further review:

- plotly/plotly.js/issues/1775
- plotly/plotly.js/issues/1876
