### ISSUE TITLE
Some translations are not showing in the app but are present in the repo

### ISSUE THREAD

**Issue by sephrat** [babybuddy/babybuddy#715]
I know there hasn't been a sync between POEditor and the repo for some months now, but this is different.

I'm using the app in French and I notice some strings are still displayed in English despite being localized in the .po file.
Examples:
https://github.com/babybuddy/babybuddy/blob/6db4d18e0ab98abcdb7d9d3498c9744b68f9c7ad/locale/fr/LC_MESSAGES/django.po#L1122-L1134 and https://github.com/babybuddy/babybuddy/blob/6db4d18e0ab98abcdb7d9d3498c9744b68f9c7ad/locale/fr/LC_MESSAGES/django.po#L1085-L1091
Still shows in English in /feedings/add/
![image](https://github.com/babybuddy/babybuddy/assets/34862846/fdf70728-4373-4118-b27a-8569d7e2f391)

Another example: https://github.com/babybuddy/babybuddy/blob/6db4d18e0ab98abcdb7d9d3498c9744b68f9c7ad/locale/fr/LC_MESSAGES/django.po#L1932-L1936
![image](https://github.com/babybuddy/babybuddy/assets/34862846/17d82236-8a08-4080-baae-44bb556ae893)

Most (I'd say 95%) of the other texts are just fine. 

Tested on v2.1.0

**Comment by cdubz** [comment]
Thanks for reporting! This will be fixed in the next release (coming after I look at one other issue).

**Comment by sephrat** [comment]
Thanks for the quick answer! 
It's better now but I can still see some issues. For example, my last example in my original post.
The common attribute for these non-working translations seems to be the "fuzzy" tag.
Other examples where original texts are displayed instead of the translated ones: 
https://github.com/babybuddy/babybuddy/blob/92238338e5f7105f9c652d09278ff349093cf316/locale/fr/LC_MESSAGES/django.po#L1938-L1941
https://github.com/babybuddy/babybuddy/blob/92238338e5f7105f9c652d09278ff349093cf316/locale/fr/LC_MESSAGES/django.po#L1958-L1961
https://github.com/babybuddy/babybuddy/blob/92238338e5f7105f9c652d09278ff349093cf316/locale/fr/LC_MESSAGES/django.po#L1963-L1968
https://github.com/babybuddy/babybuddy/blob/92238338e5f7105f9c652d09278ff349093cf316/locale/fr/LC_MESSAGES/django.po#L2304-L2308

**Comment by cdubz** [comment]
Ah yeah fuzzy translations won't be used. That is separate from the issue I fixed. Could you open a separate ticket for that for better tracking? I'll need to refresh my memory on how the fuzzy handling works...
