### ISSUE TITLE
WHO weight percentiles data not properly plotted in weight graph

### ISSUE THREAD

**Issue by P9k** [babybuddy/babybuddy#722]
I love the new feature of plotting the WHO weight percentiles together with the measured baby weights! :-)

Unfortunately, the percentile curves do not properly plot for me in the weight graph, but all show the value "0". 

The curves and their data are there in principle (I can see this when hovering over a curve), but are all plotted on top of each other along the x-axis.

![2023-10-15-WHO-Weight-1](https://github.com/babybuddy/babybuddy/assets/10435455/9902eae2-ce2d-4d69-907c-5bc7e824db26)

![2023-10-15-WHO-Weight-2](https://github.com/babybuddy/babybuddy/assets/10435455/6672e628-b820-48de-be3c-3636e0c4cf84)

In case that's relevant: I am on Babybuddy version 2.1.2 and use Firefox to browse the Babybuddy website.

**Comment by cdubz** [comment]
Huh, weird. The data also seems to be missing entirely from the demo instance... was this working for you in any prior version?

**Comment by P9k** [comment]
I did not test it in any previous version 

I got aware of this feature after upgrading to 2.1.2 and checking the changelogs.

**Comment by cdubz** [comment]
Hm, ok. It seems the migration is running but the WHO data is not being inserted for some reason... on a fresh install it doesn't seem to happen but it has happened to you and happened in the demo instance. What version were you on prior to updating to 2.1.2?

I'm not sure what is causing this yet but this should workaround the issue by re-running the migration and hopefully actually inserting the data (it worked in the demo, anyway). Run these commands from within the app environment:

```
python manage.py migrate core 0029_alter_pumping_options_remove_pumping_time_and_more
python manage.py migrate
```

@barakplasma any ideas what might be happening here? :detective:

**Comment by P9k** [comment]
> Check the y axis, his data looks like the y value is six thousand grams for example, rather than six kg. I think it's a scaling issue for his particular data

That's probably it! I am entering the weight in units of gram as this is what our scale shows. I just checked and noticed that in the documentation the weight appears to be entered in kilograms (https://docs.baby-buddy.net/user-guide/adding-entries/#weight).

**Comment by barakplasma** [comment]
Yeah, babies are weighed in kg rather than grams in most places. It's a known issue though that baby buddy is unit less

**Comment by cdubz** [comment]
Not really a known issue but an intentional decision 😉 I am leaning more towards using define units though. See also #689 —little more complex as it deals with food but illustrates there is indeed a lot of support for units generally.
