### ISSUE TITLE
Notifications not clearing (Home Assistant ingress)

### ISSUE THREAD

**Issue by broadcasttechie** [babybuddy/babybuddy#731]
Hi, I'm finding that using BB through the Home Assistant interface that notifications are never clearing until the container is restarted. 
Accessing the interface directly on port 8000 works fine, but not through HA. (same issue on both direct HA and through the nginx add-on I'm using for external SSL (CORS set in BB settings for both addresses).

This is using Chrome on Android.

I'll try and look at the code/ browser logs etc when I'm awake enough to find my laptop!

This is such a great solution - thank you!

**Comment by MrApplejuice** [comment]
Hey there! Just randomly saw you message. Have a look here: https://github.com/OttPeterR/addon-babybuddy/issues/31

The issue on the addon repo contains a (potential) fix for the problem. The discussion on issue mainly is about how to properly roll it out (if there isn't another better way).

**Comment by broadcasttechie** [comment]
Thanks for the pointer to the existing issue/comment - I'll blame lack of sleep for not searching the issues fully!

I'm struggling how to apply the setting suggested, can someone give me a hint how to edit the py files in the container on Home Assistant?

**Comment by MrApplejuice** [comment]
Hey! I suggest to ask on the other issue of the other repository. Your questions are more about home assistant than they are about babybuddy. A lot more knowledgeable people over there that can help (not a home assistant expert myself, otherwise I would answer).
