### ISSUE TITLE
Deleting entries gives 400 bad request

### ISSUE THREAD

**Issue by markolonius** [babybuddy/babybuddy#734]
When selecting all 2800 sleep entries in database and selecting "Delete selected Sleep" then "Go" then selecting "Yes, I'm sure" to confirm leads to "400 bad request" and does not delete any entries.  If I select only a few sleep entries it will delete them.  This also happens for diaper changes so I'm assuming for other things as well.  I am happy to provide any other info/debug/logs upon request (I just don't see how currently).

**Comment by cdubz** [comment]
The "Database Admin" section of Baby Buddy is the standard [Django admin site](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/). This sounds like an issue with that component. You can search for/add an issue over at [Django's bug tracker](https://code.djangoproject.com/) but I don't think there is much to be done on the Baby Buddy side.
