### ISSUE TITLE
Chinese translation - 喂食 -> 睡眠

### ISSUE THREAD

**Issue by hejhj** [babybuddy/babybuddy#742]
‘sleeps’ should be translated to ‘睡眠’
https://github.com/babybuddy/babybuddy/blob/1ef0bb9287adc4b47e74ec9cb2ac5164f142cc11/locale/zh/LC_MESSAGES/django.po#L1915

**Comment by hejhj** [comment]
@cdubz can you reopen this issue? The fix has been overwritten by the change in https://github.com/babybuddy/babybuddy/pull/741/files#diff-b7f5c38bb42aaa57f71fc6303eadd99a437b0866bd274647e3208e06c6480836

**Comment by cdubz** [comment]
Crap. Sorry about that!

**Comment by cdubz** [comment]
Fixed anew by #752.
