### ISSUE TITLE
What is the correct way to install python deps

### ISSUE THREAD

**Issue by billybonks** [babybuddy/babybuddy#750]
I didnt see anything regarding this on the documentation, so i am using  `pipenv install -r requirements.txt` this causes all dependencies to get locked, they are all currently *

I am not an expert at python so wanted to understand the correct approach

**Comment by billybonks** [comment]
https://github.com/babybuddy/babybuddy/compare/master...billybonks:babybuddy:fix/lockfile?expand=1 this is what happens to the Pipfile

**Comment by cdubz** [comment]
The [manual deployment documentation](https://docs.baby-buddy.net/setup/deployment/#manual) may help clarify this. Normally dependencies are install with pipenv. The requirements file is there for certain specific platforms that do not support pipenv.
