### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by billybonks** [babybuddy/babybuddy#759]
What should I use to lint/formatting:

JS
JSON
Django templates

right now I am using prettier JS and JSON and DJLint for Django. but every file I touch gets reformatted.

**Comment by cdubz** [comment]
The only linting that happens is via black and the `gulp lint` and `gulp format` commands. Anything else is not linted.

**Comment by billybonks** [comment]
Any objecting to me adding the ones mentioned here? i am not sure whats the best option for Django templates

**Comment by cdubz** [comment]
No objections. May be better to isolate that in to a separate PR though.

**Comment by billybonks** [comment]
Agreed

Kind Regards
Sebastien Stettler

**Comment by billybonks** [comment]
all prs are merged
