### ISSUE TITLE
Empty field message

### ISSUE THREAD

**Issue by aryansanchiya** [babybuddy/babybuddy#793]
When you forgot to fill the field, message is not displaying at right position.
so it can look confusing for the new user.
![Screenshot from 2024-04-12 17-54-54](https://github.com/babybuddy/babybuddy/assets/77040985/127f099a-fb6d-488d-aa82-71a511cb4342)

**Comment by cdubz** [comment]
@aryansanchiya that error is over the "Child" field and indicates that a child has not been selected. This message is just the browser behavior for a required radio fieldset so we don't really have control of where it appears (as is). Where would you expect it to be?

**Comment by aryansanchiya** [comment]
Okay i got this, i just misunderstood.
