### ISSUE TITLE
Provide a way to contribute/donate

### ISSUE THREAD

**Issue by ahosgood** [babybuddy/babybuddy#797]
I love OSS and this project is now very useful and relevant to me. Thank you for creating it!

I can't see a way to contribute anything - maybe there is but it's not prominent enough?

**Comment by cdubz** [comment]
@ahosgood thanks for reaching out -- and for looking to contribute! The main project page on GH shows sponsorship options in the sidebar. I'm actually just in the process of getting approval for the Baby Buddy "organization" to be sponsored but for now you can sponsor me directly on GH at https://github.com/sponsors/cdubz or via Open Collective: https://opencollective.com/babybuddy

I'll work on making these contribution paths more prominent in the README/docs.

**Comment by ahosgood** [comment]
Thank you. I was on the GitHub mobile app and it doesn't have the sidebar. I was looking in the README or on the docs site. 👍🏼
