### ISSUE TITLE
Diaper color picker is a drop down vs. buttons in 2.3.1

### ISSUE THREAD

**Issue by vember31** [babybuddy/babybuddy#803]
@cdubz wanted to say thank you! The diaper color (and amount) field is back and working in 2.3.1 :) 
 
This is a lower-priority item but I figured I'd put in an issue/enhancement for it.  While the color field is indeed back in 2.3.1, it's now the only field that you choose via a drop-down menu in any of the forms (e.g. comparing to feedings, etc).  The rest of the forms have all the options turned to buttons with 2.3.0, which has been really nice.

Just wanted to call it out so that it could match the UI/UX of the other fields that have been turned to buttons.

Thanks again for this app - it's incredibly helpful!

**Comment by cdubz** [comment]
Good call -- yes. Technically we are still kind of "in progress" with these ux/mobile enhancements. This probably just got overlooked. Will try to get it improved in a future release.
