### ISSUE TITLE
Add Bottle Feed Form: two 'Amount' fields 

### ISSUE THREAD

**Issue by AstroPhotoJay** [babybuddy/babybuddy#811]
As the title suggests...

The add bottle feed form has two amount fields which can both be filled in. The data in the second amount field is saved. Data in the first field is dropped. Screenshot for reference.

![2024-04-25 21_49_25-Add a Bottle Feeding _ Baby Buddy](https://github.com/babybuddy/babybuddy/assets/97019222/c94374a5-b153-49f3-8222-8eae488d679b)

**Comment by cdubz** [comment]
This is fixed in #800. I thought I had already released this but apparently not. Will get a new release out in the next few hours.
