### ISSUE TITLE
Feature Request: add more page option selections throughout app

### ISSUE THREAD

**Issue by 20BBrown14** [babybuddy/babybuddy#812]
When looking the feedings and changes page, sometimes I'd like to go to the very last page or even a specific page. It'd be nice if there were First, previous, next, and last page buttons

**Comment by cdubz** [comment]
Open to improvements here! Makes me wonder if there is any use case for _search_ but that seems like it would be complicated 🤔

**Comment by MisterPhilip** [comment]
To add to this - a dropdown to let us select the number of items per page would be a nice addition to the pagination. I think both might be relatively easy to add? I might take a stab at it once the tags updates are merged.

**Comment by cdubz** [comment]
Implemented in #824
