### ISSUE TITLE
Network issues - Assistance diagnosing please

### ISSUE THREAD

**Issue by psilantropy** [babybuddy/babybuddy#822]
Hi,

I have randomly hit some networking problems and wondered if I could have some help figuring this out. Wife has just started to love this system, but obviously outages are testing her! :)

I have about 32 other containers, maybe 15 with basically the same setup, but no issues.

They started out as 502 gateway errors as I was using my domain for all connections, but it seems my babybuddy container network intermittently drops/times out and causes this. After 5-30 seconds everything is fine again.

I use portainer to deploy. This shouldn't matter, but it does use 8000 on host.
lscr.io/linuxserver/babybuddy:latest
Babybuddy is set up with 8269:8000 tcp, bridge network.
I also have ngnix proxy manager, and forward 80+443 to this container on my router. If I shut this container down (and leave port forwards in place) it makes no difference to my situation.

Babybuddy container logs seem irrelevant?

> using keys found in /config/keys
> Operations to perform:
>   Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, dbsettings, sessions
> Running migrations:
>   No migrations to apply.
>   Your models in app(s): 'babybuddy', 'core' have changes that are not yet reflected in a migration, and so won't be applied.
>   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
> Cache table 'cache_default' already exists.
> [custom-init] No custom files found, skipping...
> [2024-05-11 22:47:31 +0000] [277] [INFO] Starting gunicorn 22.0.0
> [2024-05-11 22:47:31 +0000] [277] [INFO] Listening at: http://127.0.0.1:3000 (277)
> [2024-05-11 22:47:31 +0000] [277] [INFO] Using worker: gthread
> [2024-05-11 22:47:31 +0000] [314] [INFO] Booting worker with pid: 314
> [2024-05-11 22:47:31 +0000] [315] [INFO] Booting worker with pid: 315
> Connection to localhost (127.0.0.1) 3000 port [tcp/*] succeeded!

netstat -an | grep 8269
> tcp        0      0 0.0.0.0:8269            0.0.0.0:*               LISTEN
> tcp        0      0 192.x.x.x:8269      172.17.0.9:58882        TIME_WAIT
> tcp        0      0 192.x.x.x:8269      172.17.0.9:54010        TIME_WAIT
> tcp        0      0 1192.x.x.x:8269      172.17.0.9:52230        TIME_WAIT
> tcp      517      0 192.x.x.x:8269      172.17.0.9:45300        CLOSE_WAIT
> tcp        0      0 192.x.x.x:8269      172.17.0.9:58892        TIME_WAIT
> tcp      516      0 192.x.x.x:8269      172.17.0.9:52238        ESTABLISHED
> tcp      529      0 192.x.x.x:8269      172.17.0.9:52232        ESTABLISHED
> tcp      518      0 192.x.x.x:8269      172.17.0.9:52266        ESTABLISHED
> tcp      520      0 192.x.x.x:8269      172.17.0.9:45290        CLOSE_WAIT
> tcp        0      0 192.x.x.x:8269      172.17.0.9:58890        TIME_WAIT
> tcp      522      0 192.x.x.x:8269      172.17.0.9:52254        ESTABLISHED
> tcp      519      0 192.x.x.x:8269      172.17.0.9:45316        CLOSE_WAIT
> tcp      530      0 192.x.x.x:8269      172.17.0.9:41184        CLOSE_WAIT
> tcp      523      0 192.x.x.x:8269      172.17.0.9:45330        CLOSE_WAIT
> tcp      519      0 192.x.x.x:8269      172.17.0.9:52278        ESTABLISHED
> tcp6       0      0 :::8269                 :::*                    LISTEN

Should 80/443 be listed here? This isn't like the other containers in the list.

`# docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a
CONTAINER ID   NAMES                     PORTS
9d626e160fd6   Babybuddy                 80/tcp, 443/tcp, 0.0.0.0:8269->8000/tcp, :::8269->8000/tcp
`

```
netstat -tulpn | grep 8269
tcp        0      0 0.0.0.0:8269            0.0.0.0:*               LISTEN      3006262/docker-prox
tcp6       0      0 :::8269                 :::*                    LISTEN      3006275/docker-prox
```

Some web console logs (when it loads successfully)

> The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.

I think this happens when I load mid-failure, and some assets don't load.
![edgelogs](https://github.com/babybuddy/babybuddy/assets/79955883/16da44f0-0c0f-4b8e-a883-5cd173d5a7c2)

Tried various forms of env variables, doesn't really change anything.

> CSRF_TRUSTED_ORIGINS=site,site,site,
> SECURE_PROXY_SSL_HEADER=false
> REVERSE_PROXY_AUTH=true

Right now I just have this enabled and it works but still has the intermittent drops;

CSRF_TRUSTED_ORIGINS=https://babybuddy.xxxxxxxx.com,http://192.x.x.x:8269

I also run the HomeAssitant integration. If I watch the entities I can see them all go "unavailable" then back again quite often.
![ha](https://github.com/babybuddy/babybuddy/assets/79955883/ec34f682-034b-40df-a7f4-c81fbad55ec4)

I did try deploy as network = host, but get the bind in use for 80 and 443. Which are obviously in use by nginx proxy manager for all my other containers.

Thanks in advance for any support :)

**Comment by psilantropy** [comment]
I understand this part now.
`80/tcp, 443/tcp, 0.0.0.0:8269->8000/tcp, :::8269->8000/tcp
`I think this is just 80 and 443 inside the container only. Not sure if that is causing some of these issues though.

**Comment by cdubz** [comment]
When did you start using the container and when did you start experiencing the issue? Just curious to establish if it's always been happening or if the issue could be narrowed based on timing.

I wouldn't expect Baby Buddy's logs to tell you anything since the application doesn't really know anything about the infrastructure, but is there anywhere else along the path the logs could tell us something?

**Comment by psilantropy** [comment]
Thanks for the reply cdubz, and apologies I know this is likely not a bb issue at all but appreciate the assistance anyone can offer.

I have had this bb instance running for about a year. In active use for 6 weeks. For 3 of those weeks, I had no problems at all.
I keep bb up to date, along with other infra items - and no I don't test adequately.

I have dropped portainer from my host. Redeployed bb with just 8000:8000, but still get this 'outages' for up to a minute at a time.

If I complete a curl ip:8000 from my host (same host as containers, with containers bridged) I get connected, connected, then couldn't connect to server a few times before going back to connected. I'll see if I can drill into this problem further.

**Comment by psilantropy** [comment]
Bit more info from curl;


> user@host:~# curl 192.x.x.x:8000 -v
> *   Trying 192.x.x.x:8000...
> * Connected to 192.x.x.x (192.x.x.x) port 8000 (#0)
> GET / HTTP/1.1
> Host: 192.x.x.x:8000
> User-Agent: curl/7.88.1
> Accept: */*
> >
> < HTTP/1.1 302 Found
> < Server: nginx
> < Date: Tue, 14 May 2024 02:05:28 GMT
> < Content-Type: text/html; charset=utf-8
> < Content-Length: 0
> < Connection: keep-alive
> < Location: /login/?next=/
> < Expires: Tue, 14 May 2024 02:05:28 GMT
> < Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
> < X-Frame-Options: DENY
> < Vary: Accept-Language, Cookie
> < Content-Language: en-US
> < X-Content-Type-Options: nosniff
> < Referrer-Policy: same-origin
> < Cross-Origin-Opener-Policy: same-origin
> <
> * Connection #0 to host 192.x.x.x left intact

2 seconds later.

> user@host:~# curl 192.x.x.x:8000 -v
> *   Trying 192.x.x.x:8000...
> * connect to 192.x.x.x port 8000 failed: No route to host
> * Failed to connect to 192.x.x.x port 8000 after 1746 ms: Couldn't connect to server
> * Closing connection 0
> curl: (7) Failed to connect to 192.x.x.x port 8000 after 1746 ms: Couldn't connect to server
> user@host:~#

**Comment by psilantropy** [comment]
I think I accidentally figured out a solution after posting to reddit and trying a few more things.

- Ping from host to container ip (172) goes up and down constantly, however.
- 
- ping to container 172 gateway or any other ip on that network never drops.

After testing the above, I found a really weird thing. If I ping portainer 172xxx.12 I intermittently get a reply from .11 redirect to .12.

If I ping babybuddy 172xxx.6 I intermittently get a reply from .7 redirect to .6.

.11 is octoprint and .6 is transmission, both on the same bridge network. Stopping both those containers appears to have resolved this issue completely.

I will make new bridge networks and separate all this stuff. Problem solved :>

**Comment by cdubz** [comment]
Hooray! Glad ya got it sorted.

**Comment by psilantropy** [comment]
Thanks. Was driving me bonkers!
Have a good one and thanks for all your hard work.
