### ISSUE TITLE
Missing timer coverage for POST /api/pumpings

### ISSUE THREAD

**Issue by skjdghsdjgsdj** [babybuddy/babybuddy#826]
It looks like, while you can create a pumping entry through the web interface from a timer, the API coverage lacks the ability:

```
curl -v -H 'Authorization: Token ...' -H 'Content-Type: application/json'
    -X POST -d '{"child": 1, "amount": 10, "timer": 327}' 'https://.../api/pumping/'
```
results in:  
```
{"id":18,"child":1,"amount":10.0,"start":"2024-05-19T16:41:49.978134-00:00",
"end":"2024-05-19T16:41:49.978145-00:00","duration":"00:00:00.000011","notes":null,"tags":[]}%
```
Note the duration is effectively zero, not what timer `327` was tracking.

While I could use the API to just read the start of a timer and calculate the end, then POST accordingly, it would be far simpler if the schema accepted timer IDs like feedings do, and like the web UI implies is possible.

Schema attached that shows a missing timer ID field.

**Comment by skjdghsdjgsdj** [comment]
<img width="1029" alt="Screenshot 2024-05-19 at 5 03 35 PM" src="https://github.com/babybuddy/babybuddy/assets/37231318/a3918e55-adb4-4cd5-be1e-de66b5414f63">
GitHub in Firefox didn't attach the image so here's trying from Safari.

**Comment by cdubz** [comment]
Thanks for flagging. I _think_ we just need to change the `PumpingSerializer` @ https://github.com/babybuddy/babybuddy/blob/7937b23dc481a71ada34e1cea2547c9f00e34df2/api/serializers.py#L120-L123

to extend `CoreModelWithDurationSerializer` instead of `CoreModelSerializer` (as `FeedingSerializer` does).
