### ISSUE TITLE
Pumping Amounts report graph needs a legend

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#828]
While looking at #827 I noticed the Pumping Amounts report graph doesn't have a legend (while Feeding Amounts does) --

![image](https://github.com/babybuddy/babybuddy/assets/10456740/9ed04979-8f7c-4310-bb1f-9264991fd9cc)

As a minor aside -- the data faking for demo/development purposes could be improved to make that graph look a little more realistic (again, as Feeding Amounts does).

**Comment by laingcc** [comment]
What would the legend show? It doesn't look like the pumping amount has any other meta data, Just time and amount.

**Comment by cdubz** [comment]
Looking at this again -- it doesn't seem there is any need for a legend here. I think I just get confused by session-based coloring in this graph 😄 Thanks for looking!
