### ISSUE TITLE
how to add hebrew language?

### ISSUE THREAD

**Issue by noy1122** [babybuddy/babybuddy#840]
I tried to change BabyBuddy to hebrew but its not exist on the list in settings but when I log in to demo BabyBuddy I see hebrew in the list, how can I add it to my BabyBuddy?
thanks

**Comment by cdubz** [comment]
@noy1122 what version of Baby Buddy are you running? Hebrew was introduced in [v2.3.0](https://github.com/babybuddy/babybuddy/releases/tag/v2.3.0).

You can find your version in the bottom of the secondary menu:

<img width="269" alt="image" src="https://github.com/babybuddy/babybuddy/assets/10456740/d24514c7-5c27-4a1d-b890-a220b18706ec">

**Comment by noy1122** [comment]
@cdubz I tried to update now to 2.4.0 but when I try to update from HA i get this error

> Failed to call service update/install. Error updating Baby Buddy: Can't install ottpeterr/image-amd64-babybuddy:2.4.0: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=2.4.0&fromImage=ottpeterr%2Fimage-amd64-babybuddy&platform=linux%2Famd64: Not Found ("manifest for ottpeterr/image-amd64-babybuddy:2.4.0 not found: manifest unknown: manifest unknown")

maybe you know ?

**Comment by cdubz** [comment]
@noy1122 it looks like the latest version if not available yet. You can track it over at OttPeterR/addon-babybuddy/issues/71

**Comment by noy1122** [comment]
@cdubz so I cant update now?

**Comment by cdubz** [comment]
@noy1122 -- right. You are already using the latest version of the HA addon.

**Comment by noy1122** [comment]
@cdubz Ok. Thanks
