### ISSUE TITLE
Feature request: show time between feedings in feeding list

### ISSUE THREAD

**Issue by skjdghsdjgsdj** [babybuddy/babybuddy#841]
It would be helpful if the feeding listing page `/feedings` showed for each feeding the time elapsed since the prior feeding. Right now it shows the date/time and duration of the feeding itself, but not time since the prior one.

<img width="1265" alt="image" src="https://github.com/babybuddy/babybuddy/assets/37231318/0524f00b-ef05-4fa6-b557-b4a89773227b">

tl;dr "Time since prior feeding" column after "Duration" column

**Comment by cdubz** [comment]
Neat idea! Happy to review PRs for it.
