### ISSUE TITLE
Migrating using export/imports - child_id missing from export tool

### ISSUE THREAD

**Issue by psilantropy** [babybuddy/babybuddy#859]
(Note: I have imported everything, adding the column manually, this is just fyi)

Hi,

Is child_id excluded from exports for any reason? Or maybe a bug?

I was trying to migrate between 2 instances of babybuddy just using the database admin export and import tools.
I've done this before without issue, but the child_id column is not included with any exports.

For example a feeding export has;
![image](https://github.com/user-attachments/assets/8a4f1b7f-b30d-431a-96f5-fff619de833d)

But the importer requires;
` This importer will import the following fields: id, **child_id,** weight, date, notes, tags, child_first_name, child_last_name `

Export tool allows selection, but output doesn't produce.

![image](https://github.com/user-attachments/assets/0cc21958-4fba-4389-ba99-c6a68741063f)
![image](https://github.com/user-attachments/assets/18344132-6724-4751-9521-d285f8e47ef6)
![image](https://github.com/user-attachments/assets/9e1d92ac-eb0e-4c70-b85d-ffd80a4d9746)

Thanks :)

**Comment by cdubz** [comment]
Hm, I think that is a bug. Thanks for a reporting. Happy to take a PR or will look at it when I can.
