### ISSUE TITLE
Tags are ignored when adding a bottle feeding

### ISSUE THREAD

**Issue by real-or-random** [babybuddy/babybuddy#880]
Tags are ignored when adding a bottle feeding. I need to edit the entry afterward and re-add the tags. Only then the tags are saved.

This issue only occurs with the bottle feeding form. Everything is alright using the "normal" feeding form, or when adding entries other than feedings, e.g., notes. 

This is on version 2.6.0.

**Comment by cdubz** [comment]
Thanks for reporting -- I can reproduce this in the demo.

**Comment by cdubz** [comment]
Will be fixed in the next release! 🐛🥾
