### ISSUE TITLE
Incorrect colspan on pumping entries

### ISSUE THREAD

**Issue by skjdghsdjgsdj** [babybuddy/babybuddy#888]
Presumably introduced by the new "Previous" column, the colspan for notes on pumpings is one column too small:

<img width="1071" alt="Screenshot 2024-10-21 at 11 02 25 AM" src="https://github.com/user-attachments/assets/ebf6fc1c-8394-45cf-9b08-4ed2d96427f9">

Not sure if other pages are also affected.

**Comment by cdubz** [comment]
Thanks for flagging! Will be fixed in the next release.
