### ISSUE TITLE
Simple notes textarea for changes and feedings

### ISSUE THREAD

**Issue by nelsonblaha** [babybuddy/babybuddy#89]
My wife wants to be able to put notes like "20% left breast, 80% right breast" on feedings, and notes like "dry little raisin poop" on a diaper change. It seems like a general-purpose notes area on some activities would be very easy to do and useful for a lot of things like that.

**Comment by cdubz** [comment]
Make sense as an optional field. But would need a bit of thinking on how/when to show it? The list views are pretty jammed already and there is no "per-entry" view at the moment.

Happy to take ideas (or PRs!) for this. We are one day away from the 40-week mark for #2 👶

**Comment by nelsonblaha** [comment]
Congratulations! We discovered the notes function and that's pretty good. I suppose notes on events would still be useful for a lot of things, and slightly slightly better for our use case. As I'm a web dev I tried to make a PR for this but I'm just not familiar enough with the MVC of this framework. I could make a suggestion for the list problem though: some kind of tiny note symbol on an entry that has notes, indicating that going to the event show page will show the note.

**Comment by cdubz** [comment]
Working on this in a (unpushed) PR. I want the note to be easily visible without going in to an entry edit screen. I initially worked out a click to expand row solution, but I actually think it looks fine if entries with not just show the note in the row.

Here's an example listing of Diaper Changes with notes on some --

![image](https://user-images.githubusercontent.com/10456740/74582413-2a21a180-4f70-11ea-8ce2-cd7708de7c47.png)

This could maybe get a little crowded with excessive notes though.

**Comment by cdubz** [comment]
@nelsonblaha this is merged in to `master` and will be in v1.4.0 at some point.

**Comment by nelsonblaha** [comment]
I love BabyBuddy!!
