### ISSUE TITLE
Error in card_diaperchange_types 

### ISSUE THREAD

**Issue by thib3113** [babybuddy/babybuddy#890]
Doing nothing, just going to the app I get the error (every refresh) : 

```
Exception Type:	KeyError
Exception Value:	
7
Exception Location: /app/www/public/dashboard/templatetags/cards.py, line 86, in card_diaperchange_types
```

It seems that in /app/www/public/dashboard/templatetags/cards.py on the line 86, key was `7`, but stats is limited to 6 . 

https://github.com/babybuddy/babybuddy/blob/9a89f56067c65781f272265fab0078c5870882fe/dashboard/templatetags/cards.py#L86

Maybe linked with time change ? ( but it always crash on every refresh ) . 

I'm using timezone Europe/Paris

---

In the part "local vars" of the debug page I see : 
```
max_date	
datetime.datetime(2024, 10, 28, 0, 0, 0, 995083, tzinfo=zoneinfo.ZoneInfo(key='Europe/Paris'))
min_date	
datetime.datetime(2024, 10, 21, 0, 0, 0, 995083, tzinfo=zoneinfo.ZoneInfo(key='Europe/Paris'))
```

**Comment by markstor** [comment]
Same here with Europe/Madrid. Changing the user timezone to Etc/GMT-1 served as a workaround

**Comment by thib3113** [comment]
as a workaround, I've done a little change here : 

https://github.com/babybuddy/babybuddy/blob/9a89f56067c65781f272265fab0078c5870882fe/dashboard/templatetags/cards.py#L85

```diff
-key = (max_date - instance.time).days
+key = min((max_date - instance.time).days, 6)
```

it will not fix the real problem ... and return false stats ... but it works

**Comment by Coupyrulz** [comment]
> Same here with Europe/Madrid. Changing the user timezone to Etc/GMT-1 served as a workaround

How do you set this if I can't access the dashboard to edit users?

**Comment by thib3113** [comment]
@Coupyrulz can you access /user/settings/ of your installation ?

**Comment by cdubz** [comment]
This specific issue will be fixed in the next release. Continuing to track others over at #893
