### ISSUE TITLE
Clock change not calculated into sleep time 

### ISSUE THREAD

**Issue by markusschloesser** [babybuddy/babybuddy#891]
We had a clock change tonight here in Germany, but Babybuddy didn't factor in the extra hour into the sleep duration.

Running v2.2.1 in home assistant

**Comment by markusschloesser** [comment]
Apologies, non-native English speaker, should have searched for DST.
But I think this is a different issue?

**Comment by cdubz** [comment]
This will be fixed (with a migration to fix existing incorrect entries) in the next release. Tracking other DST issues over in #893.
