### ISSUE TITLE
DST issues 🕛🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🫠☠️ 

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#893]
I'm going to use this ticket to try to track down and squash the DST bugs that have been around forever. I haven't had a ton of time to work on Baby Buddy lately, but I have some planned time for it next week and this issue has been a longstanding pain-in-the-butt (like DST itself).

- [x] OttPeterR/addon-babybuddy/issues/78
- [x] #892
- [x] #891
- [x] #890
- [x] #831
- [x] #792
- [x] #612
- [x] #572
- [x] #570
- [x] #440
- [x] #211
- [x] #174

Just capturing _everything_ here for any context I need. Others feel free to point out things I may have missed!

**Comment by oelegeirnaert** [comment]
I had the same, I temporarily removed the diaper change from the dashboard.

I didn't have the time to troubleshoot.

But it has something to do with the time change from summertime to wintertime.

**Comment by cdubz** [comment]
Ok. I am wrapping this up to get in to a release now (just ahead of DST changes in the US!).

The only issue left open in #174 -- that one seems a bit more complicated and may have something to with Django itself. I'll dig in to directly on that ticket.
