### ISSUE TITLE
SUB_PATH configuration not working with 2.6.1

### ISSUE THREAD

**Issue by fs1** [babybuddy/babybuddy#896]
I've updated from 2.6.0 to 2.6.1 and now my babybuddy installation in a sub path (https://server/babybuddy/) isn't working any longer. It redirects me to the wrong path (https://server/login/?next=/babybuddy/), ignoring the SUB_PATH setting in the configuration:
`SUB_PATH = "/babybuddy"`

I guess the bug inititates from b6f974c.

If I manually override the path setting in the login form and also in every redirect, I can manage to see the dashboard.

**Comment by cdubz** [comment]
Damn. @MrApplejuice any ideas?

**Comment by cdubz** [comment]
@fs1 can you confirm if you are using HA for your Baby Buddy instance? My understanding of #852 was that it would only impact HA installations. Just want to verify whether this impacts anyone using `SUB_PATH` or just HA + `SUB_PATH`.

**Comment by fs1** [comment]
hm no, I am not using homeassistant. I am running an apache webserver, gunicorn for the python magic and data is stored in a postgres database.

**Comment by MrApplejuice** [comment]
Hi sorry, a bit late to the party! The extension I wrote should only be active for home assistant installs. I will do a quick code review on my side.

**Comment by MrApplejuice** [comment]
@fs1 - can you by any chance make live changes to the code on your server for testing? For which I can see that my homeassistant middleware is doing something:

https://github.com/babybuddy/babybuddy/blob/3d4ccc04d0918ae9ae6f0da10dd29b5f10e77466/babybuddy/middleware.py#L155-L158

If you comment out that branch, nothing should happen anymore at all. Maybe, the `set_script_prefix(self.original_script_prefix)` causes issues? It is needed for HomeAssistant in cases where people use the non-ingress hosting option, which just exposes a regular old port to the babybuddy server. So the branch is there for a reason, but I cannot imaging that it interferes with SUB_PATH...

Still worth a try to debug this. @fs1, you can also be a lot more radical and try to replace the entire `def __call__` - body with the line:

```
    def __call__(self, request: HttpRequest):
        return self.get_response(request)
```

This will disable any functionality of the entire HomeAssistant middleware...

**Comment by fs1** [comment]
If I comment out
```
155       #  if apply_x_ingress_path:
156       #      set_script_prefix("/" + x_ingress_path.lstrip("/"))
157       #  else:
158       #      set_script_prefix(self.original_script_prefix)
```
it's working again.

If I only comment out lines 157 and 158, it's also working:
```
157       #  else:
158       #      set_script_prefix(self.original_script_prefix)
```

If I replace the `def __call__` - body, it works again, too. But that's obvious at this moment, I guess.

**Comment by MrApplejuice** [comment]
Roger! Thank you for testing, I did not have a setup handy to test a reverse-sub path proxy setup right now. I suggest that you leave the hack in your server then, and I submit a patch to actually fully disabled the middleware when `ENABLE_HOME_ASSISTANT_SUPPORT = False`. The fall-through I created makes the code simpler and seemed more elegant, but clearly causes bugs, so it is a no-go.

**Comment by cdubz** [comment]
Thanks, @MrApplejuice! Cut a new v2.6.3 with this fix. Let us know if it works, @fs1.

**Comment by fs1** [comment]
2.6.3 and SUB_PATH is working again. Thx, guys.
