### ISSUE TITLE
pre-filled date/time

### ISSUE THREAD

**Issue by LuisaGeraghty** [babybuddy/babybuddy#91]
Hi,
When you add an event, the end time is pre-filled, but it would make a lot more sense for the start time to be filled, because you'd be marking it at the time it happened. 

Alternatively, have both pre-filled so you can amend the relevant one either when you go back to it to mark the end or to save time when backdating.

![Screenshot_20200118-170516](https://user-images.githubusercontent.com/60041750/72667627-ca3de680-3a15-11ea-838b-a7dabf39de7d.png)
![Screenshot_20200118-170507](https://user-images.githubusercontent.com/60041750/72667638-e3469780-3a15-11ea-9f89-d8a568108f12.png)

**Comment by cdubz** [comment]
My thinking there is that if you’re going to enter something manually, you’re likely to do it at the end of the thing. When my wife and I used this we did everything that had a duration with timers and that means both fields would be filled by the timer values automatically. I would guess that’s how most users would operate but I also have no way of knowing that (:

Although maybe the behavior could be configurable per user...

**Comment by LuisaGeraghty** [comment]
I currently use one where you press start, then it begins a stopwatch until you press end. For me and my extreme baby brain, it's much more useful because I don't have to keep a sense of time, I'm outsourcing it to the app!

**Comment by cdubz** [comment]
Baby Buddy has timers for that (: Tap the timer icon in the upper right corner and then click the entry type to stop the timer and start a new entry. —

![DF85BB82-2A14-4823-B24B-F25CBF3FABFE](https://user-images.githubusercontent.com/10456740/72670363-6275a480-39f1-11ea-8792-1271eb4c0252.jpeg)

**Comment by LuisaGeraghty** [comment]
Oh I see! I wouldn't have thought to click on that icon, because my thought was simply that I wanted to add data therefore I press the plus icon. No idea what I thought the clock icon was for. In which case, I would suggest any of the following:
1) changing the plus icon to something like a notepad, to slow down the user and make them look at both options, making the past/present split more visible to the user
2) changing the terminology under the plus icon so it's in the past tense (i.e. "sleep" becomes "slept", "feeding" becomes "fed")
3) on the desktop version, placing the timers underneath the categories in "activities". I've done a very rough mockup of this. ("custom" should have a "start timer" as well as " view timer" under it, but I need to go right now, hopefully you see the theory though)

Also, I just want to say thanks for replying so quickly to this!
![image](https://user-images.githubusercontent.com/60041750/72671072-f1f47500-3a3c-11ea-8a55-7cd376b27aa6.png)


I wanted to try and do some mockups

**Comment by cdubz** [comment]
The menu has always been something of a mess, so I'm happy to get your feedback here. I think I see what you are suggesting and I'll fiddle with it a bit. I'm not totally sold on using past tense for the entry add menu items, but I do think what you are getting it would make the timers more obvious.

I also wonder if the "+" icon should even be there in mobile or if that should just a hamburger menu or something. The timers really are the most important part of the app, I think.

Happy to take more feedback, especially from folks with UI/UX experience. I'm terrible with that and don't really know how to find folks who may be interested in contributing in that way.

#32 has some discussion around this as well.

**Comment by LostSoulfly** [comment]
Perhaps adding a "Now" button to input the current date and time? Generally, I open the calendar and click the date each time to populate the fields. A "Now" button would allow quickly changing the relevant hours/minutes for any field not pre-defined. Hell, you could just make the labels themselves fill in the current time to keep it uncluttered.

**Comment by cdubz** [comment]
@LostSoulfly I like that idea, I have broken that off in to a specific issue.
