### ISSUE TITLE
Timeline is rounding numbers - dangerous for temperature values

### ISSUE THREAD

**Issue by pkern** [babybuddy/babybuddy#913]
The timeline code intends to format the temperature with one significant digit after the decimal point (`%(temperature).0f`). At least in my installation it instead prints them rounded to the nearest full integer for some reason. The full value is visible from the temperature measurement list, but it'd be useful if the timeline would not misrepresent temperature values.

(Thanks for working on this!)

**Comment by cdubz** [comment]
Thanks for flagging. Just adding context for where this is handled for now --

https://github.com/babybuddy/babybuddy/blob/823dc3854514d3c770f9dbaad1636bc5d82177e7/core/timeline.py#L240-L245

I think this is not correct, right? `.0f` would format e.g. "96.2" as "96". It should be `.1f` or `.2f`, I think?

**Comment by pkern** [comment]
> I think this is not correct, right? `.0f` would format e.g. "96.2" as "96". It should be `.1f` or `.2f`, I think?

Gah you are right. Thanks for the speedy fix! My brain was in Sheets mode where it's #.0 to get two significant digits.
