### ISSUE TITLE
WHO weight percentiles not working

### ISSUE THREAD

**Issue by JohnnyVi** [babybuddy/babybuddy#927]
The who percentiles for weight are just zero, while they should be rising linear graphs.
There are multiple weight recordings.
Am I missing something or is the feature broken

**Comment by antropolouco** [comment]
Hey there!

How are you?

Here for me, everything seems to be fine:

![image](https://github.com/user-attachments/assets/33bb45e1-7556-44ab-a8b2-9bde3c0e8fdb)

How are weigths being recorded there?

In my case, I have a working Baby Buddy instance for a baby which is just a few weeks old, so for instance my entries are like "3.33", "3.52" (kg) and so on. As I said, the mentioned report seems to be working just fine here. I did face similar issues with reports, BUT then I realized that I wasn't registering the entries in the proper format (so it might be your case yoo).

Best regards and abrazos desde Brasil

**Comment by JohnnyVi** [comment]
Hi!

You gave me the solution! I entered the weight in grams (instead of kilogram) because this is what you do with newborns!
I changed the values and now it works!

**Comment by JohnnyVi** [comment]
Stupid user error: entered the weight in grams instead of kilogram

**Comment by lukasMega** [comment]
I think it's not clear. I did the same mistake and used grams instead of kg.

**Comment by cdubz** [comment]
Yes, it’s absolutely not clear 😁

Lack of units was initially intentional, but I’m leaning more now towards adding them.

#689 is kind of where I am tracking this.

**Comment by antropolouco** [comment]
> Hi!
> 
> You gave me the solution! I entered the weight in grams (instead of kilogram) because this is what you do with newborns! I changed the values and now it works!

That's nice to hear!

I hope you are enjoying Baby Buddy as much as I do, so the project keeps growing and improving.

Saludos
